#pragma once

#include <string>

namespace HydraTest::Formula::Representation::Contagious::Parser {
    inline std::string contagiousFormulaRepresentationParserNoCommentInput = "p cnf 10 9\n"
                                                                             "1 0\n"
                                                                             "-1 2 0\n"
                                                                             "-1 3 0\n"
                                                                             "-2 4 5 0\n"
                                                                             "-4 6 0\n"
                                                                             "-4 7 0\n"
                                                                             "-5 8 0\n"
                                                                             "-5 9 0\n"
                                                                             "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserCommentsInput = "c Comment 1\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "p cnf 10 9\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "c Comment 2\n"
                                                                            "1 0\n"
                                                                            "-1 2 0\n"
                                                                            "c Comment 3\n"
                                                                            "-1 3 0\n"
                                                                            "-2 4 5 0\n"
                                                                            "-4 6 0\n"
                                                                            "c Comment 4\n"
                                                                            "c Comment 5\n"
                                                                            "-4 7 0\n"
                                                                            "-5 8 0\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "-5 9 0\n"
                                                                            "-3 -10 0\n"
                                                                            "c Comment 6\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n";

    inline std::string contagiousFormulaRepresentationParserLetterCaseInput = "C Comment 1\n"
                                                                              "P cNF 10 9\n"
                                                                              "1 0\n"
                                                                              "-1 2 0\n"
                                                                              "-1 3 0\n"
                                                                              "-2 4 5 0\n"
                                                                              "-4 6 0\n"
                                                                              "-4 7 0\n"
                                                                              "-5 8 0\n"
                                                                              "-5 9 0\n"
                                                                              "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserMultipleLineClauseInput = "p cnf 10 9\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 \n"
                                                                                      "3 0\n"
                                                                                      "-2 \n"
                                                                                      "4 \n"
                                                                                      "5 \n"
                                                                                      "0\n"
                                                                                      "-4\n"
                                                                                      "6 0\n"
                                                                                      "-4 7 \n"
                                                                                      "0\n"
                                                                                      "-5 8\n"
                                                                                      "0\n"
                                                                                      "-5 \n"
                                                                                      "9 \n"
                                                                                      "0\n"
                                                                                      "-3\n"
                                                                                      "-10\n"
                                                                                      "0\n";

    inline std::string contagiousFormulaRepresentationParserEmptyLinesInput = "p cnf 10 9\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "1 0\n"
                                                                              "-1 2 0\n"
                                                                              "\n"
                                                                              "-1 3 0\n"
                                                                              "-2 4 5 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "-4 6 0\n"
                                                                              "-4 7 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "-5 8 0\n"
                                                                              "-5 9 \n"
                                                                              "\n"
                                                                              "\n"
                                                                              "0\n"
                                                                              "-3 -10 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "\n";

    inline std::string contagiousFormulaRepresentationParserComplementaryLiteralsForbiddenInput = "p cnf 10 9\n"
                                                                                                  "1 0\n"
                                                                                                  "-1 2 0\n"
                                                                                                  "-1 3 0\n"
                                                                                                  "-2 4 5 0\n"
                                                                                                  "-4 6 4 0\n"
                                                                                                  "-4 7 0\n"
                                                                                                  "-5 8 0\n"
                                                                                                  "-5 9 0\n"
                                                                                                  "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserDuplicateLiteralsInput = "p cnf 10 9\n"
                                                                                     "1 0\n"
                                                                                     "-1 2 2 0\n"
                                                                                     "-1 3 0\n"
                                                                                     "-2 4 5 4 0\n"
                                                                                     "-4 6 0\n"
                                                                                     "-4 7 -4 0\n"
                                                                                     "-5 8 -5 -5 0\n"
                                                                                     "-5 9 9 9 0\n"
                                                                                     "-3 -10 -3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserUnsatInput = "p cnf 3 6\n"
                                                                         "1 0\n"
                                                                         "-1 2 0\n"
                                                                         "-1 3 0\n"
                                                                         "-2 -3 1 0\n"
                                                                         "-3 -2 0\n"
                                                                         "2 3 0\n";

    inline std::string contagiousFormulaRepresentationParserUnitClausesInput = "p cnf 10 9\n"
                                                                               "1 0\n"
                                                                               "-1 2 0\n"
                                                                               "-1 3 0\n"
                                                                               "-2 4 5 0\n"
                                                                               "-4 6 0\n"
                                                                               "-4 0\n"
                                                                               "-5 8 0\n"
                                                                               "-5 0\n"
                                                                               "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserTabularInput = "p\tcnf 10\t9\n"
                                                                           "1 0\t\t\t\n"
                                                                           "-1 2\t0\n"
                                                                           "-1\t3 0\n"
                                                                           "-2 \t4  \t5 0\n"
                                                                           "-4 6 0\n"
                                                                           "-4\t\t7 0\n"
                                                                           "-5 8 0\n"
                                                                           "-5 9 0\n"
                                                                           "-3\t\t-10\t 0\n";

    inline std::string contagiousFormulaRepresentationParserSizeInput = "p cnf 10 9 18\n"
                                                                        "1 0\n"
                                                                        "-1 2 0\n"
                                                                        "-1 3 0\n"
                                                                        "-2 4 5 0\n"
                                                                        "-4 6 0\n"
                                                                        "-4 7 0\n"
                                                                        "-5 8 0\n"
                                                                        "-5 9 0\n"
                                                                        "-3 -10 0";

    inline std::string contagiousFormulaRepresentationParserProblemLineTabularInput = "p\tcnf\t\t10\t\t\t9\t\t\t\t\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineMissingInput = "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLinePositionInput = "1 0\n"
                                                                                       "p cnf 10 9\n"
                                                                                       "-1 2 0\n"
                                                                                       "-1 3 0\n"
                                                                                       "-2 4 5 0\n"
                                                                                       "-4 6 0\n"
                                                                                       "-4 7 0\n"
                                                                                       "-5 8 0\n"
                                                                                       "-5 9 0\n"
                                                                                       "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLinePInput = "a cnf 10 9\n"
                                                                                "1 0\n"
                                                                                "-1 2 0\n"
                                                                                "-1 3 0\n"
                                                                                "-2 4 5 0\n"
                                                                                "-4 6 0\n"
                                                                                "-4 7 0\n"
                                                                                "-5 8 0\n"
                                                                                "-5 9 0\n"
                                                                                "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLinePSpaceInput = "pcnf 10 9\n"
                                                                                     "1 0\n"
                                                                                     "-1 2 0\n"
                                                                                     "-1 3 0\n"
                                                                                     "-2 4 5 0\n"
                                                                                     "-4 6 0\n"
                                                                                     "-4 7 0\n"
                                                                                     "-5 8 0\n"
                                                                                     "-5 9 0\n"
                                                                                     "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineCnfInput = "p nnf 10 9\n"
                                                                                  "1 0\n"
                                                                                  "-1 2 0\n"
                                                                                  "-1 3 0\n"
                                                                                  "-2 4 5 0\n"
                                                                                  "-4 6 0\n"
                                                                                  "-4 7 0\n"
                                                                                  "-5 8 0\n"
                                                                                  "-5 9 0\n"
                                                                                  "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineCnfSpaceInput = "p cnf10 9\n"
                                                                                       "1 0\n"
                                                                                       "-1 2 0\n"
                                                                                       "-1 3 0\n"
                                                                                       "-2 4 5 0\n"
                                                                                       "-4 6 0\n"
                                                                                       "-4 7 0\n"
                                                                                       "-5 8 0\n"
                                                                                       "-5 9 0\n"
                                                                                       "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineNumberOfVariablesNegativeInput = "p cnf -10 9\n"
                                                                                                        "1 0\n"
                                                                                                        "-1 2 0\n"
                                                                                                        "-1 3 0\n"
                                                                                                        "-2 4 5 0\n"
                                                                                                        "-4 6 0\n"
                                                                                                        "-4 7 0\n"
                                                                                                        "-5 8 0\n"
                                                                                                        "-5 9 0\n"
                                                                                                        "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineNumberOfVariablesNotNumberInput = "p cnf a 9\n"
                                                                                                         "1 0\n"
                                                                                                         "-1 2 0\n"
                                                                                                         "-1 3 0\n"
                                                                                                         "-2 4 5 0\n"
                                                                                                         "-4 6 0\n"
                                                                                                         "-4 7 0\n"
                                                                                                         "-5 8 0\n"
                                                                                                         "-5 9 0\n"
                                                                                                         "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineNumberOfClausesNegativeInput = "p cnf 10 -9\n"
                                                                                                      "1 0\n"
                                                                                                      "-1 2 0\n"
                                                                                                      "-1 3 0\n"
                                                                                                      "-2 4 5 0\n"
                                                                                                      "-4 6 0\n"
                                                                                                      "-4 7 0\n"
                                                                                                      "-5 8 0\n"
                                                                                                      "-5 9 0\n"
                                                                                                      "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineNumberOfClausesNotNumberInput = "p cnf 10 a\n"
                                                                                                       "1 0\n"
                                                                                                       "-1 2 0\n"
                                                                                                       "-1 3 0\n"
                                                                                                       "-2 4 5 0\n"
                                                                                                       "-4 6 0\n"
                                                                                                       "-4 7 0\n"
                                                                                                       "-5 8 0\n"
                                                                                                       "-5 9 0\n"
                                                                                                       "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineSizeNegativeInput = "p cnf 10 9 -18\n"
                                                                                           "1 0\n"
                                                                                           "-1 2 0\n"
                                                                                           "-1 3 0\n"
                                                                                           "-2 4 5 0\n"
                                                                                           "-4 6 0\n"
                                                                                           "-4 7 0\n"
                                                                                           "-5 8 0\n"
                                                                                           "-5 9 0\n"
                                                                                           "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineSizeNotNumberInput = "p cnf 10 9 a\n"
                                                                                            "1 0\n"
                                                                                            "-1 2 0\n"
                                                                                            "-1 3 0\n"
                                                                                            "-2 4 5 0\n"
                                                                                            "-4 6 0\n"
                                                                                            "-4 7 0\n"
                                                                                            "-5 8 0\n"
                                                                                            "-5 9 0\n"
                                                                                            "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineMoreParametersInput = "p cnf 10 9 18 a\n"
                                                                                             "1 0\n"
                                                                                             "-1 2 0\n"
                                                                                             "-1 3 0\n"
                                                                                             "-2 4 5 0\n"
                                                                                             "-4 6 0\n"
                                                                                             "-4 7 0\n"
                                                                                             "-5 8 0\n"
                                                                                             "-5 9 0\n"
                                                                                             "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineMoreParametersNumberInput = "p cnf 10 9 18 1\n"
                                                                                                   "1 0\n"
                                                                                                   "-1 2 0\n"
                                                                                                   "-1 3 0\n"
                                                                                                   "-2 4 5 0\n"
                                                                                                   "-4 6 0\n"
                                                                                                   "-4 7 0\n"
                                                                                                   "-5 8 0\n"
                                                                                                   "-5 9 0\n"
                                                                                                   "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserProblemLineLessParametersInput = "p cnf 10\n"
                                                                                             "1 0\n"
                                                                                             "-1 2 0\n"
                                                                                             "-1 3 0\n"
                                                                                             "-2 4 5 0\n"
                                                                                             "-4 6 0\n"
                                                                                             "-4 7 0\n"
                                                                                             "-5 8 0\n"
                                                                                             "-5 9 0\n"
                                                                                             "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderInput = "c t mc\n"
                                                                                       "p cnf 6 4\n"
                                                                                       "c t wmc\n"
                                                                                       "-1 -2 0\n"
                                                                                       "c t pmc\n"
                                                                                       "2 3 -4 0\n"
                                                                                       "c t pwmc\n"
                                                                                       "4 5 0\n"
                                                                                       "c t a\n"
                                                                                       "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderNoModelCountingHeaderInput = "c tmp\n"
                                                                                                            "p cnf 6 4\n"
                                                                                                            "-1 -2 0\n"
                                                                                                            "2 3 -4 0\n"
                                                                                                            "4 5 0\n"
                                                                                                            "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMissingInput = "p cnf 6 4\n"
                                                                                              "-1 -2 0\n"
                                                                                              "2 3 -4 0\n"
                                                                                              "4 5 0\n"
                                                                                              "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderBeforeProblemLineInput = "c c comment\n"
                                                                                                        "c t mc\n"
                                                                                                        "c c comment\n"
                                                                                                        "p cnf 6 4\n"
                                                                                                        "c c comment\n"
                                                                                                        "-1 -2 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "2 3 -4 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "4 5 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "4 6 0\n"
                                                                                                        "ccomment\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderAfterProblemLineInput = "c c comment\n"
                                                                                                       "p cnf 6 4\n"
                                                                                                       "c c comment\n"
                                                                                                       "c t wmc\n"
                                                                                                       "c c comment\n"
                                                                                                       "-1 -2 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "2 3 -4 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "4 5 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "4 6 0\n"
                                                                                                       "c\t\n"
                                                                                                       "c\t";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderInTheMiddleInput = "c c comment\n"
                                                                                                  "p cnf 6 4\n"
                                                                                                  "c c comment\n"
                                                                                                  "-1 -2 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "2 3 -4 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "c t pmc\n"
                                                                                                  "c c comment\n"
                                                                                                  "4 5 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "4 6 0\n"
                                                                                                  "c \n"
                                                                                                  "c ";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderAtTheEndInput = "c c comment\n"
                                                                                               "p cnf 6 4\n"
                                                                                               "c c comment\n"
                                                                                               "-1 -2 0\n"
                                                                                               "c c comment\n"
                                                                                               "2 3 -4 0\n"
                                                                                               "c c comment\n"
                                                                                               "4 5 0\n"
                                                                                               "c c comment\n"
                                                                                               "4 6 0\n"
                                                                                               "c c comment\n"
                                                                                               "c t pwmc\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderTabularInput = "p cnf 6 4\n"
                                                                                              "c\tt\t\tmc\t\t\t\n"
                                                                                              "-1 -2 0\n"
                                                                                              "2 3 -4 0\n"
                                                                                              "4 5 0\n"
                                                                                              "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMissingModelCountingTypeInput = "p cnf 6 4\n"
                                                                                                               "c t\n"
                                                                                                               "-1 -2 0\n"
                                                                                                               "2 3 -4 0\n"
                                                                                                               "4 5 0\n"
                                                                                                               "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMissingModelCountingTypeTabularInput = "p cnf 6 4\n"
                                                                                                                      "-1 -2 0\n"
                                                                                                                      "c t\t\n"
                                                                                                                      "2 3 -4 0\n"
                                                                                                                      "4 5 0\n"
                                                                                                                      "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderUnknownModelCountingTypeInput = "c t a\n"
                                                                                                               "p cnf 6 4\n"
                                                                                                               "-1 -2 0\n"
                                                                                                               "2 3 -4 0\n"
                                                                                                               "4 5 0\n"
                                                                                                               "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderLetterCaseInput = "C T WmC\n"
                                                                                                 "p cnf 6 4\n"
                                                                                                 "-1 -2 0\n"
                                                                                                 "2 3 -4 0\n"
                                                                                                 "4 5 0\n"
                                                                                                 "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderTSpaceInput = "p cnf 6 4\n"
                                                                                             "ct pwmc\n"
                                                                                             "-1 -2 0\n"
                                                                                             "2 3 -4 0\n"
                                                                                             "4 5 0\n"
                                                                                             "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderModelCountingTypeSpaceInput = "p cnf 6 4\n"
                                                                                                             "c tpwmc\n"
                                                                                                             "-1 -2 0\n"
                                                                                                             "2 3 -4 0\n"
                                                                                                             "4 5 0\n"
                                                                                                             "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMoreParametersInput = "p cnf 6 4\n"
                                                                                                     "c t pwmc a\n"
                                                                                                     "-1 -2 0\n"
                                                                                                     "2 3 -4 0\n"
                                                                                                     "4 5 0\n"
                                                                                                     "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMoreParametersNumberInput = "p cnf 6 4\n"
                                                                                                           "-1 -2 0\n"
                                                                                                           "2 3 -4 0\n"
                                                                                                           "4 5 0\n"
                                                                                                           "4 6 0\n"
                                                                                                           "c t pwmc\t1\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMoreHeadersSameInput = "c t mc\n"
                                                                                                      "p cnf 6 4\n"
                                                                                                      "c t mc\n"
                                                                                                      "-1 -2 0\n"
                                                                                                      "2 3 -4 0\n"
                                                                                                      "4 5 0\n"
                                                                                                      "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserModelCountingHeaderMoreHeadersDifferentInput = "c t wmc\n"
                                                                                                           "p cnf 6 4\n"
                                                                                                           "c t pmc\n"
                                                                                                           "-1 -2 0\n"
                                                                                                           "2 3 -4 0\n"
                                                                                                           "4 5 0\n"
                                                                                                           "4 6 0\n";

    inline std::string contagiousFormulaRepresentationParserClauseNotNumberInput = "p cnf 10 9 18\n"
                                                                                   "1 0\n"
                                                                                   "-1 2 0\n"
                                                                                   "-1 3 0\n"
                                                                                   "-2 4 5 0\n"
                                                                                   "-4 a 0\n"
                                                                                   "-4 7 0\n"
                                                                                   "-5 8 0\n"
                                                                                   "-5 9 0\n"
                                                                                   "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserMissingEndOfClauseInput = "p cnf 10 9 18\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10\n";

    inline std::string contagiousFormulaRepresentationParserEmptyClauseInput = "p cnf 10 9 18\n"
                                                                               "1 0\n"
                                                                               "-1 2 0\n"
                                                                               "-1 3 0\n"
                                                                               "-2 4 5 0\n"
                                                                               "-4 6 0\n"
                                                                               "0\n"
                                                                               "-5 8 0\n"
                                                                               "-5 9 0\n"
                                                                               "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserEmptyClauseComplementaryLiteralsInput = "p cnf 10 9 18\n"
                                                                                                    "1 0\n"
                                                                                                    "-1 2 0\n"
                                                                                                    "-1 3 0\n"
                                                                                                    "-2 4 5 0\n"
                                                                                                    "-4 6 0\n"
                                                                                                    "-4 4 0\n"
                                                                                                    "-5 8 0\n"
                                                                                                    "-5 9 0\n"
                                                                                                    "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserUnusedVariablesInput = "p cnf 15 9 18\n"
                                                                                   "1 0\n"
                                                                                   "-1 2 0\n"
                                                                                   "-1 3 0\n"
                                                                                   "-2 4 5 0\n"
                                                                                   "-4 6 0\n"
                                                                                   "-4 7 0\n"
                                                                                   "-5 8 0\n"
                                                                                   "-5 9 0\n"
                                                                                   "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserMoreVariablesInput = "p cnf 9 9 18\n"
                                                                                 "1 0\n"
                                                                                 "-1 2 0\n"
                                                                                 "-1 3 0\n"
                                                                                 "-2 4 5 0\n"
                                                                                 "-4 6 0\n"
                                                                                 "-4 7 0\n"
                                                                                 "-5 8 0\n"
                                                                                 "-5 9 0\n"
                                                                                 "-3 -10 0\n";

    inline std::string contagiousFormulaRepresentationParserVariableOutOfRangeInput = "p cnf 10 9 18\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -11 0\n";

    inline std::string contagiousFormulaRepresentationParserOnlyClausesContainingComplementaryLiteralsInput = "p cnf 16 8 29\n"
                                                                                                              "1 -1 2 0\n"
                                                                                                              "-4 -3 3 0\n"
                                                                                                              "-5 6 5 0\n"
                                                                                                              "-7 7 0\n"
                                                                                                              "-8 8 9 -9 0\n"
                                                                                                              "-10 11 12 -11 10 0\n"
                                                                                                              "13 -14 -15 -13 14 0\n"
                                                                                                              "-16 16 16 -16 0\n";

    inline std::string contagiousFormulaRepresentationParserComplementaryLiteralsInput = "p cnf 7 7 21\n"
                                                                                         "-1 1 0\n"
                                                                                         "1 2 0\n"
                                                                                         "2 -2 3 0\n"
                                                                                         "-5 -4 4 0\n"
                                                                                         "5 -6 0\n"
                                                                                         "-7 7 7 0\n"
                                                                                         "1 -2 6 -1 2 -6 0\n";

    inline std::string contagiousFormulaRepresentationParserRedundantLiteralsInput = "p cnf 7 7 23\n"
                                                                                     "1 1 0\n"
                                                                                     "1 2 0\n"
                                                                                     "-2 -2 3 0\n"
                                                                                     "4 -5 4 4 0\n"
                                                                                     "5 -6 0\n"
                                                                                     "-7 7 7 -7 0\n"
                                                                                     "-1 2 -6 -1 2 -6 0\n";
}   // namespace HydraTest::Formula::Representation::Contagious::Parser
