#pragma once

#include <string>

namespace HydraTest::Container::ContagiousOccurrenceList {
    inline std::string contagiousOccurrenceListConstructorResult = "contagiousOccurrenceList1:\n"
                                                                   "Occurrence list: 2 2 2 2 \n"
                                                                   "Separator: 2\n"
                                                                   "Literal offset (end offset): 1: 0 (0) -1: 2 (2) \n"
                                                                   "\n"
                                                                   "contagiousOccurrenceList2:\n"
                                                                   "Occurrence list: 4 4 4 4 4 4 4 4 4 4 \n"
                                                                   "Separator: 4\n"
                                                                   "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                   "\n";

    inline std::string contagiousOccurrenceListCopyAndMoveResult = "Occurrence list: 4 4 4 4 4 4 4 4 4 4 \n"
                                                                   "Separator: 4\n"
                                                                   "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                   "\n"
                                                                   "Copy method\n"
                                                                   "Occurrence list: 4 4 4 4 4 4 4 4 4 4 \n"
                                                                   "Separator: 4\n"
                                                                   "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                   "\n"
                                                                   "Occurrence list: 0 4 4 4 4 4 4 4 4 4 \n"
                                                                   "Separator: 4\n"
                                                                   "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                   "\n"
                                                                   "Move method\n"
                                                                   "Occurrence list: 4 4 4 4 4 4 4 4 4 4 \n"
                                                                   "Separator: 4\n"
                                                                   "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                   "\n";

    inline std::string contagiousOccurrenceListAddOccurrenceResult = "Occurrence list: 4 4 4 4 4 4 4 4 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                     "\n"
                                                                     "Literal: 2, clause ID: 1\n"
                                                                     "Occurrence list: 4 4 4 1 4 4 4 4 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (4) -2: 6 (6) \n"
                                                                     "\n"
                                                                     "Literal: -1, clause ID: 0\n"
                                                                     "Overflow (literal: -1, literalT: 3, offset: 2, end offset: 2)!\n"
                                                                     "\n"
                                                                     "Literal: 1, clause ID: 0\n"
                                                                     "Occurrence list: 0 4 4 1 4 4 4 4 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (4) -2: 6 (6) \n"
                                                                     "\n"
                                                                     "Literal: 1, clause ID: 1\n"
                                                                     "Overflow (literal: 1, literalT: 2, offset: 0, end offset: 1)!\n"
                                                                     "\n"
                                                                     "Literal: -2, clause ID: 0\n"
                                                                     "Occurrence list: 0 4 4 1 4 4 0 4 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (4) -2: 6 (7) \n"
                                                                     "\n"
                                                                     "Literal: 1, clause ID: 0\n"
                                                                     "Attempt to add a duplicate occurrence (literal: 1, literalT: 2, complementary literal: 0, clause ID: 0)!\n"
                                                                     "\n"
                                                                     "Literal: 2, clause ID: 3\n"
                                                                     "Occurrence list: 0 4 4 1 3 4 0 4 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (7) \n"
                                                                     "\n"
                                                                     "Literal: 2, clause ID: 1\n"
                                                                     "Attempt to add a duplicate occurrence (literal: 2, literalT: 4, complementary literal: 0, clause ID: 1)!\n"
                                                                     "\n"
                                                                     "Literal: -2, clause ID: 1\n"
                                                                     "Attempt to add a duplicate occurrence (literal: -2, literalT: 5, complementary literal: 1, clause ID: 1)!\n"
                                                                     "\n"
                                                                     "Literal: -2, clause ID: 0\n"
                                                                     "Attempt to add a duplicate occurrence (literal: -2, literalT: 5, complementary literal: 0, clause ID: 0)!\n"
                                                                     "\n"
                                                                     "Literal: -2, clause ID: 2\n"
                                                                     "Occurrence list: 0 4 4 1 3 4 0 2 4 4 \n"
                                                                     "Separator: 4\n"
                                                                     "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (8) \n"
                                                                     "\n"
                                                                     "Literal: -2, clause ID: 3\n"
                                                                     "Attempt to add a duplicate occurrence (literal: -2, literalT: 5, complementary literal: 1, clause ID: 3)!\n"
                                                                     "\n";

    inline std::string contagiousOccurrenceListRemoveOccurrenceResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                        "\n"
                                                                        "Literal: 2, clause ID: 3\n"
                                                                        "Occurrence list: 0 5 5 1 5 5 0 2 4 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (4) -2: 6 (9) \n"
                                                                        "\n"
                                                                        "Literal: -2, clause ID: 4\n"
                                                                        "Occurrence list: 0 5 5 1 5 5 0 2 5 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (4) -2: 6 (8) \n"
                                                                        "\n"
                                                                        "Literal: -1, clause ID: 1\n"
                                                                        "Attempt to remove an occurrence that does not exist (literal: -1, literalT: 3, clause ID: 1)!\n"
                                                                        "\n"
                                                                        "Literal: 1, clause ID: 0\n"
                                                                        "Occurrence list: 5 5 5 1 5 5 0 2 5 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (4) -2: 6 (8) \n"
                                                                        "\n"
                                                                        "Literal: 2, clause ID: 1\n"
                                                                        "Occurrence list: 5 5 5 5 5 5 0 2 5 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (8) \n"
                                                                        "\n"
                                                                        "Literal: 1, clause ID: 0\n"
                                                                        "Attempt to remove an occurrence that does not exist (literal: 1, literalT: 2, clause ID: 0)!\n"
                                                                        "\n"
                                                                        "Literal: 1, clause ID: 1\n"
                                                                        "Attempt to remove an occurrence that does not exist (literal: 1, literalT: 2, clause ID: 1)!\n"
                                                                        "\n"
                                                                        "Literal: -2, clause ID: 4\n"
                                                                        "Attempt to remove an occurrence that does not exist (literal: -2, literalT: 5, clause ID: 4)!\n"
                                                                        "\n"
                                                                        "Literal: -2, clause ID: 3\n"
                                                                        "Attempt to remove an occurrence that does not exist (literal: -2, literalT: 5, clause ID: 3)!\n"
                                                                        "\n"
                                                                        "Literal: -2, clause ID: 0\n"
                                                                        "Occurrence list: 5 5 5 5 5 5 2 5 5 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (7) \n"
                                                                        "\n"
                                                                        "Literal: -2, clause ID: 2\n"
                                                                        "Occurrence list: 5 5 5 5 5 5 5 5 5 5 \n"
                                                                        "Separator: 5\n"
                                                                        "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (3) -2: 6 (6) \n"
                                                                        "\n";

    inline std::string contagiousOccurrenceListGetOccurrencesResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                      "Separator: 5\n"
                                                                      "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                      "\n"
                                                                      "Initialized:\n"
                                                                      "Variable: \n"
                                                                      "1: 1\n"
                                                                      "2: 5\n"
                                                                      "\n"
                                                                      "Vector:\n"
                                                                      "1 (1): 0 \n"
                                                                      "-1 (0): \n"
                                                                      "2 (2): 1 3 \n"
                                                                      "-2 (3): 0 2 4 \n"
                                                                      "\n"
                                                                      "Set:\n"
                                                                      "1: 0 \n"
                                                                      "-1: \n"
                                                                      "2: 1 3 \n"
                                                                      "-2: 0 2 4 \n"
                                                                      "\n"
                                                                      "Removing:\n"
                                                                      "Occurrence list: 5 5 5 1 5 5 0 4 5 5 \n"
                                                                      "Separator: 5\n"
                                                                      "Literal offset (end offset): 1: 0 (0) -1: 2 (2) 2: 3 (4) -2: 6 (8) \n"
                                                                      "\n"
                                                                      "Variable: \n"
                                                                      "1: 0\n"
                                                                      "2: 3\n"
                                                                      "\n"
                                                                      "Vector:\n"
                                                                      "1 (0): \n"
                                                                      "-1 (0): \n"
                                                                      "2 (1): 1 \n"
                                                                      "-2 (2): 0 4 \n"
                                                                      "\n"
                                                                      "Set:\n"
                                                                      "1: \n"
                                                                      "-1: \n"
                                                                      "2: 1 \n"
                                                                      "-2: 0 4 \n"
                                                                      "\n"
                                                                      "Adding:\n"
                                                                      "Occurrence list: 0 5 5 1 3 5 0 4 2 5 \n"
                                                                      "Separator: 5\n"
                                                                      "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                      "\n"
                                                                      "Variable: \n"
                                                                      "1: 1\n"
                                                                      "2: 5\n"
                                                                      "\n"
                                                                      "Vector:\n"
                                                                      "1 (1): 0 \n"
                                                                      "-1 (0): \n"
                                                                      "2 (2): 1 3 \n"
                                                                      "-2 (3): 0 4 2 \n"
                                                                      "\n"
                                                                      "Set:\n"
                                                                      "1: 0 \n"
                                                                      "-1: \n"
                                                                      "2: 1 3 \n"
                                                                      "-2: 0 2 4 \n"
                                                                      "\n";

    inline std::string contagiousOccurrenceListExistsResult = "Occurrence list: 0 5 5 3 5 5 0 4 5 5 \n"
                                                              "Separator: 5\n"
                                                              "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (4) -2: 6 (8) \n"
                                                              "\n"
                                                              "Literal: 1, clause ID: 0\n"
                                                              "Exists: 1\n"
                                                              "\n"
                                                              "Literal: 1, clause ID: 1\n"
                                                              "Exists: 0\n"
                                                              "\n"
                                                              "Literal: -1, clause ID: 0\n"
                                                              "Exists: 0\n"
                                                              "\n"
                                                              "Literal: 2, clause ID: 3\n"
                                                              "Exists: 1\n"
                                                              "\n"
                                                              "Literal: 2, clause ID: 1\n"
                                                              "Exists: 0\n"
                                                              "\n"
                                                              "Literal: 2, clause ID: 2\n"
                                                              "Exists: 0\n"
                                                              "\n"
                                                              "Literal: -2, clause ID: 0\n"
                                                              "Exists: 1\n"
                                                              "\n"
                                                              "Literal: -2, clause ID: 2\n"
                                                              "Exists: 0\n"
                                                              "\n"
                                                              "Literal: -2, clause ID: 3\n"
                                                              "Exists: 0\n"
                                                              "\n";

    inline std::string contagiousOccurrenceListRemoveOccurrencesResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                         "Separator: 5\n"
                                                                         "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                         "\n"
                                                                         "Removed clauses: 0 4\n"
                                                                         "Occurrence list: 0 5 5 1 3 5 2 5 5 5 \n"
                                                                         "Separator: 5\n"
                                                                         "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (7) \n"
                                                                         "\n";

    inline std::string contagiousOccurrenceListRemoveOccurrencesEmptyResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                              "Separator: 5\n"
                                                                              "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                              "\n"
                                                                              "Removed clauses:\n"
                                                                              "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                              "Separator: 5\n"
                                                                              "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                              "\n";

    inline std::string contagiousOccurrenceListRemoveOccurrencesKeepAllResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                                "Separator: 5\n"
                                                                                "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                                "\n"
                                                                                "Removed clauses:\n"
                                                                                "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                                "Separator: 5\n"
                                                                                "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                                "\n";

    inline std::string contagiousOccurrenceListRemoveOccurrencesRemoveAllResult = "Occurrence list: 0 5 5 1 3 5 0 2 4 5 \n"
                                                                                  "Separator: 5\n"
                                                                                  "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (5) -2: 6 (9) \n"
                                                                                  "\n"
                                                                                  "Removed clauses: 1 3\n"
                                                                                  "Occurrence list: 0 5 5 5 5 5 0 2 4 5 \n"
                                                                                  "Separator: 5\n"
                                                                                  "Literal offset (end offset): 1: 0 (1) -1: 2 (2) 2: 3 (3) -2: 6 (9) \n"
                                                                                  "\n";
}   // namespace HydraTest::Container::ContagiousOccurrenceList
