#pragma once

#include <string>

namespace HydraTest::Formula::Representation::Contagious::UnsortedSubsumption {
    inline std::string contagiousFormulaRepresentationUnsortedSubsumptionResult = "Current formula: \n"
                                                                                  "-1 0 -1 0 1 0 1 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                  "--------------------\n"
                                                                                  "\n"
                                                                                  "Current formula (no duplicate and subsumed clauses): \n"
                                                                                  "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                  "--------------------\n"
                                                                                  "\n"
                                                                                  "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                  "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                  "Used variables: 1 2 3 4 5 6 7 8\n";

    inline std::string contagiousFormulaRepresentationUnsortedSubsumptionAssignmentResult = "Add assignment: -7\n"
                                                                                            "Current formula: \n"
                                                                                            "-1 0 -1 0 1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 -6 -8 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses): \n"
                                                                                            "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                            "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                            "Used variables: 1 2 3 4 5 6 8\n"
                                                                                            "----------------------------------------\n"
                                                                                            "\n"
                                                                                            "Add assignment: 8\n"
                                                                                            "Current formula: \n"
                                                                                            "-1 0 -1 0 1 0 1 0 -4 0 4 0 -6 0 -6 0 6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 4 -5 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses): \n"
                                                                                            "-1 0 1 0 -4 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                            "-1 0 1 0 -4 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                            "Used variables: 1 2 3 4 6\n"
                                                                                            "----------------------------------------\n"
                                                                                            "\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "----------------------------------------\n"
                                                                                            "\n"
                                                                                            "Remove assignment: 8\n"
                                                                                            "Current formula: \n"
                                                                                            "-1 0 -1 0 1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 -6 -8 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses): \n"
                                                                                            "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                            "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                            "Used variables: 1 2 3 4 5 6 8\n"
                                                                                            "----------------------------------------\n"
                                                                                            "\n"
                                                                                            "Remove assignment: -7\n"
                                                                                            "Current formula: \n"
                                                                                            "-1 0 -1 0 1 0 1 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses): \n"
                                                                                            "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                            "--------------------\n"
                                                                                            "\n"
                                                                                            "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                            "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                            "Used variables: 1 2 3 4 5 6 7 8\n"
                                                                                            "----------------------------------------\n"
                                                                                            "\n";

    inline std::string contagiousFormulaRepresentationUnsortedSubsumptionCurrentComponentResult = "Current component: 1\n"
                                                                                                  "Current formula: \n"
                                                                                                  "-1 0 -1 0 1 0 1 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                  "-1 0 1 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                  "-1 0 1 0 \n"
                                                                                                  "Used variables: 1\n"
                                                                                                  "----------------------------------------\n"
                                                                                                  "\n"
                                                                                                  "Current component: 2 3\n"
                                                                                                  "Current formula: \n"
                                                                                                  "-2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                  "-2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                  "-2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                                  "Used variables: 2 3\n"
                                                                                                  "----------------------------------------\n"
                                                                                                  "\n"
                                                                                                  "Current component: 4 5 6 7 8\n"
                                                                                                  "Current formula: \n"
                                                                                                  "-4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                  "-4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                                  "--------------------\n"
                                                                                                  "\n"
                                                                                                  "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                  "-4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                                  "Used variables: 4 5 6 7 8\n"
                                                                                                  "----------------------------------------\n"
                                                                                                  "\n";

    inline std::string contagiousFormulaRepresentationUnsortedVariableSubsumptionResult = "Current formula: \n"
                                                                                          "-1 0 -1 0 1 0 1 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                          "--------------------\n"
                                                                                          "\n"
                                                                                          "Current formula (no duplicate and subsumed clauses): \n"
                                                                                          "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                          "--------------------\n"
                                                                                          "\n"
                                                                                          "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                          "1 0 2 3 0 4 5 0 4 7 0 4 8 0 6 7 0 6 8 0 \n"
                                                                                          "Used variables: 1 2 3 4 5 6 7 8\n";

    inline std::string contagiousFormulaRepresentationUnsortedVariableSubsumptionAssignmentResult = "Add assignment: -7\n"
                                                                                                    "Current formula: \n"
                                                                                                    "-1 0 -1 0 1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 -6 -8 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                    "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                    "1 0 4 0 6 0 2 3 0 \n"
                                                                                                    "Used variables: 1 2 3 4 6\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "\n"
                                                                                                    "Add assignment: 8\n"
                                                                                                    "Current formula: \n"
                                                                                                    "-1 0 -1 0 1 0 1 0 -4 0 4 0 -6 0 -6 0 6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 4 -5 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                    "-1 0 1 0 -4 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                    "1 0 4 0 6 0 2 3 0 \n"
                                                                                                    "Used variables: 1 2 3 4 6\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "\n"
                                                                                                    "\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "\n"
                                                                                                    "Remove assignment: 8\n"
                                                                                                    "Current formula: \n"
                                                                                                    "-1 0 -1 0 1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 -6 -8 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                    "-1 0 1 0 4 0 -6 0 6 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                    "1 0 4 0 6 0 2 3 0 \n"
                                                                                                    "Used variables: 1 2 3 4 6\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "\n"
                                                                                                    "Remove assignment: -7\n"
                                                                                                    "Current formula: \n"
                                                                                                    "-1 0 -1 0 1 0 1 0 -2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                    "-1 0 1 0 -2 -3 0 -2 3 0 2 -3 0 2 3 0 -4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                                    "--------------------\n"
                                                                                                    "\n"
                                                                                                    "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                    "1 0 2 3 0 4 5 0 4 7 0 4 8 0 6 7 0 6 8 0 \n"
                                                                                                    "Used variables: 1 2 3 4 5 6 7 8\n"
                                                                                                    "----------------------------------------\n"
                                                                                                    "\n";

    inline std::string contagiousFormulaRepresentationUnsortedVariableSubsumptionCurrentComponentResult = "Current component: 1\n"
                                                                                                          "Current formula: \n"
                                                                                                          "-1 0 -1 0 1 0 1 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                          "-1 0 1 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                          "1 0 \n"
                                                                                                          "Used variables: 1\n"
                                                                                                          "----------------------------------------\n"
                                                                                                          "\n"
                                                                                                          "Current component: 2 3\n"
                                                                                                          "Current formula: \n"
                                                                                                          "-2 -3 0 -2 -3 0 -2 3 0 -2 3 0 2 -3 0 2 -3 0 2 3 0 2 3 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                          "-2 -3 0 -2 3 0 2 -3 0 2 3 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                          "2 3 0 \n"
                                                                                                          "Used variables: 2 3\n"
                                                                                                          "----------------------------------------\n"
                                                                                                          "\n"
                                                                                                          "Current component: 4 5 6 7 8\n"
                                                                                                          "Current formula: \n"
                                                                                                          "-4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 -4 5 -6 0 4 -5 6 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses): \n"
                                                                                                          "-4 5 0 -4 -8 0 4 -5 0 4 7 0 -6 7 0 -6 -8 0 6 7 0 6 -8 0 \n"
                                                                                                          "--------------------\n"
                                                                                                          "\n"
                                                                                                          "Current formula (no duplicate and subsumed clauses) - unsorted variant: \n"
                                                                                                          "4 5 0 4 7 0 4 8 0 6 7 0 6 8 0 \n"
                                                                                                          "Used variables: 4 5 6 7 8\n"
                                                                                                          "----------------------------------------\n"
                                                                                                          "\n";
}   // namespace HydraTest::Formula::Representation::Contagious::UnsortedSubsumption
