#pragma once

#include <string>

namespace HydraTest::Container::StackWithLevels {
    inline std::string stackWithLevelsConstructorResult = "Stack (with levels): |\n"
                                                          "\n";

    inline std::string stackWithLevelsAddElementsResult = "Stack (with levels): |\n"
                                                          "\n"
                                                          "Add element: 4\n"
                                                          "Stack (with levels): | 4\n"
                                                          "\n"
                                                          "Add element: 5\n"
                                                          "Stack (with levels): | 4 5\n"
                                                          "\n"
                                                          "Add element: 7\n"
                                                          "Stack (with levels): | 4 5 7\n"
                                                          "\n"
                                                          "Add element: 2\n"
                                                          "Stack (with levels): | 4 5 7 2\n"
                                                          "\n"
                                                          "Add element: 1\n"
                                                          "Stack (with levels): | 4 5 7 2 1\n"
                                                          "\n";

    inline std::string stackWithLevelsAddElementsPairResult = "Stack (with levels): |\n"
                                                              "\n"
                                                              "Add element: (3, 4)\n"
                                                              "Stack (with levels): | (3, 4)\n"
                                                              "\n"
                                                              "Add element: (4, 3)\n"
                                                              "Stack (with levels): | (3, 4) (4, 3)\n"
                                                              "\n"
                                                              "Add element: (3, 5)\n"
                                                              "Stack (with levels): | (3, 4) (4, 3) (3, 5)\n"
                                                              "\n"
                                                              "Add element: (2, 4)\n"
                                                              "Stack (with levels): | (3, 4) (4, 3) (3, 5) (2, 4)\n"
                                                              "\n"
                                                              "Add element: (0, 0)\n"
                                                              "Stack (with levels): | (3, 4) (4, 3) (3, 5) (2, 4) (0, 0)\n"
                                                              "\n"
                                                              "Add element: (2, 2)\n"
                                                              "Stack (with levels): | (3, 4) (4, 3) (3, 5) (2, 4) (0, 0) (2, 2)\n"
                                                              "\n";

    inline std::string stackWithLevelsAddMultiOccurrentElementsResult = "Stack (with levels): |\n"
                                                                        "\n"
                                                                        "Add element: 1\n"
                                                                        "Stack (with levels): | 1\n"
                                                                        "\n"
                                                                        "Add element: 2\n"
                                                                        "Stack (with levels): | 1 2\n"
                                                                        "\n"
                                                                        "Add element: 3\n"
                                                                        "Stack (with levels): | 1 2 3\n"
                                                                        "\n"
                                                                        "Add element: 1\n"
                                                                        "Attempt to add the element (1) multiple times!\n"
                                                                        "Stack (with levels): | 1 2 3\n"
                                                                        "\n"
                                                                        "Add element: 4\n"
                                                                        "Stack (with levels): | 1 2 3 4\n"
                                                                        "\n"
                                                                        "Add element: 2\n"
                                                                        "Attempt to add the element (2) multiple times!\n"
                                                                        "Stack (with levels): | 1 2 3 4\n"
                                                                        "\n"
                                                                        "Add element: 5\n"
                                                                        "Stack (with levels): | 1 2 3 4 5\n"
                                                                        "\n"
                                                                        "Add element: 5\n"
                                                                        "Attempt to add the element (5) multiple times!\n"
                                                                        "Stack (with levels): | 1 2 3 4 5\n"
                                                                        "\n";

    inline std::string stackWithLevelsAddMultiOccurrentElementsPairResult = "Stack (with levels): |\n"
                                                                            "\n"
                                                                            "Add element: (1, 2)\n"
                                                                            "Stack (with levels): | (1, 2)\n"
                                                                            "\n"
                                                                            "Add element: (2, 1)\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1)\n"
                                                                            "\n"
                                                                            "Add element: (1, 1)\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1)\n"
                                                                            "\n"
                                                                            "Add element: (1, 2)\n"
                                                                            "Attempt to add the element ((1, 2)) multiple times!\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1)\n"
                                                                            "\n"
                                                                            "Add element: (2, 2)\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1) (2, 2)\n"
                                                                            "\n"
                                                                            "Add element: (2, 1)\n"
                                                                            "Attempt to add the element ((2, 1)) multiple times!\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1) (2, 2)\n"
                                                                            "\n"
                                                                            "Add element: (1, 1)\n"
                                                                            "Attempt to add the element ((1, 1)) multiple times!\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1) (2, 2)\n"
                                                                            "\n"
                                                                            "Add element: (4, 5)\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1) (2, 2) (4, 5)\n"
                                                                            "\n"
                                                                            "Add element: (4, 5)\n"
                                                                            "Attempt to add the element ((4, 5)) multiple times!\n"
                                                                            "Stack (with levels): | (1, 2) (2, 1) (1, 1) (2, 2) (4, 5)\n"
                                                                            "\n";

    inline std::string stackWithLevelsAddLevelsResult = "Stack (with levels): |\n"
                                                        "\n"
                                                        "Add element: 1\n"
                                                        "Add new level\n"
                                                        "Stack (with levels): | 1 |\n"
                                                        "\n"
                                                        "Add element: 2\n"
                                                        "Stack (with levels): | 1 | 2\n"
                                                        "\n"
                                                        "Add element: 3\n"
                                                        "Add new level\n"
                                                        "Stack (with levels): | 1 | 2 3 |\n"
                                                        "\n"
                                                        "Add element: 4\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4\n"
                                                        "\n"
                                                        "Add element: 5\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5\n"
                                                        "\n"
                                                        "Add element: 6\n"
                                                        "Add new level\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 |\n"
                                                        "\n"
                                                        "Add element: 7\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7\n"
                                                        "\n"
                                                        "Add element: 8\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8\n"
                                                        "\n"
                                                        "Add element: 9\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9\n"
                                                        "\n"
                                                        "Add element: 10\n"
                                                        "Add new level\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10 |\n"
                                                        "\n"
                                                        "Add new level\n"
                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10 | |\n"
                                                        "\n";

    inline std::string stackWithLevelsAddLevelsPairResult = "Stack (with levels): |\n"
                                                            "\n"
                                                            "Add element: (1, 1)\n"
                                                            "Add new level\n"
                                                            "Stack (with levels): | (1, 1) |\n"
                                                            "\n"
                                                            "Add element: (2, 2)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2)\n"
                                                            "\n"
                                                            "Add element: (3, 3)\n"
                                                            "Add new level\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) |\n"
                                                            "\n"
                                                            "Add element: (4, 4)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4)\n"
                                                            "\n"
                                                            "Add element: (5, 5)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5)\n"
                                                            "\n"
                                                            "Add element: (6, 6)\n"
                                                            "Add new level\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) |\n"
                                                            "\n"
                                                            "Add element: (7, 7)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7)\n"
                                                            "\n"
                                                            "Add element: (8, 8)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8)\n"
                                                            "\n"
                                                            "Add element: (9, 9)\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9)\n"
                                                            "\n"
                                                            "Add element: (10, 10)\n"
                                                            "Add new level\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10) |\n"
                                                            "\n"
                                                            "Add new level\n"
                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10) | |\n"
                                                            "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelResult = "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9\n"
                                                                 "\n"
                                                                 "Remove current level\n"
                                                                 "Stack (with levels): | 1 | 2 3 | 4 5 6\n"
                                                                 "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelFunctorResult = "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9\n"
                                                                        "\n"
                                                                        "Remove current level\n"
                                                                        "Removed element: 9\n"
                                                                        "Removed element: 8\n"
                                                                        "Removed element: 7\n"
                                                                        "Stack (with levels): | 1 | 2 3 | 4 5 6\n"
                                                                        "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelEmptyResult = "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10 |\n"
                                                                      "\n"
                                                                      "Remove current level\n"
                                                                      "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10\n"
                                                                      "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelPairResult = "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9)\n"
                                                                     "\n"
                                                                     "Remove current level\n"
                                                                     "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6)\n"
                                                                     "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelFunctorPairResult = "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9)\n"
                                                                            "\n"
                                                                            "Remove current level\n"
                                                                            "Removed element: (9, 9)\n"
                                                                            "Removed element: (8, 8)\n"
                                                                            "Removed element: (7, 7)\n"
                                                                            "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6)\n"
                                                                            "\n";

    inline std::string stackWithLevelsRemoveCurrentLevelEmptyPairResult = "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10) |\n"
                                                                          "\n"
                                                                          "Remove current level\n"
                                                                          "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10)\n"
                                                                          "\n";

    inline std::string stackWithLevelsClearResult = "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10 |\n"
                                                    "\n"
                                                    "Clear\n"
                                                    "Stack (with levels):\n"
                                                    "\n";

    inline std::string stackWithLevelsClearFunctorResult = "Stack (with levels): | 1 | 2 3 | 4 5 6 | 7 8 9 10 |\n"
                                                           "\n"
                                                           "Clear\n"
                                                           "Removed element: 10\n"
                                                           "Removed element: 9\n"
                                                           "Removed element: 8\n"
                                                           "Removed element: 7\n"
                                                           "Removed element: 6\n"
                                                           "Removed element: 5\n"
                                                           "Removed element: 4\n"
                                                           "Removed element: 3\n"
                                                           "Removed element: 2\n"
                                                           "Removed element: 1\n"
                                                           "Stack (with levels):\n"
                                                           "\n";

    inline std::string stackWithLevelsClearEmptyResult = "Stack (with levels):\n"
                                                         "\n"
                                                         "Clear\n"
                                                         "Stack (with levels):\n"
                                                         "\n";

    inline std::string stackWithLevelsClearPairResult = "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10) |\n"
                                                        "\n"
                                                        "Clear\n"
                                                        "Stack (with levels):\n"
                                                        "\n";

    inline std::string stackWithLevelsClearFunctorPairResult = "Stack (with levels): | (1, 1) | (2, 2) (3, 3) | (4, 4) (5, 5) (6, 6) | (7, 7) (8, 8) (9, 9) (10, 10) |\n"
                                                               "\n"
                                                               "Clear\n"
                                                               "Removed element: (10, 10)\n"
                                                               "Removed element: (9, 9)\n"
                                                               "Removed element: (8, 8)\n"
                                                               "Removed element: (7, 7)\n"
                                                               "Removed element: (6, 6)\n"
                                                               "Removed element: (5, 5)\n"
                                                               "Removed element: (4, 4)\n"
                                                               "Removed element: (3, 3)\n"
                                                               "Removed element: (2, 2)\n"
                                                               "Removed element: (1, 1)\n"
                                                               "Stack (with levels):\n"
                                                               "\n";

    inline std::string stackWithLevelsClearEmptyPairResult = "Stack (with levels):\n"
                                                             "\n"
                                                             "Clear\n"
                                                             "Stack (with levels):\n"
                                                             "\n";

    inline std::string stackWithLevelsPrintFunctorResult = "Stack (with levels): | 4 | 5 7 | 2 1\n"
                                                           "\n"
                                                           "Printed with functor (+1): | 5 | 6 8 | 3 2 \n";

    inline std::string stackWithLevelsPrintFunctorPairResult = "Stack (with levels): | (3, 4) | (4, 3) (3, 5) | (2, 4) (0, 0) (2, 2) |\n"
                                                               "\n"
                                                               "Printed with functor (+1, +2): | (4, 6) | (5, 5) (4, 7) | (3, 6) (1, 2) (3, 4) | \n";
}   // namespace HydraTest::Container::StackWithLevels
