#pragma once

#include <string>

namespace HydraTest::Formula::Representation::Contiguous::Parser {
    inline std::string contiguousFormulaRepresentationParserNoCommentInput = "p cnf 10 9\n"
                                                                             "1 0\n"
                                                                             "-1 2 0\n"
                                                                             "-1 3 0\n"
                                                                             "-2 4 5 0\n"
                                                                             "-4 6 0\n"
                                                                             "-4 7 0\n"
                                                                             "-5 8 0\n"
                                                                             "-5 9 0\n"
                                                                             "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserCommentsInput = "c Comment 1\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "p cnf 10 9\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "c Comment 2\n"
                                                                            "1 0\n"
                                                                            "-1 2 0\n"
                                                                            "c Comment 3\n"
                                                                            "-1 3 0\n"
                                                                            "-2 4 5 0\n"
                                                                            "-4 6 0\n"
                                                                            "c Comment 4\n"
                                                                            "c Comment 5\n"
                                                                            "-4 7 0\n"
                                                                            "-5 8 0\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n"
                                                                            "-5 9 0\n"
                                                                            "-3 -10 0\n"
                                                                            "c Comment 6\n"
                                                                            "c\n"
                                                                            "c \n"
                                                                            "c\t\n"
                                                                            "c    \n"
                                                                            "c\t\t\t\t\n"
                                                                            "c \t \t\n";

    inline std::string contiguousFormulaRepresentationParserLetterCaseInput = "C Comment 1\n"
                                                                              "P cNF 10 9\n"
                                                                              "1 0\n"
                                                                              "-1 2 0\n"
                                                                              "-1 3 0\n"
                                                                              "-2 4 5 0\n"
                                                                              "-4 6 0\n"
                                                                              "-4 7 0\n"
                                                                              "-5 8 0\n"
                                                                              "-5 9 0\n"
                                                                              "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserMultipleLineClauseInput = "p cnf 10 9\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 \n"
                                                                                      "3 0\n"
                                                                                      "-2 \n"
                                                                                      "4 \n"
                                                                                      "5 \n"
                                                                                      "0\n"
                                                                                      "-4\n"
                                                                                      "6 0\n"
                                                                                      "-4 7 \n"
                                                                                      "0\n"
                                                                                      "-5 8\n"
                                                                                      "0\n"
                                                                                      "-5 \n"
                                                                                      "9 \n"
                                                                                      "0\n"
                                                                                      "-3\n"
                                                                                      "-10\n"
                                                                                      "0\n";

    inline std::string contiguousFormulaRepresentationParserEmptyLinesInput = "p cnf 10 9\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "1 0\n"
                                                                              "-1 2 0\n"
                                                                              "\n"
                                                                              "-1 3 0\n"
                                                                              "-2 4 5 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "-4 6 0\n"
                                                                              "-4 7 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "-5 8 0\n"
                                                                              "-5 9 \n"
                                                                              "\n"
                                                                              "\n"
                                                                              "0\n"
                                                                              "-3 -10 0\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "\n";

    inline std::string contiguousFormulaRepresentationParserComplementaryLiteralsForbiddenInput = "p cnf 10 9\n"
                                                                                                  "1 0\n"
                                                                                                  "-1 2 0\n"
                                                                                                  "-1 3 0\n"
                                                                                                  "-2 4 5 0\n"
                                                                                                  "-4 6 4 0\n"
                                                                                                  "-4 7 0\n"
                                                                                                  "-5 8 0\n"
                                                                                                  "-5 9 0\n"
                                                                                                  "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserDuplicateLiteralsInput = "p cnf 10 9\n"
                                                                                     "1 0\n"
                                                                                     "-1 2 2 0\n"
                                                                                     "-1 3 0\n"
                                                                                     "-2 4 5 4 0\n"
                                                                                     "-4 6 0\n"
                                                                                     "-4 7 -4 0\n"
                                                                                     "-5 8 -5 -5 0\n"
                                                                                     "-5 9 9 9 0\n"
                                                                                     "-3 -10 -3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserUnsatInput = "p cnf 3 6\n"
                                                                         "1 0\n"
                                                                         "-1 2 0\n"
                                                                         "-1 3 0\n"
                                                                         "-2 -3 1 0\n"
                                                                         "-3 -2 0\n"
                                                                         "2 3 0\n";

    inline std::string contiguousFormulaRepresentationParserUnitClausesInput = "p cnf 10 9\n"
                                                                               "1 0\n"
                                                                               "-1 2 0\n"
                                                                               "-1 3 0\n"
                                                                               "-2 4 5 0\n"
                                                                               "-4 6 0\n"
                                                                               "-4 0\n"
                                                                               "-5 8 0\n"
                                                                               "-5 0\n"
                                                                               "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserTabularInput = "p\tcnf 10\t9\n"
                                                                           "1 0\t\t\t\n"
                                                                           "-1 2\t0\n"
                                                                           "-1\t3 0\n"
                                                                           "-2 \t4  \t5 0\n"
                                                                           "-4 6 0\n"
                                                                           "-4\t\t7 0\n"
                                                                           "-5 8 0\n"
                                                                           "-5 9 0\n"
                                                                           "-3\t\t-10\t 0\n";

    inline std::string contiguousFormulaRepresentationParserSizeInput = "p cnf 10 9 18\n"
                                                                        "1 0\n"
                                                                        "-1 2 0\n"
                                                                        "-1 3 0\n"
                                                                        "-2 4 5 0\n"
                                                                        "-4 6 0\n"
                                                                        "-4 7 0\n"
                                                                        "-5 8 0\n"
                                                                        "-5 9 0\n"
                                                                        "-3 -10 0";

    inline std::string contiguousFormulaRepresentationParserProblemLineTabularInput = "p\tcnf\t\t10\t\t\t9\t\t\t\t\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineMissingInput = "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLinePositionInput = "1 0\n"
                                                                                       "p cnf 10 9\n"
                                                                                       "-1 2 0\n"
                                                                                       "-1 3 0\n"
                                                                                       "-2 4 5 0\n"
                                                                                       "-4 6 0\n"
                                                                                       "-4 7 0\n"
                                                                                       "-5 8 0\n"
                                                                                       "-5 9 0\n"
                                                                                       "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLinePInput = "a cnf 10 9\n"
                                                                                "1 0\n"
                                                                                "-1 2 0\n"
                                                                                "-1 3 0\n"
                                                                                "-2 4 5 0\n"
                                                                                "-4 6 0\n"
                                                                                "-4 7 0\n"
                                                                                "-5 8 0\n"
                                                                                "-5 9 0\n"
                                                                                "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLinePSpaceInput = "pcnf 10 9\n"
                                                                                     "1 0\n"
                                                                                     "-1 2 0\n"
                                                                                     "-1 3 0\n"
                                                                                     "-2 4 5 0\n"
                                                                                     "-4 6 0\n"
                                                                                     "-4 7 0\n"
                                                                                     "-5 8 0\n"
                                                                                     "-5 9 0\n"
                                                                                     "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineCnfInput = "p nnf 10 9\n"
                                                                                  "1 0\n"
                                                                                  "-1 2 0\n"
                                                                                  "-1 3 0\n"
                                                                                  "-2 4 5 0\n"
                                                                                  "-4 6 0\n"
                                                                                  "-4 7 0\n"
                                                                                  "-5 8 0\n"
                                                                                  "-5 9 0\n"
                                                                                  "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineCnfSpaceInput = "p cnf10 9\n"
                                                                                       "1 0\n"
                                                                                       "-1 2 0\n"
                                                                                       "-1 3 0\n"
                                                                                       "-2 4 5 0\n"
                                                                                       "-4 6 0\n"
                                                                                       "-4 7 0\n"
                                                                                       "-5 8 0\n"
                                                                                       "-5 9 0\n"
                                                                                       "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineNumberOfVariablesNegativeInput = "p cnf -10 9\n"
                                                                                                        "1 0\n"
                                                                                                        "-1 2 0\n"
                                                                                                        "-1 3 0\n"
                                                                                                        "-2 4 5 0\n"
                                                                                                        "-4 6 0\n"
                                                                                                        "-4 7 0\n"
                                                                                                        "-5 8 0\n"
                                                                                                        "-5 9 0\n"
                                                                                                        "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineNumberOfVariablesNotNumberInput = "p cnf a 9\n"
                                                                                                         "1 0\n"
                                                                                                         "-1 2 0\n"
                                                                                                         "-1 3 0\n"
                                                                                                         "-2 4 5 0\n"
                                                                                                         "-4 6 0\n"
                                                                                                         "-4 7 0\n"
                                                                                                         "-5 8 0\n"
                                                                                                         "-5 9 0\n"
                                                                                                         "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineNumberOfClausesNegativeInput = "p cnf 10 -9\n"
                                                                                                      "1 0\n"
                                                                                                      "-1 2 0\n"
                                                                                                      "-1 3 0\n"
                                                                                                      "-2 4 5 0\n"
                                                                                                      "-4 6 0\n"
                                                                                                      "-4 7 0\n"
                                                                                                      "-5 8 0\n"
                                                                                                      "-5 9 0\n"
                                                                                                      "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineNumberOfClausesNotNumberInput = "p cnf 10 a\n"
                                                                                                       "1 0\n"
                                                                                                       "-1 2 0\n"
                                                                                                       "-1 3 0\n"
                                                                                                       "-2 4 5 0\n"
                                                                                                       "-4 6 0\n"
                                                                                                       "-4 7 0\n"
                                                                                                       "-5 8 0\n"
                                                                                                       "-5 9 0\n"
                                                                                                       "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineSizeNegativeInput = "p cnf 10 9 -18\n"
                                                                                           "1 0\n"
                                                                                           "-1 2 0\n"
                                                                                           "-1 3 0\n"
                                                                                           "-2 4 5 0\n"
                                                                                           "-4 6 0\n"
                                                                                           "-4 7 0\n"
                                                                                           "-5 8 0\n"
                                                                                           "-5 9 0\n"
                                                                                           "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineSizeNotNumberInput = "p cnf 10 9 a\n"
                                                                                            "1 0\n"
                                                                                            "-1 2 0\n"
                                                                                            "-1 3 0\n"
                                                                                            "-2 4 5 0\n"
                                                                                            "-4 6 0\n"
                                                                                            "-4 7 0\n"
                                                                                            "-5 8 0\n"
                                                                                            "-5 9 0\n"
                                                                                            "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineMoreParametersInput = "p cnf 10 9 18 a\n"
                                                                                             "1 0\n"
                                                                                             "-1 2 0\n"
                                                                                             "-1 3 0\n"
                                                                                             "-2 4 5 0\n"
                                                                                             "-4 6 0\n"
                                                                                             "-4 7 0\n"
                                                                                             "-5 8 0\n"
                                                                                             "-5 9 0\n"
                                                                                             "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineMoreParametersNumberInput = "p cnf 10 9 18 1\n"
                                                                                                   "1 0\n"
                                                                                                   "-1 2 0\n"
                                                                                                   "-1 3 0\n"
                                                                                                   "-2 4 5 0\n"
                                                                                                   "-4 6 0\n"
                                                                                                   "-4 7 0\n"
                                                                                                   "-5 8 0\n"
                                                                                                   "-5 9 0\n"
                                                                                                   "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserProblemLineLessParametersInput = "p cnf 10\n"
                                                                                             "1 0\n"
                                                                                             "-1 2 0\n"
                                                                                             "-1 3 0\n"
                                                                                             "-2 4 5 0\n"
                                                                                             "-4 6 0\n"
                                                                                             "-4 7 0\n"
                                                                                             "-5 8 0\n"
                                                                                             "-5 9 0\n"
                                                                                             "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderInput = "c t mc\n"
                                                                                       "p cnf 6 4\n"
                                                                                       "c t wmc\n"
                                                                                       "-1 -2 0\n"
                                                                                       "c t pmc\n"
                                                                                       "2 3 -4 0\n"
                                                                                       "c t pwmc\n"
                                                                                       "4 5 0\n"
                                                                                       "c t a\n"
                                                                                       "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderNoModelCountingHeaderInput = "c tmp\n"
                                                                                                            "p cnf 6 4\n"
                                                                                                            "-1 -2 0\n"
                                                                                                            "2 3 -4 0\n"
                                                                                                            "4 5 0\n"
                                                                                                            "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMissingInput = "p cnf 6 4\n"
                                                                                              "-1 -2 0\n"
                                                                                              "2 3 -4 0\n"
                                                                                              "4 5 0\n"
                                                                                              "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderBeforeProblemLineInput = "c c comment\n"
                                                                                                        "c t mc\n"
                                                                                                        "c c comment\n"
                                                                                                        "p cnf 6 4\n"
                                                                                                        "c c comment\n"
                                                                                                        "-1 -2 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "2 3 -4 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "4 5 0\n"
                                                                                                        "c c comment\n"
                                                                                                        "4 6 0\n"
                                                                                                        "ccomment\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderAfterProblemLineInput = "c c comment\n"
                                                                                                       "p cnf 6 4\n"
                                                                                                       "c c comment\n"
                                                                                                       "c t wmc\n"
                                                                                                       "c c comment\n"
                                                                                                       "-1 -2 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "2 3 -4 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "4 5 0\n"
                                                                                                       "c c comment\n"
                                                                                                       "4 6 0\n"
                                                                                                       "c\t\n"
                                                                                                       "c\t";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderInTheMiddleInput = "c c comment\n"
                                                                                                  "p cnf 6 4\n"
                                                                                                  "c c comment\n"
                                                                                                  "-1 -2 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "2 3 -4 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "c t pmc\n"
                                                                                                  "c c comment\n"
                                                                                                  "4 5 0\n"
                                                                                                  "c c comment\n"
                                                                                                  "4 6 0\n"
                                                                                                  "c \n"
                                                                                                  "c ";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderAtTheEndInput = "c c comment\n"
                                                                                               "p cnf 6 4\n"
                                                                                               "c c comment\n"
                                                                                               "-1 -2 0\n"
                                                                                               "c c comment\n"
                                                                                               "2 3 -4 0\n"
                                                                                               "c c comment\n"
                                                                                               "4 5 0\n"
                                                                                               "c c comment\n"
                                                                                               "4 6 0\n"
                                                                                               "c c comment\n"
                                                                                               "c t pwmc\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderTabularInput = "p cnf 6 4\n"
                                                                                              "c\tt\t\tmc\t\t\t\n"
                                                                                              "-1 -2 0\n"
                                                                                              "2 3 -4 0\n"
                                                                                              "4 5 0\n"
                                                                                              "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMissingModelCountingTypeInput = "p cnf 6 4\n"
                                                                                                               "c t\n"
                                                                                                               "-1 -2 0\n"
                                                                                                               "2 3 -4 0\n"
                                                                                                               "4 5 0\n"
                                                                                                               "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMissingModelCountingTypeTabularInput = "p cnf 6 4\n"
                                                                                                                      "-1 -2 0\n"
                                                                                                                      "c t\t\n"
                                                                                                                      "2 3 -4 0\n"
                                                                                                                      "4 5 0\n"
                                                                                                                      "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderUnknownModelCountingTypeInput = "c t a\n"
                                                                                                               "p cnf 6 4\n"
                                                                                                               "-1 -2 0\n"
                                                                                                               "2 3 -4 0\n"
                                                                                                               "4 5 0\n"
                                                                                                               "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderLetterCaseInput = "C T WmC\n"
                                                                                                 "p cnf 6 4\n"
                                                                                                 "-1 -2 0\n"
                                                                                                 "2 3 -4 0\n"
                                                                                                 "4 5 0\n"
                                                                                                 "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderTSpaceInput = "p cnf 6 4\n"
                                                                                             "ct pwmc\n"
                                                                                             "-1 -2 0\n"
                                                                                             "2 3 -4 0\n"
                                                                                             "4 5 0\n"
                                                                                             "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderModelCountingTypeSpaceInput = "p cnf 6 4\n"
                                                                                                             "c tpwmc\n"
                                                                                                             "-1 -2 0\n"
                                                                                                             "2 3 -4 0\n"
                                                                                                             "4 5 0\n"
                                                                                                             "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMoreParametersInput = "p cnf 6 4\n"
                                                                                                     "c t pwmc a\n"
                                                                                                     "-1 -2 0\n"
                                                                                                     "2 3 -4 0\n"
                                                                                                     "4 5 0\n"
                                                                                                     "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMoreParametersNumberInput = "p cnf 6 4\n"
                                                                                                           "-1 -2 0\n"
                                                                                                           "2 3 -4 0\n"
                                                                                                           "4 5 0\n"
                                                                                                           "4 6 0\n"
                                                                                                           "c t pwmc\t1\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMoreHeadersSameInput = "c t mc\n"
                                                                                                      "p cnf 6 4\n"
                                                                                                      "c t mc\n"
                                                                                                      "-1 -2 0\n"
                                                                                                      "2 3 -4 0\n"
                                                                                                      "4 5 0\n"
                                                                                                      "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserModelCountingHeaderMoreHeadersDifferentInput = "c t wmc\n"
                                                                                                           "p cnf 6 4\n"
                                                                                                           "c t pmc\n"
                                                                                                           "-1 -2 0\n"
                                                                                                           "2 3 -4 0\n"
                                                                                                           "4 5 0\n"
                                                                                                           "4 6 0\n";

    inline std::string contiguousFormulaRepresentationParserClauseNotNumberInput = "p cnf 10 9 18\n"
                                                                                   "1 0\n"
                                                                                   "-1 2 0\n"
                                                                                   "-1 3 0\n"
                                                                                   "-2 4 5 0\n"
                                                                                   "-4 a 0\n"
                                                                                   "-4 7 0\n"
                                                                                   "-5 8 0\n"
                                                                                   "-5 9 0\n"
                                                                                   "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserMissingEndOfClauseInput = "p cnf 10 9 18\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -10\n";

    inline std::string contiguousFormulaRepresentationParserEmptyClauseInput = "p cnf 10 9 18\n"
                                                                               "1 0\n"
                                                                               "-1 2 0\n"
                                                                               "-1 3 0\n"
                                                                               "-2 4 5 0\n"
                                                                               "-4 6 0\n"
                                                                               "0\n"
                                                                               "-5 8 0\n"
                                                                               "-5 9 0\n"
                                                                               "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserEmptyClauseComplementaryLiteralsInput = "p cnf 10 9 18\n"
                                                                                                    "1 0\n"
                                                                                                    "-1 2 0\n"
                                                                                                    "-1 3 0\n"
                                                                                                    "-2 4 5 0\n"
                                                                                                    "-4 6 0\n"
                                                                                                    "-4 4 0\n"
                                                                                                    "-5 8 0\n"
                                                                                                    "-5 9 0\n"
                                                                                                    "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserUnusedVariablesInput = "p cnf 15 9 18\n"
                                                                                   "1 0\n"
                                                                                   "-1 2 0\n"
                                                                                   "-1 3 0\n"
                                                                                   "-2 4 5 0\n"
                                                                                   "-4 6 0\n"
                                                                                   "-4 7 0\n"
                                                                                   "-5 8 0\n"
                                                                                   "-5 9 0\n"
                                                                                   "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserMoreVariablesInput = "p cnf 9 9 18\n"
                                                                                 "1 0\n"
                                                                                 "-1 2 0\n"
                                                                                 "-1 3 0\n"
                                                                                 "-2 4 5 0\n"
                                                                                 "-4 6 0\n"
                                                                                 "-4 7 0\n"
                                                                                 "-5 8 0\n"
                                                                                 "-5 9 0\n"
                                                                                 "-3 -10 0\n";

    inline std::string contiguousFormulaRepresentationParserVariableOutOfRangeInput = "p cnf 10 9 18\n"
                                                                                      "1 0\n"
                                                                                      "-1 2 0\n"
                                                                                      "-1 3 0\n"
                                                                                      "-2 4 5 0\n"
                                                                                      "-4 6 0\n"
                                                                                      "-4 7 0\n"
                                                                                      "-5 8 0\n"
                                                                                      "-5 9 0\n"
                                                                                      "-3 -11 0\n";

    inline std::string contiguousFormulaRepresentationParserOnlyClausesContainingComplementaryLiteralsInput = "p cnf 16 8 29\n"
                                                                                                              "1 -1 2 0\n"
                                                                                                              "-4 -3 3 0\n"
                                                                                                              "-5 6 5 0\n"
                                                                                                              "-7 7 0\n"
                                                                                                              "-8 8 9 -9 0\n"
                                                                                                              "-10 11 12 -11 10 0\n"
                                                                                                              "13 -14 -15 -13 14 0\n"
                                                                                                              "-16 16 16 -16 0\n";

    inline std::string contiguousFormulaRepresentationParserComplementaryLiteralsInput = "p cnf 7 7 21\n"
                                                                                         "-1 1 0\n"
                                                                                         "1 2 0\n"
                                                                                         "2 -2 3 0\n"
                                                                                         "-5 -4 4 0\n"
                                                                                         "5 -6 0\n"
                                                                                         "-7 7 7 0\n"
                                                                                         "1 -2 6 -1 2 -6 0\n";

    inline std::string contiguousFormulaRepresentationParserRedundantLiteralsInput = "p cnf 7 7 23\n"
                                                                                     "1 1 0\n"
                                                                                     "1 2 0\n"
                                                                                     "-2 -2 3 0\n"
                                                                                     "4 -5 4 4 0\n"
                                                                                     "5 -6 0\n"
                                                                                     "-7 7 7 -7 0\n"
                                                                                     "-1 2 -6 -1 2 -6 0\n";
}   // namespace HydraTest::Formula::Representation::Contiguous::Parser
