#pragma once

#include <string>

namespace HydraTest::Container::ComputeConnectedComponents {
    inline std::string computeConnectedComponentsConstructorResult = "Compute connected components\n"
                                                                     "\t1 - root, rank: 0\n"
                                                                     "\t2 - root, rank: 0\n"
                                                                     "\t3 - root, rank: 0\n"
                                                                     "\n";

    inline std::string computeConnectedComponentsIsEmptyResult = "Compute connected components\n"
                                                                 "\t1 - root, rank: 0\n"
                                                                 "\t2 - root, rank: 0\n"
                                                                 "\t3 - root, rank: 0\n"
                                                                 "\t4 - root, rank: 0\n"
                                                                 "\t5 - root, rank: 0\n"
                                                                 "\n"
                                                                 "Is empty: 1\n"
                                                                 "\n";

    inline std::string computeConnectedComponentsAddConnectionResult = "Compute connected components\n"
                                                                       "\t1 - root, rank: 0\n"
                                                                       "\t2 - root, rank: 0\n"
                                                                       "\t3 - root, rank: 0\n"
                                                                       "\n"
                                                                       "Add connection: 1 - 2\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - root, rank: 0\n"
                                                                       "\n"
                                                                       "Add connection: 2 - 1\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - root, rank: 0\n"
                                                                       "\n"
                                                                       "Add connection: 2 - 3\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - 1\n"
                                                                       "\n"
                                                                       "Add connection: 3 - 2\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - 1\n"
                                                                       "\n"
                                                                       "Add connection: 1 - 3\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - 1\n"
                                                                       "\n"
                                                                       "Add connection: 3 - 1\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 1\n"
                                                                       "\t2 - 1\n"
                                                                       "\t3 - 1\n"
                                                                       "\n";

    inline std::string computeConnectedComponentsPathCompressionResult = "Compute connected components\n"
                                                                         "\t1 - root, rank: 3\n"
                                                                         "\t2 - 1\n"
                                                                         "\t3 - 1\n"
                                                                         "\t4 - 3\n"
                                                                         "\t5 - 1\n"
                                                                         "\t6 - 5\n"
                                                                         "\t7 - 5\n"
                                                                         "\t8 - 7\n"
                                                                         "\n"
                                                                         "Compute connected components\n"
                                                                         "\t1 - root, rank: 3\n"
                                                                         "\t2 - 1\n"
                                                                         "\t3 - 1\n"
                                                                         "\t4 - 3\n"
                                                                         "\t5 - 1\n"
                                                                         "\t6 - 5\n"
                                                                         "\t7 - 1\n"
                                                                         "\t8 - 1\n"
                                                                         "\n";

    inline std::string computeConnectedComponentsRankResult = "Compute connected components\n"
                                                              "\t1 - root, rank: 0\n"
                                                              "\t2 - root, rank: 0\n"
                                                              "\t3 - root, rank: 0\n"
                                                              "\t4 - root, rank: 0\n"
                                                              "\t5 - root, rank: 0\n"
                                                              "\t6 - root, rank: 0\n"
                                                              "\n"
                                                              "Add connection: 1 - 2\n"
                                                              "Compute connected components\n"
                                                              "\t1 - root, rank: 1\n"
                                                              "\t2 - 1\n"
                                                              "\t3 - root, rank: 0\n"
                                                              "\t4 - root, rank: 0\n"
                                                              "\t5 - root, rank: 0\n"
                                                              "\t6 - root, rank: 0\n"
                                                              "\n"
                                                              "Add connection: 1 - 3\n"
                                                              "Compute connected components\n"
                                                              "\t1 - root, rank: 1\n"
                                                              "\t2 - 1\n"
                                                              "\t3 - 1\n"
                                                              "\t4 - root, rank: 0\n"
                                                              "\t5 - root, rank: 0\n"
                                                              "\t6 - root, rank: 0\n"
                                                              "\n"
                                                              "Add connection: 4 - 1\n"
                                                              "Compute connected components\n"
                                                              "\t1 - root, rank: 1\n"
                                                              "\t2 - 1\n"
                                                              "\t3 - 1\n"
                                                              "\t4 - 1\n"
                                                              "\t5 - root, rank: 0\n"
                                                              "\t6 - root, rank: 0\n"
                                                              "\n"
                                                              "Add connection: 5 - 6\n"
                                                              "Compute connected components\n"
                                                              "\t1 - root, rank: 1\n"
                                                              "\t2 - 1\n"
                                                              "\t3 - 1\n"
                                                              "\t4 - 1\n"
                                                              "\t5 - root, rank: 1\n"
                                                              "\t6 - 5\n"
                                                              "\n"
                                                              "Add connection: 1 - 5\n"
                                                              "Compute connected components\n"
                                                              "\t1 - root, rank: 2\n"
                                                              "\t2 - 1\n"
                                                              "\t3 - 1\n"
                                                              "\t4 - 1\n"
                                                              "\t5 - 1\n"
                                                              "\t6 - 5\n"
                                                              "\n";

    inline std::string computeConnectedComponentsResult = "Compute connected components\n"
                                                          "\t1 - root, rank: 0\n"
                                                          "\t2 - root, rank: 0\n"
                                                          "\t3 - root, rank: 0\n"
                                                          "\t4 - root, rank: 0\n"
                                                          "\t5 - root, rank: 0\n"
                                                          "\t6 - root, rank: 0\n"
                                                          "\t7 - root, rank: 0\n"
                                                          "\t8 - root, rank: 0\n"
                                                          "\t9 - root, rank: 0\n"
                                                          "\t10 - root, rank: 0\n"
                                                          "\n"
                                                          "Compute connected components\n"
                                                          "\t1 - root, rank: 2\n"
                                                          "\t2 - 1\n"
                                                          "\t3 - 1\n"
                                                          "\t4 - 3\n"
                                                          "\t5 - root, rank: 0\n"
                                                          "\t6 - root, rank: 1\n"
                                                          "\t7 - 6\n"
                                                          "\t8 - root, rank: 1\n"
                                                          "\t9 - 8\n"
                                                          "\t10 - 8\n"
                                                          "\n"
                                                          "Is empty: 0\n"
                                                          "\n"
                                                          "Connected components\n"
                                                          "\t1 2 3 4 \n"
                                                          "\t5 \n"
                                                          "\t6 7 \n"
                                                          "\t8 9 10 \n"
                                                          "\n"
                                                          "Is empty: 1\n"
                                                          "\n";

    inline std::string computeConnectedComponentsDiscontinuousResult = "Compute connected components\n"
                                                                       "\t1 - root, rank: 0\n"
                                                                       "\t2 - root, rank: 0\n"
                                                                       "\t3 - root, rank: 0\n"
                                                                       "\t4 - root, rank: 0\n"
                                                                       "\t5 - root, rank: 0\n"
                                                                       "\t6 - root, rank: 0\n"
                                                                       "\t7 - root, rank: 0\n"
                                                                       "\t8 - root, rank: 0\n"
                                                                       "\t9 - root, rank: 0\n"
                                                                       "\t10 - root, rank: 0\n"
                                                                       "\t11 - root, rank: 0\n"
                                                                       "\t12 - root, rank: 0\n"
                                                                       "\n"
                                                                       "Compute connected components\n"
                                                                       "\t1 - root, rank: 0\n"
                                                                       "\t2 - root, rank: 0\n"
                                                                       "\t3 - 4\n"
                                                                       "\t4 - root, rank: 1\n"
                                                                       "\t5 - root, rank: 0\n"
                                                                       "\t6 - root, rank: 0\n"
                                                                       "\t7 - root, rank: 0\n"
                                                                       "\t8 - 9\n"
                                                                       "\t9 - root, rank: 1\n"
                                                                       "\t10 - 9\n"
                                                                       "\t11 - root, rank: 0\n"
                                                                       "\t12 - root, rank: 0\n"
                                                                       "\n"
                                                                       "Is empty: 0\n"
                                                                       "\n"
                                                                       "Connected components\n"
                                                                       "\t2 \n"
                                                                       "\t3 4 \n"
                                                                       "\t6 \n"
                                                                       "\t8 9 10 \n"
                                                                       "\t12 \n"
                                                                       "\n"
                                                                       "Is empty: 1\n"
                                                                       "\n";
}   // namespace HydraTest::Container::ComputeConnectedComponents
