#pragma once

#include <string>

namespace HydraTest::SatSolver::MiniSat {
    inline std::string miniSatSolverConstructorResult = "Current formula: 1 0 -2 0 -1 3 0 1 -5 0 -2 6 0 2 -4 0 -7 -8 0 -7 8 0 7 -8 0 \n"
                                                        "\n"
                                                        "SAT solver\n"
                                                        "Type: MiniSat\n"
                                                        "Initially implied literals: 1 -2 3 -4\n"
                                                        "VSIDS score type: D4\n"
                                                        "Assumption:\n"
                                                        "Variable assumption:\n"
                                                        "\n"
                                                        "-------------------\n"
                                                        "----- MiniSat -----\n"
                                                        "-------------------\n"
                                                        "Number of variables: 8\n"
                                                        "Number of clauses: 3\n"
                                                        "Number of assigned literals: 4\n"
                                                        "Assumptions: \n"
                                                        "Current formula: -7 -8 0 -7 8 0 7 -8 0 00\n"
                                                        "\n"
                                                        "\n";

    inline std::string miniSatSolverSatisfiabilitySatisfiableFormulaResult = "Current formula: 1 0 -2 0 -1 3 0 1 -5 0 -2 6 0 2 -4 0 -7 -8 0 -7 8 0 7 -8 0 \n"
                                                                             "\n"
                                                                             "SAT solver\n"
                                                                             "Type: MiniSat\n"
                                                                             "Initially implied literals: 1 -2 3 -4\n"
                                                                             "VSIDS score type: D4\n"
                                                                             "Assumption:\n"
                                                                             "Variable assumption:\n"
                                                                             "\n"
                                                                             "-------------------\n"
                                                                             "----- MiniSat -----\n"
                                                                             "-------------------\n"
                                                                             "Number of variables: 8\n"
                                                                             "Number of clauses: 3\n"
                                                                             "Number of assigned literals: 4\n"
                                                                             "Assumptions: \n"
                                                                             "Current formula: -7 -8 0 -7 8 0 7 -8 0 00\n"
                                                                             "\n"
                                                                             "\n"
                                                                             "Is satisfiable: 1\n";

    inline std::string miniSatSolverSatisfiabilityUnsatisfiableFormulaResult = "Current formula: -1 -2 0 1 -2 0 1 2 0 -1 2 -3 0 -1 2 3 0 \n"
                                                                               "\n"
                                                                               "SAT solver\n"
                                                                               "Type: MiniSat\n"
                                                                               "Initially implied literals:\n"
                                                                               "VSIDS score type: D4\n"
                                                                               "Assumption:\n"
                                                                               "Variable assumption:\n"
                                                                               "\n"
                                                                               "-------------------\n"
                                                                               "----- MiniSat -----\n"
                                                                               "-------------------\n"
                                                                               "Number of variables: 3\n"
                                                                               "Number of clauses: 5\n"
                                                                               "Number of assigned literals: 0\n"
                                                                               "Assumptions: \n"
                                                                               "Current formula: -1 -2 0 1 -2 0 1 2 0 -1 2 -3 0 -1 2 3 0 00\n"
                                                                               "\n"
                                                                               "\n"
                                                                               "Is satisfiable: 0\n";

    inline std::string miniSatSolverSatisfiabilityAssumptionsResult = "Current formula: 1 0 -1 -3 0 1 2 0 -4 -5 0 4 5 0 6 -7 0 7 -8 0 \n"
                                                                      "\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "-------------------\n"
                                                                      "----- MiniSat -----\n"
                                                                      "-------------------\n"
                                                                      "Number of variables: 8\n"
                                                                      "Number of clauses: 4\n"
                                                                      "Number of assigned literals: 2\n"
                                                                      "Assumptions: \n"
                                                                      "Current formula: -4 -5 0 4 5 0 6 -7 0 7 -8 0 00\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption:\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: 1\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: 1\n"
                                                                      "Variable assumption: 1\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: 3\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: 3\n"
                                                                      "Variable assumption: 3\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 0\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: 1 -3\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: 1 -3\n"
                                                                      "Variable assumption: 1 3\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: 2\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: 2\n"
                                                                      "Variable assumption: 2\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: -2\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: -2\n"
                                                                      "Variable assumption: 2\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: -4 5\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: -4 5\n"
                                                                      "Variable assumption: 4 5\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption: -6 8\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption: -6 8\n"
                                                                      "Variable assumption: 6 8\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 0\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "--------------------------------------------------\n"
                                                                      "Assumption:\n"
                                                                      "--------------------------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "------------------------------\n"
                                                                      "Is satisfiable: 1\n"
                                                                      "------------------------------\n"
                                                                      "SAT solver\n"
                                                                      "Type: MiniSat\n"
                                                                      "Initially implied literals: 1 -3\n"
                                                                      "VSIDS score type: D4\n"
                                                                      "Assumption:\n"
                                                                      "Variable assumption:\n"
                                                                      "\n"
                                                                      "\n"
                                                                      "\n";

    inline std::string miniSatSolverUnitPropagationResult = "Current formula: 1 0 -3 0 -1 2 0 3 -4 0 5 7 0 -7 -9 0 -6 -7 8 0 \n"
                                                            "\n"
                                                            "SAT solver\n"
                                                            "Type: MiniSat\n"
                                                            "Initially implied literals: 1 2 -3 -4\n"
                                                            "VSIDS score type: D4\n"
                                                            "Assumption:\n"
                                                            "Variable assumption:\n"
                                                            "\n"
                                                            "-------------------\n"
                                                            "----- MiniSat -----\n"
                                                            "-------------------\n"
                                                            "Number of variables: 9\n"
                                                            "Number of clauses: 3\n"
                                                            "Number of assigned literals: 4\n"
                                                            "Assumptions: \n"
                                                            "Current formula: 5 7 0 -7 -9 0 -6 -7 8 0 00\n"
                                                            "\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption:\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption:\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -2\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Formula is not satisfiable\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -2\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Formula is not satisfiable\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -5\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 -5 7 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -5\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 7 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 6\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 6\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 6\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -5 6\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 -5 6 7 8 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: -5 6\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 7 8 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 -5\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 -5 7 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 -5\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 7 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 6\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 6\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 6\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals:\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 -5 6\n"
                                                            "Include assumptions: 1\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 1 2 -3 -4 -5 6 7 8 -9\n"
                                                            "\n"
                                                            "------------------------------\n"
                                                            "Assumption: 1 2 -3 -4 -5 6\n"
                                                            "Include assumptions: 0\n"
                                                            "------------------------------\n"
                                                            "Implied literals: 7 8 -9\n"
                                                            "\n";

    inline std::string miniSatSolverUnitPropagationRestrictionsResult = "Current formula: 1 0 -3 0 -1 2 0 3 -4 0 5 7 0 -7 -9 0 -6 -7 8 0 \n"
                                                                        "\n"
                                                                        "SAT solver\n"
                                                                        "Type: MiniSat\n"
                                                                        "Initially implied literals: 1 2 -3 -4\n"
                                                                        "VSIDS score type: D4\n"
                                                                        "Assumption:\n"
                                                                        "Variable assumption:\n"
                                                                        "\n"
                                                                        "-------------------\n"
                                                                        "----- MiniSat -----\n"
                                                                        "-------------------\n"
                                                                        "Number of variables: 9\n"
                                                                        "Number of clauses: 3\n"
                                                                        "Number of assigned literals: 4\n"
                                                                        "Assumptions: \n"
                                                                        "Current formula: 5 7 0 -7 -9 0 -6 -7 8 0 00\n"
                                                                        "\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables:\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4 -5 7 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4 7 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4 6\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4 -5 6 7 8 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4 7 8 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 1 2 3 4\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 1 2 -3 -4\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -5 7 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 7 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 6\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -5 6 7 8 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 5 6 7 8 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 7 8 -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 7\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 7\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 6\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 6 7 8\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 6 7 8\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: 7 8\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption:\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals:\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 1\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -9\n"
                                                                        "\n"
                                                                        "------------------------------\n"
                                                                        "Assumption: -5 6\n"
                                                                        "Include assumptions: 0\n"
                                                                        "Restricted variables: 9\n"
                                                                        "------------------------------\n"
                                                                        "Implied literals: -9\n"
                                                                        "\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureResult = "Current formula: -1 2 0 1 2 0 1 3 0 -2 -3 0 -4 -5 0 -4 -6 0 4 -5 0 5 6 0 -7 9 0 7 8 0 7 -9 0 8 -9 0 -10 11 0 -11 12 0 -13 -14 0 -13 -15 0 14 15 0 -16 -18 0 16 -17 0 -17 18 0 7 10 -13 0 -9 -11 -13 0 \n"
                                                                              "\n"
                                                                              "SAT solver\n"
                                                                              "Type: MiniSat\n"
                                                                              "Initially implied literals:\n"
                                                                              "VSIDS score type: D4\n"
                                                                              "Assumption:\n"
                                                                              "Variable assumption:\n"
                                                                              "\n"
                                                                              "-------------------\n"
                                                                              "----- MiniSat -----\n"
                                                                              "-------------------\n"
                                                                              "Number of variables: 18\n"
                                                                              "Number of clauses: 22\n"
                                                                              "Number of assigned literals: 0\n"
                                                                              "Assumptions: \n"
                                                                              "Current formula: -1 2 0 1 2 0 1 3 0 -2 -3 0 -4 -5 0 -4 -6 0 4 -5 0 5 6 0 -7 9 0 7 8 0 7 -9 0 8 -9 0 -10 11 0 -11 12 0 -13 -14 0 -13 -15 0 14 15 0 -16 -18 0 16 -17 0 -17 18 0 7 10 -13 0 -9 -11 -13 0 00\n"
                                                                              "\n"
                                                                              "\n"
                                                                              "Implicit implied literals: 1 2 -3 -4 -5 6 8 -13 -17\n"
                                                                              "7: 7 9\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureSelectedVariablesResult = "Current formula: -1 2 0 1 2 0 1 3 0 -2 -3 0 -4 -5 0 -4 -6 0 4 -5 0 5 6 0 -7 9 0 7 8 0 7 -9 0 8 -9 0 -10 11 0 -11 12 0 -13 -14 0 -13 -15 0 14 15 0 -16 -18 0 16 -17 0 -17 18 0 7 10 -13 0 -9 -11 -13 0 \n"
                                                                                               "\n"
                                                                                               "SAT solver\n"
                                                                                               "Type: MiniSat\n"
                                                                                               "Initially implied literals:\n"
                                                                                               "VSIDS score type: D4\n"
                                                                                               "Assumption:\n"
                                                                                               "Variable assumption:\n"
                                                                                               "\n"
                                                                                               "-------------------\n"
                                                                                               "----- MiniSat -----\n"
                                                                                               "-------------------\n"
                                                                                               "Number of variables: 18\n"
                                                                                               "Number of clauses: 22\n"
                                                                                               "Number of assigned literals: 0\n"
                                                                                               "Assumptions: \n"
                                                                                               "Current formula: -1 2 0 1 2 0 1 3 0 -2 -3 0 -4 -5 0 -4 -6 0 4 -5 0 5 6 0 -7 9 0 7 8 0 7 -9 0 8 -9 0 -10 11 0 -11 12 0 -13 -14 0 -13 -15 0 14 15 0 -16 -18 0 16 -17 0 -17 18 0 7 10 -13 0 -9 -11 -13 0 00\n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables:\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals:\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 1 2 3\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: 1 2 -3\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 4 5 6\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: -4 -5 6\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 7 8 9\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: 8\n"
                                                                                               "7: 7 9\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 10 11 12\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals:\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 7 8 9 10 11 12 13 14 15\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: 8 -13\n"
                                                                                               "7: 7 9\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 16 17 18\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: -17\n"
                                                                                               "------------------------------\n"
                                                                                               "Selected variables: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18\n"
                                                                                               "------------------------------\n"
                                                                                               "Implicit implied literals: 1 2 -3 -4 -5 6 8 -13 -17\n"
                                                                                               "7: 7 9\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureNoIgnoreResult = "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 \n"
                                                                                      "\n"
                                                                                      "SAT solver\n"
                                                                                      "Type: MiniSat\n"
                                                                                      "Initially implied literals:\n"
                                                                                      "VSIDS score type: D4\n"
                                                                                      "Assumption:\n"
                                                                                      "Variable assumption:\n"
                                                                                      "\n"
                                                                                      "-------------------\n"
                                                                                      "----- MiniSat -----\n"
                                                                                      "-------------------\n"
                                                                                      "Number of variables: 5\n"
                                                                                      "Number of clauses: 12\n"
                                                                                      "Number of assigned literals: 0\n"
                                                                                      "Assumptions: \n"
                                                                                      "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 00\n"
                                                                                      "\n"
                                                                                      "\n"
                                                                                      "Implicit implied literals: 2 -5\n"
                                                                                      "1: 1 4\n"
                                                                                      "3: 1 3 4\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureIgnoreResult = "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 \n"
                                                                                    "\n"
                                                                                    "SAT solver\n"
                                                                                    "Type: MiniSat\n"
                                                                                    "Initially implied literals:\n"
                                                                                    "VSIDS score type: D4\n"
                                                                                    "Assumption:\n"
                                                                                    "Variable assumption:\n"
                                                                                    "\n"
                                                                                    "-------------------\n"
                                                                                    "----- MiniSat -----\n"
                                                                                    "-------------------\n"
                                                                                    "Number of variables: 5\n"
                                                                                    "Number of clauses: 12\n"
                                                                                    "Number of assigned literals: 0\n"
                                                                                    "Assumptions: \n"
                                                                                    "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 00\n"
                                                                                    "\n"
                                                                                    "\n"
                                                                                    "Implicit implied literals: 2 -5\n"
                                                                                    "1: 1 4\n"
                                                                                    "3: 1 3\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureClauseReductionHeuristicAscendingResult = "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 \n"
                                                                                                               "\n"
                                                                                                               "SAT solver\n"
                                                                                                               "Type: MiniSat\n"
                                                                                                               "Initially implied literals:\n"
                                                                                                               "VSIDS score type: D4\n"
                                                                                                               "Assumption:\n"
                                                                                                               "Variable assumption:\n"
                                                                                                               "\n"
                                                                                                               "-------------------\n"
                                                                                                               "----- MiniSat -----\n"
                                                                                                               "-------------------\n"
                                                                                                               "Number of variables: 5\n"
                                                                                                               "Number of clauses: 12\n"
                                                                                                               "Number of assigned literals: 0\n"
                                                                                                               "Assumptions: \n"
                                                                                                               "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 00\n"
                                                                                                               "\n"
                                                                                                               "\n"
                                                                                                               "Implicit implied literals: 2 -5\n"
                                                                                                               "4: 1 3 4\n";

    inline std::string miniSatSolverEquivalencePreprocessingStructureClauseReductionHeuristicDescendingResult = "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 \n"
                                                                                                                "\n"
                                                                                                                "SAT solver\n"
                                                                                                                "Type: MiniSat\n"
                                                                                                                "Initially implied literals:\n"
                                                                                                                "VSIDS score type: D4\n"
                                                                                                                "Assumption:\n"
                                                                                                                "Variable assumption:\n"
                                                                                                                "\n"
                                                                                                                "-------------------\n"
                                                                                                                "----- MiniSat -----\n"
                                                                                                                "-------------------\n"
                                                                                                                "Number of variables: 5\n"
                                                                                                                "Number of clauses: 12\n"
                                                                                                                "Number of assigned literals: 0\n"
                                                                                                                "Assumptions: \n"
                                                                                                                "Current formula: -1 2 0 -1 -4 0 1 2 0 1 4 0 -3 -5 0 3 -5 0 -1 2 -4 0 1 2 -4 0 2 -3 5 0 2 3 5 0 -3 -4 5 0 3 4 5 0 00\n"
                                                                                                                "\n"
                                                                                                                "\n"
                                                                                                                "Implicit implied literals: 2 -5\n"
                                                                                                                "1: 1 4\n"
                                                                                                                "3: 1 3 4\n";
}   // namespace HydraTest::SatSolver::MiniSat
