#pragma once

#include <string>

namespace HydraTest::Statistics {
    inline std::string statisticsNumberCounterResult = "--------------------------------------------------\n"
                                                       "------------------number counter------------------\n"
                                                       "--------------------------------------------------\n"
                                                       "Number of calls: 0\n"
                                                       "Sum count: 0\n"
                                                       "Min count: 0\n"
                                                       "Max count: 0\n"
                                                       "Average count: 0.000000\n"
                                                       "\n"
                                                       "Add: 3\n"
                                                       "Counter: number counter\n"
                                                       "1\n"
                                                       "3\n"
                                                       "3\n"
                                                       "3\n"
                                                       "3.000000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 1\n"
                                                       "Counter: number counter\n"
                                                       "2\n"
                                                       "4\n"
                                                       "1\n"
                                                       "3\n"
                                                       "2.000000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 2\n"
                                                       "Counter: number counter\n"
                                                       "3\n"
                                                       "6\n"
                                                       "1\n"
                                                       "3\n"
                                                       "2.000000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 0\n"
                                                       "Counter: number counter\n"
                                                       "4\n"
                                                       "6\n"
                                                       "0\n"
                                                       "3\n"
                                                       "1.500000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 3\n"
                                                       "Counter: number counter\n"
                                                       "5\n"
                                                       "9\n"
                                                       "0\n"
                                                       "3\n"
                                                       "1.800000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 3\n"
                                                       "Counter: number counter\n"
                                                       "6\n"
                                                       "12\n"
                                                       "0\n"
                                                       "3\n"
                                                       "2.000000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 100\n"
                                                       "Counter: number counter\n"
                                                       "7\n"
                                                       "112\n"
                                                       "0\n"
                                                       "100\n"
                                                       "16.000000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "Add: 9999\n"
                                                       "Counter: number counter\n"
                                                       "8\n"
                                                       "10111\n"
                                                       "0\n"
                                                       "9999\n"
                                                       "1263.875000\n"
                                                       "--------------------\n"
                                                       "\n"
                                                       "--------------------------------------------------\n"
                                                       "------------------number counter------------------\n"
                                                       "--------------------------------------------------\n"
                                                       "Number of calls: 8\n"
                                                       "Sum count: 10111\n"
                                                       "Min count: 0\n"
                                                       "Max count: 9999\n"
                                                       "Average count: 1263.875000\n";

    inline std::string statisticsRealNumberCounterResult = "--------------------------------------------------\n"
                                                           "---------------real number counter----------------\n"
                                                           "--------------------------------------------------\n"
                                                           "Number of calls: 0\n"
                                                           "Sum count: 0.000000\n"
                                                           "Min count: 0.000000\n"
                                                           "Max count: 0.000000\n"
                                                           "Average count: 0.000000\n"
                                                           "\n"
                                                           "Add: 3.500000\n"
                                                           "Counter: real number counter\n"
                                                           "1\n"
                                                           "3.500000\n"
                                                           "3.500000\n"
                                                           "3.500000\n"
                                                           "3.500000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 1.000000\n"
                                                           "Counter: real number counter\n"
                                                           "2\n"
                                                           "4.500000\n"
                                                           "1.000000\n"
                                                           "3.500000\n"
                                                           "2.250000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 2.100000\n"
                                                           "Counter: real number counter\n"
                                                           "3\n"
                                                           "6.600000\n"
                                                           "1.000000\n"
                                                           "3.500000\n"
                                                           "2.200000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 0.000000\n"
                                                           "Counter: real number counter\n"
                                                           "4\n"
                                                           "6.600000\n"
                                                           "0.000000\n"
                                                           "3.500000\n"
                                                           "1.650000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 3.800000\n"
                                                           "Counter: real number counter\n"
                                                           "5\n"
                                                           "10.400000\n"
                                                           "0.000000\n"
                                                           "3.800000\n"
                                                           "2.080000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 3.700000\n"
                                                           "Counter: real number counter\n"
                                                           "6\n"
                                                           "14.100000\n"
                                                           "0.000000\n"
                                                           "3.800000\n"
                                                           "2.350000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 100.000000\n"
                                                           "Counter: real number counter\n"
                                                           "7\n"
                                                           "114.100000\n"
                                                           "0.000000\n"
                                                           "100.000000\n"
                                                           "16.300000\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "Add: 9999.000000\n"
                                                           "Counter: real number counter\n"
                                                           "8\n"
                                                           "10113.100000\n"
                                                           "0.000000\n"
                                                           "9999.000000\n"
                                                           "1264.137500\n"
                                                           "--------------------\n"
                                                           "\n"
                                                           "--------------------------------------------------\n"
                                                           "---------------real number counter----------------\n"
                                                           "--------------------------------------------------\n"
                                                           "Number of calls: 8\n"
                                                           "Sum count: 10113.100000\n"
                                                           "Min count: 0.000000\n"
                                                           "Max count: 9999.000000\n"
                                                           "Average count: 1264.137500\n";

    inline std::string statisticsNumberResult = "--------------------------------------------------\n"
                                                "----------------------number----------------------\n"
                                                "--------------------------------------------------\n"
                                                "Set: 0\n"
                                                "Number: 0\n"
                                                "\n"
                                                "Set: 3\n"
                                                "Number: number\n"
                                                "1\n"
                                                "3\n"
                                                "--------------------\n"
                                                "\n"
                                                "Set: 1\n"
                                                "The number statistic (number) has already been set!\n";

    inline std::string statisticsNumberResetResult = "--------------------------------------------------\n"
                                                     "----------------------number----------------------\n"
                                                     "--------------------------------------------------\n"
                                                     "Set: 0\n"
                                                     "Number: 0\n"
                                                     "\n"
                                                     "Set: 3\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "3\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 1\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "1\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 2\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "2\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 0\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "0\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 3\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "3\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 3\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "3\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 100\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "100\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "Set: 9999\n"
                                                     "Number: number\n"
                                                     "1\n"
                                                     "9999\n"
                                                     "--------------------\n"
                                                     "\n"
                                                     "--------------------------------------------------\n"
                                                     "----------------------number----------------------\n"
                                                     "--------------------------------------------------\n"
                                                     "Set: 1\n"
                                                     "Number: 9999\n";

    inline std::string statisticsNumberIncrementResult = "--------------------------------------------------\n"
                                                         "----------------------number----------------------\n"
                                                         "--------------------------------------------------\n"
                                                         "Set: 0\n"
                                                         "Number: 0\n"
                                                         "\n"
                                                         "Set: 3\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "4\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "5\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "6\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 1\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "1\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "2\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "4\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 2\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "2\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "4\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "5\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 0\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "0\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "1\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "2\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 3\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "4\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "5\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "6\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 3\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "3\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "4\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "5\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "6\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 100\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "100\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "101\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "102\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "103\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 9999\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "9999\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "10000\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "10001\n"
                                                         "\n"
                                                         "Increment\n"
                                                         "Number: number\n"
                                                         "1\n"
                                                         "10002\n"
                                                         "\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "--------------------------------------------------\n"
                                                         "----------------------number----------------------\n"
                                                         "--------------------------------------------------\n"
                                                         "Set: 1\n"
                                                         "Number: 10002\n";

    inline std::string statisticsNumberIncrementNumberResult = "--------------------------------------------------\n"
                                                               "----------------------number----------------------\n"
                                                               "--------------------------------------------------\n"
                                                               "Set: 0\n"
                                                               "Number: 0\n"
                                                               "\n"
                                                               "Increment: 3\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "3\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 1\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "4\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 2\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "6\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 0\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "6\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 3\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "9\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 3\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "12\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 100\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "112\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "Increment: 9999\n"
                                                               "Number: number\n"
                                                               "1\n"
                                                               "10111\n"
                                                               "--------------------\n"
                                                               "\n"
                                                               "--------------------------------------------------\n"
                                                               "----------------------number----------------------\n"
                                                               "--------------------------------------------------\n"
                                                               "Set: 1\n"
                                                               "Number: 10111\n";

    inline std::string statisticsRealNumberResult = "--------------------------------------------------\n"
                                                    "-------------------real number--------------------\n"
                                                    "--------------------------------------------------\n"
                                                    "Set: 0\n"
                                                    "Number: 0.000000\n"
                                                    "\n"
                                                    "Set: 3.500000\n"
                                                    "Number: real number\n"
                                                    "1\n"
                                                    "3.500000\n"
                                                    "--------------------\n"
                                                    "\n"
                                                    "Set: 1.000000\n"
                                                    "The number statistic (real number) has already been set!\n";

    inline std::string statisticsRealNumberResetResult = "--------------------------------------------------\n"
                                                         "-------------------real number--------------------\n"
                                                         "--------------------------------------------------\n"
                                                         "Set: 0\n"
                                                         "Number: 0.000000\n"
                                                         "\n"
                                                         "Set: 3.500000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "3.500000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 1.000000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "1.000000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 2.100000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "2.100000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 0.000000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "0.000000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 3.800000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "3.800000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 3.700000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "3.700000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 100.000000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "100.000000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "Set: 9999.000000\n"
                                                         "Number: real number\n"
                                                         "1\n"
                                                         "9999.000000\n"
                                                         "--------------------\n"
                                                         "\n"
                                                         "--------------------------------------------------\n"
                                                         "-------------------real number--------------------\n"
                                                         "--------------------------------------------------\n"
                                                         "Set: 1\n"
                                                         "Number: 9999.000000\n";

    inline std::string statisticsTimerSecondsResult = "--------------------------------------------------\n"
                                                      "-----------------timer - seconds------------------\n"
                                                      "--------------------------------------------------\n"
                                                      "Number of calls: 0\n"
                                                      "Sum time: 0 s\n"
                                                      "Min time: 0 s\n"
                                                      "Max time: 0 s\n"
                                                      "Average time: 0.000000 s\n"
                                                      "\n"
                                                      "Timer: timer - seconds [s]\n"
                                                      "0\n"
                                                      "0\n"
                                                      "0\n"
                                                      "0\n"
                                                      "0.000000\n";

    inline std::string statisticsTimerMillisecondsResult = "--------------------------------------------------\n"
                                                           "---------------timer - milliseconds---------------\n"
                                                           "--------------------------------------------------\n"
                                                           "Number of calls: 0\n"
                                                           "Sum time: 0 ms\n"
                                                           "Min time: 0 ms\n"
                                                           "Max time: 0 ms\n"
                                                           "Average time: 0.000000 ms\n"
                                                           "\n"
                                                           "Timer: timer - milliseconds [ms]\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0.000000\n";

    inline std::string statisticsTimerMicrosecondsResult = "--------------------------------------------------\n"
                                                           "---------------timer - microseconds---------------\n"
                                                           "--------------------------------------------------\n"
                                                           "Number of calls: 0\n"
                                                           "Sum time: 0 us\n"
                                                           "Min time: 0 us\n"
                                                           "Max time: 0 us\n"
                                                           "Average time: 0.000000 us\n"
                                                           "\n"
                                                           "Timer: timer - microseconds [us]\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0\n"
                                                           "0.000000\n";

    inline std::string statisticsTimerNanosecondsResult = "--------------------------------------------------\n"
                                                          "---------------timer - nanoseconds----------------\n"
                                                          "--------------------------------------------------\n"
                                                          "Number of calls: 0\n"
                                                          "Sum time: 0 ns\n"
                                                          "Min time: 0 ns\n"
                                                          "Max time: 0 ns\n"
                                                          "Average time: 0.000000 ns\n"
                                                          "\n"
                                                          "Timer: timer - nanoseconds [ns]\n"
                                                          "0\n"
                                                          "0\n"
                                                          "0\n"
                                                          "0\n"
                                                          "0.000000\n";
}   // namespace HydraTest::Statistics
