#pragma once

#include <string>

namespace HydraTest::Container::VariableStateVector {
    inline std::string variableStateVectorConstructorResult = "Number of variables: 1\n"
                                                              "Variable state vector: _\n"
                                                              "\n"
                                                              "Number of variables: 2\n"
                                                              "Variable state vector: _ _\n"
                                                              "\n"
                                                              "Number of variables: 3\n"
                                                              "Variable state vector: _ _ _\n"
                                                              "\n"
                                                              "Number of variables: 4\n"
                                                              "Variable state vector: _ _ _ _\n"
                                                              "\n"
                                                              "Number of variables: 5\n"
                                                              "Variable state vector: _ _ _ _ _\n"
                                                              "\n";

    inline std::string variableStateVectorConstructorAssignedAllVariablesResult = "Number of variables: 1\n"
                                                                                  "Variable state vector: 1\n"
                                                                                  "\n"
                                                                                  "Number of variables: 2\n"
                                                                                  "Variable state vector: 1 -2\n"
                                                                                  "\n"
                                                                                  "Number of variables: 3\n"
                                                                                  "Variable state vector: 1 -2 3\n"
                                                                                  "\n"
                                                                                  "Number of variables: 4\n"
                                                                                  "Variable state vector: 1 -2 3 -4\n"
                                                                                  "\n"
                                                                                  "Number of variables: 5\n"
                                                                                  "Variable state vector: 1 -2 3 -4 5\n"
                                                                                  "\n";

    inline std::string variableStateVectorIsAssignedOddResult = "Number of variables: 6\n"
                                                                "Variable state vector: 1 _ -3 _ 5 _\n"
                                                                "\n"
                                                                "1: 1\n"
                                                                "2: 0\n"
                                                                "3: 1\n"
                                                                "4: 0\n"
                                                                "5: 1\n"
                                                                "6: 0\n";

    inline std::string variableStateVectorIsAssignedEvenResult = "Number of variables: 6\n"
                                                                 "Variable state vector: _ 2 _ -4 _ 6\n"
                                                                 "\n"
                                                                 "1: 0\n"
                                                                 "2: 1\n"
                                                                 "3: 0\n"
                                                                 "4: 1\n"
                                                                 "5: 0\n"
                                                                 "6: 1\n";

    inline std::string variableStateVectorUnassignResult = "Number of variables: 6\n"
                                                           "Variable state vector: 1 _ -3 _ 5 _\n"
                                                           "\n"
                                                           "Unassign: 1\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ -3 _ 5 _\n"
                                                           "\n"
                                                           "Unassign: 2\n"
                                                           "Attempt to unassign the variable (2) that has not been assigned!\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ -3 _ 5 _\n"
                                                           "\n"
                                                           "Unassign: 3\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ _ _ 5 _\n"
                                                           "\n"
                                                           "Unassign: 4\n"
                                                           "Attempt to unassign the variable (4) that has not been assigned!\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ _ _ 5 _\n"
                                                           "\n"
                                                           "Unassign: 5\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ _ _ _ _\n"
                                                           "\n"
                                                           "Unassign: 6\n"
                                                           "Attempt to unassign the variable (6) that has not been assigned!\n"
                                                           "Number of variables: 6\n"
                                                           "Variable state vector: _ _ _ _ _ _\n"
                                                           "\n";

    inline std::string variableStateVectorAssignResult = "Number of variables: 6\n"
                                                         "Variable state vector: _ 2 _ -4 _ 6\n"
                                                         "\n"
                                                         "Assign: -1\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 _ -4 _ 6\n"
                                                         "\n"
                                                         "Assign: 2\n"
                                                         "Attempt to reassign the variable (2)!\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 _ -4 _ 6\n"
                                                         "\n"
                                                         "Assign: -3\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 -3 -4 _ 6\n"
                                                         "\n"
                                                         "Assign: 4\n"
                                                         "Attempt to reassign the variable (4)!\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 -3 -4 _ 6\n"
                                                         "\n"
                                                         "Assign: -5\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 -3 -4 -5 6\n"
                                                         "\n"
                                                         "Assign: 6\n"
                                                         "Attempt to reassign the variable (6)!\n"
                                                         "Number of variables: 6\n"
                                                         "Variable state vector: -1 2 -3 -4 -5 6\n"
                                                         "\n";

    inline std::string variableStateVectorGetSignResult = "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 1\n"
                                                          "Sign: 1\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 2\n"
                                                          "The variable (2) is not assigned!\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 3\n"
                                                          "Sign: 0\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 4\n"
                                                          "The variable (4) is not assigned!\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 5\n"
                                                          "Sign: 1\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 6\n"
                                                          "The variable (6) is not assigned!\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n"
                                                          "Var: 7\n"
                                                          "Sign: 0\n"
                                                          "Number of variables: 7\n"
                                                          "Variable state vector: 1 _ -3 _ 5 _ -7\n"
                                                          "\n";

    inline std::string variableStateVectorIsLiteralSatisfiedResult = "Number of variables: 7\n"
                                                                     "Variable state vector: _ 2 _ -4 _ 6 _\n"
                                                                     "\n"
                                                                     "Literal: 1\n"
                                                                     "The variable (1) is not assigned!\n"
                                                                     "Literal: -1\n"
                                                                     "The variable (1) is not assigned!\n"
                                                                     "\n"
                                                                     "Literal: 2\n"
                                                                     "Is satisfied: 1\n"
                                                                     "Literal: -2\n"
                                                                     "Is satisfied: 0\n"
                                                                     "\n"
                                                                     "Literal: 3\n"
                                                                     "The variable (3) is not assigned!\n"
                                                                     "Literal: -3\n"
                                                                     "The variable (3) is not assigned!\n"
                                                                     "\n"
                                                                     "Literal: 4\n"
                                                                     "Is satisfied: 0\n"
                                                                     "Literal: -4\n"
                                                                     "Is satisfied: 1\n"
                                                                     "\n"
                                                                     "Literal: 5\n"
                                                                     "The variable (5) is not assigned!\n"
                                                                     "Literal: -5\n"
                                                                     "The variable (5) is not assigned!\n"
                                                                     "\n"
                                                                     "Literal: 6\n"
                                                                     "Is satisfied: 1\n"
                                                                     "Literal: -6\n"
                                                                     "Is satisfied: 0\n"
                                                                     "\n"
                                                                     "Literal: 7\n"
                                                                     "The variable (7) is not assigned!\n"
                                                                     "Literal: -7\n"
                                                                     "The variable (7) is not assigned!\n"
                                                                     "\n";

    inline std::string variableStateVectorAreAllVariablesUnAssignedResult = "Are all variables assigned: 0\n"
                                                                            "Are all variables unassigned: 1\n"
                                                                            "Number of variables: 8\n"
                                                                            "Variable state vector: _ _ _ _ _ _ _ _\n"
                                                                            "\n"
                                                                            "Are all variables assigned: 0\n"
                                                                            "Are all variables unassigned: 0\n"
                                                                            "Number of variables: 8\n"
                                                                            "Variable state vector: _ 2 _ -4 _ 6 _ -8\n"
                                                                            "\n"
                                                                            "Are all variables assigned: 1\n"
                                                                            "Are all variables unassigned: 0\n"
                                                                            "Number of variables: 8\n"
                                                                            "Variable state vector: 1 2 -3 -4 5 6 -7 -8\n"
                                                                            "\n"
                                                                            "Are all variables assigned: 0\n"
                                                                            "Are all variables unassigned: 1\n"
                                                                            "Number of variables: 8\n"
                                                                            "Variable state vector: _ _ _ _ _ _ _ _\n"
                                                                            "\n";

    inline std::string variableStateVectorClearResult = "Number of variables: 10\n"
                                                        "Variable state vector: 1 _ -3 _ 5 _ -7 _ 9 _\n"
                                                        "\n"
                                                        "Clear\n"
                                                        "Number of variables: 10\n"
                                                        "Variable state vector: _ _ _ _ _ _ _ _ _ _\n"
                                                        "\n"
                                                        "Number of variables: 10\n"
                                                        "Variable state vector: _ 2 _ -4 _ 6 _ -8 _ 10\n"
                                                        "\n"
                                                        "Clear\n"
                                                        "Number of variables: 10\n"
                                                        "Variable state vector: _ _ _ _ _ _ _ _ _ _\n"
                                                        "\n";
}   // namespace HydraTest::Container::VariableStateVector
