#pragma once

#include <string>

namespace HydraTest::DecisionHeuristic::Vsads {
    inline std::string vsadsDecisionHeuristicResult = "Decision heuristic\n"
                                                      "Type: variable state aware decaying sum (VSADS)\n"
                                                      "Ignore pure literal type: pure literals are not ignored\n"
                                                      "p: 1.000000\n"
                                                      "q: 0.500000\n"
                                                      "\n"
                                                      "\n"
                                                      "--------------------\n"
                                                      "------ before ------\n"
                                                      "--------------------\n"
                                                      "Selected variables: 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42\n"
                                                      "Decision variable: 1\n"
                                                      "\n"
                                                      "-------------------\n"
                                                      "------ after ------\n"
                                                      "-------------------\n"
                                                      "Decision variable: correct\n";

    inline std::string vsadsDecisionHeuristicSelectedVariablesResult = "Decision heuristic\n"
                                                                       "Type: variable state aware decaying sum (VSADS)\n"
                                                                       "Ignore pure literal type: pure literals are not ignored\n"
                                                                       "p: 1.000000\n"
                                                                       "q: 0.500000\n"
                                                                       "\n"
                                                                       "\n"
                                                                       "--------------------\n"
                                                                       "------ before ------\n"
                                                                       "--------------------\n"
                                                                       "Selected variables: 1 2 3 4 5 6\n"
                                                                       "Decision variable: 1\n"
                                                                       "\n"
                                                                       "Selected variables: 1 7 13 19 25 31 37\n"
                                                                       "Decision variable: 1\n"
                                                                       "\n"
                                                                       "Selected variables: 7 8 9\n"
                                                                       "Decision variable: 7\n"
                                                                       "\n"
                                                                       "Selected variables: 13\n"
                                                                       "Decision variable: 13\n"
                                                                       "\n"
                                                                       "-------------------\n"
                                                                       "------ after ------\n"
                                                                       "-------------------\n"
                                                                       "Selected variables: 1 2 3 4 5 6\n"
                                                                       "Decision variable: correct\n"
                                                                       "\n"
                                                                       "Selected variables: 1 7 13 19 25 31 37\n"
                                                                       "Decision variable: correct\n"
                                                                       "\n"
                                                                       "Selected variables: 7 8 9\n"
                                                                       "Decision variable: correct\n"
                                                                       "\n"
                                                                       "Selected variables: 13\n"
                                                                       "Decision variable: correct\n"
                                                                       "\n";
}   // namespace HydraTest::DecisionHeuristic::Vsads
