#pragma once

#include <string>

namespace HydraTest::Container::FixedVector {
    inline std::string fixedVectorConstructorResult = "Empty constructor\n"
                                                      "Vector: \n"
                                                      "Fixed vector: \n"
                                                      "Number of active elements: 0\n"
                                                      "Number of all elements: 0\n"
                                                      "\n"
                                                      "Copy constructor\n"
                                                      "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 2 3 4 5 \n"
                                                      "Number of active elements: 5\n"
                                                      "Number of all elements: 5\n"
                                                      "\n"
                                                      "Move constructor\n"
                                                      "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 2 3 4 5 \n"
                                                      "Number of active elements: 5\n"
                                                      "Number of all elements: 5\n"
                                                      "\n";

    inline std::string fixedVectorConstructorRangeResult = "FirstValue: 0, lastValue: 1\n"
                                                           "Vector: 0 \n"
                                                           "Fixed vector: 0 \n"
                                                           "Number of active elements: 1\n"
                                                           "Number of all elements: 1\n"
                                                           "\n"
                                                           "FirstValue: 1, lastValue: 2\n"
                                                           "Vector: 1 \n"
                                                           "Fixed vector: 1 \n"
                                                           "Number of active elements: 1\n"
                                                           "Number of all elements: 1\n"
                                                           "\n"
                                                           "FirstValue: 3, lastValue: 4\n"
                                                           "Vector: 3 \n"
                                                           "Fixed vector: 3 \n"
                                                           "Number of active elements: 1\n"
                                                           "Number of all elements: 1\n"
                                                           "\n"
                                                           "FirstValue: 1, lastValue: 5\n"
                                                           "Vector: 1 2 3 4 \n"
                                                           "Fixed vector: 1 2 3 4 \n"
                                                           "Number of active elements: 4\n"
                                                           "Number of all elements: 4\n"
                                                           "\n"
                                                           "FirstValue: 3, lastValue: 8\n"
                                                           "Vector: 3 4 5 6 7 \n"
                                                           "Fixed vector: 3 4 5 6 7 \n"
                                                           "Number of active elements: 5\n"
                                                           "Number of all elements: 5\n"
                                                           "\n"
                                                           "FirstValue: 10, lastValue: 12\n"
                                                           "Vector: 10 11 \n"
                                                           "Fixed vector: 10 11 \n"
                                                           "Number of active elements: 2\n"
                                                           "Number of all elements: 2\n"
                                                           "\n";

    inline std::string fixedVectorCopyAndMoveResult = "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 2 3 4 5 \n"
                                                      "Number of active elements: 5\n"
                                                      "Number of all elements: 5\n"
                                                      "\n"
                                                      "Copy method\n"
                                                      "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 2 3 4 5 \n"
                                                      "Number of active elements: 5\n"
                                                      "Number of all elements: 5\n"
                                                      "\n"
                                                      "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 \n"
                                                      "Number of active elements: 1\n"
                                                      "Number of all elements: 5\n"
                                                      "\n"
                                                      "Move method\n"
                                                      "Vector: 1 2 3 4 5 \n"
                                                      "Fixed vector: 1 2 3 4 5 \n"
                                                      "Number of active elements: 5\n"
                                                      "Number of all elements: 5\n"
                                                      "\n";

    inline std::string fixedVectorChangeResult = "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 2 3 4 5 \n"
                                                 "Number of active elements: 5\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 0\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: \n"
                                                 "Number of active elements: 0\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 1\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 \n"
                                                 "Number of active elements: 1\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 2\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 2 \n"
                                                 "Number of active elements: 2\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 3\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 2 3 \n"
                                                 "Number of active elements: 3\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 4\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 2 3 4 \n"
                                                 "Number of active elements: 4\n"
                                                 "Number of all elements: 5\n"
                                                 "\n"
                                                 "Change: 5\n"
                                                 "Vector: 1 2 3 4 5 \n"
                                                 "Fixed vector: 1 2 3 4 5 \n"
                                                 "Number of active elements: 5\n"
                                                 "Number of all elements: 5\n"
                                                 "\n";

    inline std::string fixedVectorSwapResult = "Vector: 1 2 3 4 5 6 \n"
                                               "Fixed vector: 1 2 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 0<->0\n"
                                               "Vector: 1 2 3 4 5 6 \n"
                                               "Fixed vector: 1 2 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 0<->1\n"
                                               "Vector: 2 1 3 4 5 6 \n"
                                               "Fixed vector: 2 1 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 1<->0\n"
                                               "Vector: 1 2 3 4 5 6 \n"
                                               "Fixed vector: 1 2 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 1<->3\n"
                                               "Vector: 1 4 3 2 5 6 \n"
                                               "Fixed vector: 1 4 3 2 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 3<->1\n"
                                               "Vector: 1 2 3 4 5 6 \n"
                                               "Fixed vector: 1 2 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n"
                                               "Swap: 3<->4\n"
                                               "Attempt to swap two elements (3 and 4) in the fixed vector containing 4 active element(s)!\n"
                                               "Swap: 4<->3\n"
                                               "Attempt to swap two elements (4 and 3) in the fixed vector containing 4 active element(s)!\n"
                                               "Swap: 4<->4\n"
                                               "Attempt to swap two elements (4 and 4) in the fixed vector containing 4 active element(s)!\n"
                                               "Swap: 4<->5\n"
                                               "Attempt to swap two elements (4 and 5) in the fixed vector containing 4 active element(s)!\n"
                                               "\n"
                                               "Vector: 1 2 3 4 5 6 \n"
                                               "Fixed vector: 1 2 3 4 \n"
                                               "Number of active elements: 4\n"
                                               "Number of all elements: 6\n"
                                               "\n";

    inline std::string fixedVectorSwapElementResult = "Vector: 1 2 3 4 5 6 \n"
                                                      "Fixed vector: 1 2 3 4 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 1\n"
                                                      "Vector: 4 2 3 1 5 6 \n"
                                                      "Fixed vector: 4 2 3 1 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 3\n"
                                                      "Vector: 4 2 1 3 5 6 \n"
                                                      "Fixed vector: 4 2 1 3 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 5\n"
                                                      "The element (5) does not exist in the fixed vector!\n"
                                                      "\n"
                                                      "Element: 7\n"
                                                      "The element (7) does not exist in the fixed vector!\n"
                                                      "\n"
                                                      "Element: 2\n"
                                                      "Vector: 4 3 1 2 5 6 \n"
                                                      "Fixed vector: 4 3 1 2 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 2\n"
                                                      "Vector: 4 3 1 2 5 6 \n"
                                                      "Fixed vector: 4 3 1 2 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 4\n"
                                                      "Vector: 2 3 1 4 5 6 \n"
                                                      "Fixed vector: 2 3 1 4 \n"
                                                      "Number of active elements: 4\n"
                                                      "Number of all elements: 6\n"
                                                      "\n"
                                                      "Element: 6\n"
                                                      "The element (6) does not exist in the fixed vector!\n"
                                                      "\n"
                                                      "Element: 8\n"
                                                      "The element (8) does not exist in the fixed vector!\n"
                                                      "\n";

    inline std::string fixedVectorSwapElementsResult = "Vector: 1 2 3 4 5 6 \n"
                                                       "Fixed vector: 1 2 3 4 5 6 \n"
                                                       "Number of active elements: 6\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements:\n"
                                                       "Vector: 1 2 3 4 5 6 \n"
                                                       "Fixed vector: 1 2 3 4 5 6 \n"
                                                       "Number of active elements: 6\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 1\n"
                                                       "Vector: 6 2 3 4 5 1 \n"
                                                       "Fixed vector: 6 2 3 4 5 \n"
                                                       "Number of active elements: 5\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 3\n"
                                                       "Vector: 6 2 1 4 5 3 \n"
                                                       "Fixed vector: 6 2 1 4 5 \n"
                                                       "Number of active elements: 5\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 3\n"
                                                       "Vector: 6 2 1 4 5 3 \n"
                                                       "Fixed vector: 6 2 1 4 5 \n"
                                                       "Number of active elements: 5\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 2 1\n"
                                                       "Vector: 6 3 5 4 1 2 \n"
                                                       "Fixed vector: 6 3 5 4 \n"
                                                       "Number of active elements: 4\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 4 5\n"
                                                       "Vector: 6 3 2 1 4 5 \n"
                                                       "Fixed vector: 6 3 2 1 \n"
                                                       "Number of active elements: 4\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 4 5\n"
                                                       "Vector: 6 3 2 1 5 4 \n"
                                                       "Fixed vector: 6 3 2 1 \n"
                                                       "Number of active elements: 4\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       "Elements: 6 2 4\n"
                                                       "Vector: 5 3 1 2 4 6 \n"
                                                       "Fixed vector: 5 3 1 \n"
                                                       "Number of active elements: 3\n"
                                                       "Number of all elements: 6\n"
                                                       "\n"
                                                       /*
                                                       "Elements: 3 7\n"
                                                       "The elements (7) do not exist in the fixed vector!\n"
                                                       "\n"
                                                       "Elements: 7 8\n"
                                                       "The elements (7, 8) do not exist in the fixed vector!\n"
                                                       "\n"
                                                        */
                                                       "Elements: 1 2 3 4 5 6\n"
                                                       "Vector: 3 1 2 4 6 5 \n"
                                                       "Fixed vector: \n"
                                                       "Number of active elements: 0\n"
                                                       "Number of all elements: 6\n"
                                                       "\n";
}   // namespace HydraTest::Container::FixedVector
