#pragma once

#include <string>

namespace HydraTest::Formula::StructuralRestrictedRepresentation {
    inline std::string structuralRestrictedFormulaRepresentationKromCNoneResult = "Formula: -1 4 0 1 2 0 2 -3 0 -3 -4 0 \n"
                                                                                  "\n"
                                                                                  "Structural restricted formula representation\n"
                                                                                  "Type: Krom-C\n"
                                                                                  "Formula size: 8\n"
                                                                                  "Number of clauses: 4\n"
                                                                                  "Variables: 1 2 3 4\n"
                                                                                  "Formula: -1 4 0 1 2 0 2 -3 0 -3 -4 0\n"
                                                                                  "Clause offsets: 0 3 6 9\n"
                                                                                  "\n";

    inline std::string structuralRestrictedFormulaRepresentationKromCNoDuplicateResult = "Formula: -2 -6 0 -2 -6 0 2 4 0 2 4 0 4 -6 0 4 -6 0 4 -6 0 \n"
                                                                                         "\n"
                                                                                         "Structural restricted formula representation\n"
                                                                                         "Type: Krom-C\n"
                                                                                         "Formula size: 6\n"
                                                                                         "Number of clauses: 3\n"
                                                                                         "Variables: 2 4 6\n"
                                                                                         "Formula: -2 -6 0 2 4 0 4 -6 0\n"
                                                                                         "Clause offsets: 0 3 6\n"
                                                                                         "\n";

    inline std::string structuralRestrictedFormulaRepresentationKromCNoSubsumedResult = "Formula: 1 0 -4 0 -1 6 0 4 -6 0 -1 2 -4 0 1 6 -7 0 1 2 -4 -6 -7 0 \n"
                                                                                        "\n"
                                                                                        "Structural restricted formula representation\n"
                                                                                        "Type: Krom-C\n"
                                                                                        "Formula size: 6\n"
                                                                                        "Number of clauses: 4\n"
                                                                                        "Variables: 1 4 6\n"
                                                                                        "Formula: 1 0 -4 0 -1 6 0 4 -6 0\n"
                                                                                        "Clause offsets: 0 2 4 7\n"
                                                                                        "\n";

    inline std::string structuralRestrictedFormulaRepresentationHornCNoneResult = "Formula: -1 -2 0 -3 4 0 -1 3 -4 0 1 -2 -3 -4 0 \n"
                                                                                  "\n"
                                                                                  "Structural restricted formula representation\n"
                                                                                  "Type: Horn-C\n"
                                                                                  "Formula size: 11\n"
                                                                                  "Number of clauses: 4\n"
                                                                                  "Variables: 1 2 3 4\n"
                                                                                  "Formula: -1 -2 0 -3 4 0 -1 3 -4 0 1 -2 -3 -4 0\n"
                                                                                  "Clause offsets: 0 3 6 10\n"
                                                                                  "\n";

    inline std::string structuralRestrictedFormulaRepresentationHornCNoDuplicateResult = "Formula: 2 -4 0 2 -4 0 2 -6 0 2 -6 0 -2 -4 -6 0 -2 -4 -6 0 \n"
                                                                                         "\n"
                                                                                         "Structural restricted formula representation\n"
                                                                                         "Type: Horn-C\n"
                                                                                         "Formula size: 7\n"
                                                                                         "Number of clauses: 3\n"
                                                                                         "Variables: 2 4 6\n"
                                                                                         "Formula: 2 -4 0 2 -6 0 -2 -4 -6 0\n"
                                                                                         "Clause offsets: 0 3 6\n"
                                                                                         "\n";

    inline std::string structuralRestrictedFormulaRepresentationHornCNoSubsumedResult = "Formula: 1 -2 0 1 -4 0 1 -4 0 4 -7 0 -6 -7 0 -6 -7 0 1 -2 6 7 0 1 2 -6 -7 0 -1 -2 -4 -6 7 0 1 -2 4 -6 -7 0 \n"
                                                                                        "\n"
                                                                                        "Structural restricted formula representation\n"
                                                                                        "Type: Horn-C\n"
                                                                                        "Formula size: 13\n"
                                                                                        "Number of clauses: 5\n"
                                                                                        "Variables: 1 2 4 6 7\n"
                                                                                        "Formula: 1 -2 0 1 -4 0 4 -7 0 -6 -7 0 -1 -2 -4 -6 7 0\n"
                                                                                        "Clause offsets: 0 3 6 9 12\n"
                                                                                        "\n";

    inline std::string structuralRestrictedFormulaRepresentationAntiHornCNoneResult = "Formula: 1 2 0 3 -4 0 1 -3 4 0 -1 2 3 4 0 \n"
                                                                                      "\n"
                                                                                      "Structural restricted formula representation\n"
                                                                                      "Type: anti-Horn-C\n"
                                                                                      "Formula size: 11\n"
                                                                                      "Number of clauses: 4\n"
                                                                                      "Variables: 1 2 3 4\n"
                                                                                      "Formula: 1 2 0 3 -4 0 1 -3 4 0 -1 2 3 4 0\n"
                                                                                      "Clause offsets: 0 3 6 10\n"
                                                                                      "\n";

    inline std::string structuralRestrictedFormulaRepresentationAntiHornCNoDuplicateResult = "Formula: -2 4 0 -2 4 0 -2 4 0 -2 6 0 -2 6 0 2 4 6 0 2 4 6 0 \n"
                                                                                             "\n"
                                                                                             "Structural restricted formula representation\n"
                                                                                             "Type: anti-Horn-C\n"
                                                                                             "Formula size: 7\n"
                                                                                             "Number of clauses: 3\n"
                                                                                             "Variables: 2 4 6\n"
                                                                                             "Formula: -2 4 0 -2 6 0 2 4 6 0\n"
                                                                                             "Clause offsets: 0 3 6\n"
                                                                                             "\n";

    inline std::string structuralRestrictedFormulaRepresentationAntiHornCNoSubsumedResult = "Formula: 2 4 0 2 4 0 2 7 0 -4 7 0 -1 2 7 0 -1 2 7 0 2 6 7 0 \n"
                                                                                            "\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: anti-Horn-C\n"
                                                                                            "Formula size: 6\n"
                                                                                            "Number of clauses: 3\n"
                                                                                            "Variables: 2 4 7\n"
                                                                                            "Formula: 2 4 0 2 7 0 -4 7 0\n"
                                                                                            "Clause offsets: 0 3 6\n"
                                                                                            "\n";

    inline std::string structuralRestrictedFormulaRepresentationRenHCNoneResult = "Formula: -1 4 0 1 2 0 -2 3 0 -3 -4 0 1 -3 -4 0 \n"
                                                                                  "\n"
                                                                                  "Structural restricted formula representation\n"
                                                                                  "Type: renH-C\n"
                                                                                  "Formula size: 11\n"
                                                                                  "Number of clauses: 5\n"
                                                                                  "Variables: 1 2 3 4\n"
                                                                                  "Switched variables: 1 4\n"
                                                                                  "Formula: -1 4 0 1 2 0 -2 3 0 -3 -4 0 1 -3 -4 0\n"
                                                                                  "Clause offsets: 0 3 6 9 12\n"
                                                                                  "\n";

    inline std::string structuralRestrictedFormulaRepresentationRenHCNoDuplicateResult = "Formula: -2 -4 -6 0 -2 -4 -6 0 -2 -4 6 0 -2 -4 6 0 -2 4 -6 0 -2 4 -6 0 2 -4 -6 0 2 -4 -6 0 \n"
                                                                                         "\n"
                                                                                         "Structural restricted formula representation\n"
                                                                                         "Type: renH-C\n"
                                                                                         "Formula size: 12\n"
                                                                                         "Number of clauses: 4\n"
                                                                                         "Variables: 2 4 6\n"
                                                                                         "Switched variables:\n"
                                                                                         "Formula: -2 -4 -6 0 -2 -4 6 0 -2 4 -6 0 2 -4 -6 0\n"
                                                                                         "Clause offsets: 0 4 8 12\n"
                                                                                         "\n";

    inline std::string structuralRestrictedFormulaRepresentationRenHCNoSubsumedResult = "Formula: -1 2 0 1 4 0 1 4 0 2 4 0 2 4 0 -1 2 6 0 -1 2 7 0 -1 2 -6 -7 0 \n"
                                                                                        "\n"
                                                                                        "Structural restricted formula representation\n"
                                                                                        "Type: renH-C\n"
                                                                                        "Formula size: 6\n"
                                                                                        "Number of clauses: 3\n"
                                                                                        "Variables: 1 2 4\n"
                                                                                        "Switched variables: 1 2 4\n"
                                                                                        "Formula: -1 2 0 1 4 0 2 4 0\n"
                                                                                        "Clause offsets: 0 3 6\n"
                                                                                        "\n";

    inline std::string structuralRestrictedFormulaRepresentationKromCPartialAssignmentResult = "Formula: 1 -2 -3 0 1 2 3 0 -1 2 -3 4 0 \n"
                                                                                               "\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Assign literal: -1\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Formula: -2 -3 0 2 3 0 \n"
                                                                                               "\n"
                                                                                               "Structural restricted formula representation\n"
                                                                                               "Type: Krom-C\n"
                                                                                               "Formula size: 4\n"
                                                                                               "Number of clauses: 2\n"
                                                                                               "Variables: 2 3\n"
                                                                                               "Formula: -2 -3 0 2 3 0\n"
                                                                                               "Clause offsets: 0 3\n"
                                                                                               "\n";

    inline std::string structuralRestrictedFormulaRepresentationHornCPartialAssignmentResult = "Formula: 1 -2 4 0 -1 -2 -3 4 0 1 2 3 -4 0 \n"
                                                                                               "\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Assign literal: -4\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Formula: 1 -2 0 -1 -2 -3 0 \n"
                                                                                               "\n"
                                                                                               "Structural restricted formula representation\n"
                                                                                               "Type: Horn-C\n"
                                                                                               "Formula size: 5\n"
                                                                                               "Number of clauses: 2\n"
                                                                                               "Variables: 1 2 3\n"
                                                                                               "Formula: 1 -2 0 -1 -2 -3 0\n"
                                                                                               "Clause offsets: 0 3\n"
                                                                                               "\n";

    inline std::string structuralRestrictedFormulaRepresentationAntiHornCPartialAssignmentResult = "Formula: -1 2 -4 0 -1 -2 -3 4 0 1 2 3 -4 0 \n"
                                                                                                   "\n"
                                                                                                   "--------------------------------------------------------------------------------\n"
                                                                                                   "Assign literal: 4\n"
                                                                                                   "--------------------------------------------------------------------------------\n"
                                                                                                   "Formula: -1 2 0 1 2 3 0 \n"
                                                                                                   "\n"
                                                                                                   "Structural restricted formula representation\n"
                                                                                                   "Type: anti-Horn-C\n"
                                                                                                   "Formula size: 5\n"
                                                                                                   "Number of clauses: 2\n"
                                                                                                   "Variables: 1 2 3\n"
                                                                                                   "Formula: -1 2 0 1 2 3 0\n"
                                                                                                   "Clause offsets: 0 3\n"
                                                                                                   "\n";

    inline std::string structuralRestrictedFormulaRepresentationRenHCPartialAssignmentResult = "Formula: -1 2 3 -4 0 1 -2 -3 4 0 -4 -5 6 7 0 4 5 -6 -7 0 \n"
                                                                                               "\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Assign literal: 4\n"
                                                                                               "--------------------------------------------------------------------------------\n"
                                                                                               "Formula: -1 2 3 0 -5 6 7 0 \n"
                                                                                               "\n"
                                                                                               "Structural restricted formula representation\n"
                                                                                               "Type: renH-C\n"
                                                                                               "Formula size: 6\n"
                                                                                               "Number of clauses: 2\n"
                                                                                               "Variables: 1 2 3 5 6 7\n"
                                                                                               "Switched variables: 3 7\n"
                                                                                               "Formula: -1 2 3 0 -5 6 7 0\n"
                                                                                               "Clause offsets: 0 4\n"
                                                                                               "\n";

    inline std::string structuralRestrictedFormulaRepresentationConnectedComponentsResult = "Formula: -1 -2 0 1 2 0 -3 -4 0 6 7 0 3 -4 -5 0 -6 7 8 0 \n"
                                                                                            "\n"
                                                                                            "Connected components:\n"
                                                                                            "\t 1 2\n"
                                                                                            "\t 3 4 5\n"
                                                                                            "\t 6 7 8\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Set connected component: 1 2\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Formula: -1 -2 0 1 2 0 \n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "-------Krom-C-------\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: Krom-C\n"
                                                                                            "Formula size: 4\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 1 2\n"
                                                                                            "Formula: -1 -2 0 1 2 0\n"
                                                                                            "Clause offsets: 0 3\n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "-------renH-C-------\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: renH-C\n"
                                                                                            "Formula size: 4\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 1 2\n"
                                                                                            "Switched variables: 2\n"
                                                                                            "Formula: -1 -2 0 1 2 0\n"
                                                                                            "Clause offsets: 0 3\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Pop connected component: 1 2\n"
                                                                                            "----------------------------------------\n"
                                                                                            "--------------------------------------------------------------------------------\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Set connected component: 3 4 5\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Formula: -3 -4 0 3 -4 -5 0 \n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "-------Horn-C-------\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: Horn-C\n"
                                                                                            "Formula size: 5\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 3 4 5\n"
                                                                                            "Formula: -3 -4 0 3 -4 -5 0\n"
                                                                                            "Clause offsets: 0 3\n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "-------renH-C-------\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: renH-C\n"
                                                                                            "Formula size: 5\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 3 4 5\n"
                                                                                            "Switched variables:\n"
                                                                                            "Formula: -3 -4 0 3 -4 -5 0\n"
                                                                                            "Clause offsets: 0 3\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Pop connected component: 3 4 5\n"
                                                                                            "----------------------------------------\n"
                                                                                            "--------------------------------------------------------------------------------\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Set connected component: 6 7 8\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Formula: 6 7 0 -6 7 8 0 \n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "----anti-Horn-C-----\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: anti-Horn-C\n"
                                                                                            "Formula size: 5\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 6 7 8\n"
                                                                                            "Formula: -6 7 8 0 6 7 0\n"
                                                                                            "Clause offsets: 0 4\n"
                                                                                            "\n"
                                                                                            "--------------------\n"
                                                                                            "-------renH-C-------\n"
                                                                                            "--------------------\n"
                                                                                            "Structural restricted formula representation\n"
                                                                                            "Type: renH-C\n"
                                                                                            "Formula size: 5\n"
                                                                                            "Number of clauses: 2\n"
                                                                                            "Variables: 6 7 8\n"
                                                                                            "Switched variables: 6 7 8\n"
                                                                                            "Formula: 6 7 0 -6 7 8 0\n"
                                                                                            "Clause offsets: 0 3\n"
                                                                                            "\n"
                                                                                            "----------------------------------------\n"
                                                                                            "Pop connected component: 6 7 8\n"
                                                                                            "----------------------------------------\n"
                                                                                            "--------------------------------------------------------------------------------\n"
                                                                                            "\n";
}   // namespace HydraTest::Formula::StructuralRestrictedRepresentation
