#pragma once

#include <string>

namespace HydraTest::DecisionHeuristic::JeroslowWang {
    inline std::string jeroslowWangDecisionHeuristicOneSidedResult = "Decision heuristic\n"
                                                                     "Type: Jeroslow-Wang (one-sided)\n"
                                                                     "Ignore pure literal type: pure literals are not ignored\n"
                                                                     "Current formula: 1 -2 0 -4 5 0 5 6 0 -1 3 -6 0 2 3 -6 0 1 -3 4 -7 0 -2 -3 -4 7 0 \n"
                                                                     "\n"
                                                                     "\n"
                                                                     "Selected variables: 1 2 3 4 5 6 7\n"
                                                                     "Decision variable: 5\n"
                                                                     "\n";

    inline std::string jeroslowWangDecisionHeuristicOneSidedSelectedVariablesResult = "Decision heuristic\n"
                                                                                      "Type: Jeroslow-Wang (one-sided)\n"
                                                                                      "Ignore pure literal type: pure literals are not ignored\n"
                                                                                      "Current formula: 1 -2 0 -4 5 0 5 6 0 -1 3 -6 0 2 3 -6 0 1 -3 4 -7 0 -2 -3 -4 7 0 \n"
                                                                                      "\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 2 3 4 6 7\n"
                                                                                      "Decision variable: 1\n"
                                                                                      "\n"
                                                                                      "Selected variables: 4 5 6 7\n"
                                                                                      "Decision variable: 5\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 2 4\n"
                                                                                      "Decision variable: 1\n"
                                                                                      "\n"
                                                                                      "Selected variables: 3 6 7\n"
                                                                                      "Decision variable: 3\n"
                                                                                      "\n"
                                                                                      "Selected variables: 7\n"
                                                                                      "Decision variable: 7\n"
                                                                                      "\n";

    inline std::string jeroslowWangDecisionHeuristicOneSidedIgnorePositivePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: Jeroslow-Wang (one-sided)\n"
                                                                                               "Ignore pure literal type: only positive pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n";

    inline std::string jeroslowWangDecisionHeuristicOneSidedIgnoreNegativePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: Jeroslow-Wang (one-sided)\n"
                                                                                               "Ignore pure literal type: only negative pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n";

    inline std::string jeroslowWangDecisionHeuristicOneSidedIgnorePureLiteralsResult = "Decision heuristic\n"
                                                                                       "Type: Jeroslow-Wang (one-sided)\n"
                                                                                       "Ignore pure literal type: both positive and negative pure literals are ignored\n"
                                                                                       "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                       "\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 2 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 2 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n";

    inline std::string jeroslowWangDecisionHeuristicTwoSidedResult = "Decision heuristic\n"
                                                                     "Type: Jeroslow-Wang (two-sided)\n"
                                                                     "Ignore pure literal type: pure literals are not ignored\n"
                                                                     "Current formula: 1 -2 0 -4 5 0 5 6 0 -1 3 -6 0 2 3 -6 0 1 -3 4 -7 0 -2 -3 -4 7 0 \n"
                                                                     "\n"
                                                                     "\n"
                                                                     "Selected variables: 1 2 3 4 5 6 7\n"
                                                                     "Decision variable: 5\n"
                                                                     "\n";

    inline std::string jeroslowWangDecisionHeuristicTwoSidedSelectedVariablesResult = "Decision heuristic\n"
                                                                                      "Type: Jeroslow-Wang (two-sided)\n"
                                                                                      "Ignore pure literal type: pure literals are not ignored\n"
                                                                                      "Current formula: 1 -2 0 -4 5 0 5 6 0 -1 3 -6 0 2 3 -6 0 1 -3 4 -7 0 -2 -3 -4 7 0 \n"
                                                                                      "\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 2 3 4 6 7\n"
                                                                                      "Decision variable: 6\n"
                                                                                      "\n"
                                                                                      "Selected variables: 2 4 6 7\n"
                                                                                      "Decision variable: 6\n"
                                                                                      "\n"
                                                                                      "Selected variables: 3 4 7\n"
                                                                                      "Decision variable: 3\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 2\n"
                                                                                      "Decision variable: 1\n"
                                                                                      "\n"
                                                                                      "Selected variables: 7\n"
                                                                                      "Decision variable: 7\n"
                                                                                      "\n";

    inline std::string jeroslowWangDecisionHeuristicTwoSidedIgnorePositivePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: Jeroslow-Wang (two-sided)\n"
                                                                                               "Ignore pure literal type: only positive pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n";

    inline std::string jeroslowWangDecisionHeuristicTwoSidedIgnoreNegativePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: Jeroslow-Wang (two-sided)\n"
                                                                                               "Ignore pure literal type: only negative pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 3\n"
                                                                                               "\n";

    inline std::string jeroslowWangDecisionHeuristicTwoSidedIgnorePureLiteralsResult = "Decision heuristic\n"
                                                                                       "Type: Jeroslow-Wang (two-sided)\n"
                                                                                       "Ignore pure literal type: both positive and negative pure literals are ignored\n"
                                                                                       "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 1 -2 3 0 \n"
                                                                                       "\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 2 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 2 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n"
                                                                                       "Selected variables: 3 4\n"
                                                                                       "Decision variable: 3\n"
                                                                                       "\n";
}   // namespace HydraTest::DecisionHeuristic::JeroslowWang
