#pragma once

#include <string>

namespace BellaTest::Compiler::wDNNF {
    inline std::string wDnnfCompilerWDnnfCircuitResult = "Current formula: 1 2 0 1 2 0 -4 -5 0 -4 -5 0 1 2 3 0 -4 -5 -6 0 \n"
                                                         "\n"
                                                         "Circuit - wDNNF\n"
                                                         "Size: 16\n"
                                                         "Number of edges: 16\n"
                                                         "Number of nodes: 19\n"
                                                         "Number of leaves: 14\n"
                                                         "Number of inner nodes: 5\n"
                                                         "Number of used variables: 6\n"
                                                         "Root: 18\n"
                                                         "Used variables: 1 2 3 4 5 6\n"
                                                         "Node types:\n"
                                                         "\tliteral leaf: 12\n"
                                                         "\tconstant leaf: 2\n"
                                                         "\tAND inner node: 1\n"
                                                         "\tOR inner node: 4\n"
                                                         "\n"
                                                         "Nodes:\n"
                                                         "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                         "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                         "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                         "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                         "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                         "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                         "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                         "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                         "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                         "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                         "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                         "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                         "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                         "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                         "14: OR inner node - ID: 14 Size: 2 Is smooth: 0 Children (IDs): 2 4 Variables in circuit: 1 2  Literals in circuit: 1 2 \n"
                                                         "15: OR inner node - ID: 15 Size: 2 Is smooth: 0 Children (IDs): 9 11 Variables in circuit: 4 5  Literals in circuit: -4 -5 \n"
                                                         "16: OR inner node - ID: 16 Size: 3 Is smooth: 0 Children (IDs): 2 4 6 Variables in circuit: 1 2 3  Literals in circuit: 1 2 3 \n"
                                                         "17: OR inner node - ID: 17 Size: 3 Is smooth: 0 Children (IDs): 9 11 13 Variables in circuit: 4 5 6  Literals in circuit: -4 -5 -6 \n"
                                                         "18: AND inner node - ID: 18 Size: 6 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 0 Children (IDs): 14 14 15 15 16 17 Variables in circuit: 1 2 3 4 5 6  Literals in circuit: 1 2 3 -4 -5 -6 \n"
                                                         "\n";

    inline std::string wDnnfCompilerPWDnnfCircuitResult = "Current formula: 1 2 0 1 2 0 -4 -5 0 -4 -5 0 1 2 3 0 -4 -5 -6 0 \n"
                                                          "\n"
                                                          "Circuit - pwDNNF\n"
                                                          "Size: 20\n"
                                                          "Number of edges: 20\n"
                                                          "Number of nodes: 23\n"
                                                          "Number of leaves: 14\n"
                                                          "Number of inner nodes: 9\n"
                                                          "Number of used variables: 6\n"
                                                          "Root: 22\n"
                                                          "Used variables: 1 2 3 4 5 6\n"
                                                          "Node types:\n"
                                                          "\tliteral leaf: 12\n"
                                                          "\tconstant leaf: 2\n"
                                                          "\tAND inner node: 5\n"
                                                          "\tOR inner node: 2\n"
                                                          "\tbinary OR inner node: 2\n"
                                                          "\n"
                                                          "Nodes:\n"
                                                          "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                          "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                          "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                          "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                          "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                          "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                          "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                          "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                          "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                          "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                          "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                          "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                          "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                          "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                          "14: OR inner node - ID: 14 Size: 2 Is smooth: 0 Children (IDs): 2 4 Variables in circuit: 1 2  Literals in circuit: 1 2 \n"
                                                          "15: OR inner node - ID: 15 Size: 3 Is smooth: 0 Children (IDs): 2 4 6 Variables in circuit: 1 2 3  Literals in circuit: 1 2 3 \n"
                                                          "16: AND inner node - ID: 16 Size: 3 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 0 Children (IDs): 14 14 15 Variables in circuit: 1 2 3  Literals in circuit: 1 2 3 \n"
                                                          "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 8 11 Variables in circuit: 4 5  Literals in circuit: 4 -5 \n"
                                                          "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 9 Variables in circuit: 4  Literals in circuit: -4 \n"
                                                          "19: Binary OR inner node - ID: 19 Size: 2 Decision variable: 4 High child (ID): 17 Low child (ID): 18 Is smooth: 0 Variables in circuit: 4 5  Literals in circuit: -4 4 -5 \n"
                                                          "20: AND inner node - ID: 20 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 16 19 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 2 3 -4 4 -5 \n"
                                                          "21: Binary OR inner node - ID: 21 Size: 2 Decision variable: 6 High child (ID): 12 Low child (ID): 13 Is smooth: 1 Variables in circuit: 6  Literals in circuit: -6 6 \n"
                                                          "22: AND inner node - ID: 22 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 20 21 Variables in circuit: 1 2 3 4 5 6  Literals in circuit: 1 2 3 -4 4 -5 -6 6 \n"
                                                          "\n";

    inline std::string wDnnfCompilerNWDnnfCircuitResult = "Current formula: 1 2 0 1 2 0 -4 -5 0 -4 -5 0 1 2 3 0 -4 -5 -6 0 \n"
                                                          "\n"
                                                          "Circuit - nwDNNF\n"
                                                          "Size: 20\n"
                                                          "Number of edges: 20\n"
                                                          "Number of nodes: 23\n"
                                                          "Number of leaves: 14\n"
                                                          "Number of inner nodes: 9\n"
                                                          "Number of used variables: 6\n"
                                                          "Root: 22\n"
                                                          "Used variables: 1 2 3 4 5 6\n"
                                                          "Node types:\n"
                                                          "\tliteral leaf: 12\n"
                                                          "\tconstant leaf: 2\n"
                                                          "\tAND inner node: 5\n"
                                                          "\tOR inner node: 2\n"
                                                          "\tbinary OR inner node: 2\n"
                                                          "\n"
                                                          "Nodes:\n"
                                                          "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                          "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                          "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                          "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                          "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                          "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                          "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                          "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                          "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                          "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                          "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                          "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                          "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                          "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                          "14: OR inner node - ID: 14 Size: 2 Is smooth: 0 Children (IDs): 9 11 Variables in circuit: 4 5  Literals in circuit: -4 -5 \n"
                                                          "15: OR inner node - ID: 15 Size: 3 Is smooth: 0 Children (IDs): 9 11 13 Variables in circuit: 4 5 6  Literals in circuit: -4 -5 -6 \n"
                                                          "16: AND inner node - ID: 16 Size: 3 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 1 Children (IDs): 14 14 15 Variables in circuit: 4 5 6  Literals in circuit: -4 -5 -6 \n"
                                                          "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 2 Variables in circuit: 1  Literals in circuit: 1 \n"
                                                          "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 4 Variables in circuit: 1 2  Literals in circuit: -1 2 \n"
                                                          "19: Binary OR inner node - ID: 19 Size: 2 Decision variable: 1 High child (ID): 17 Low child (ID): 18 Is smooth: 0 Variables in circuit: 1 2  Literals in circuit: -1 1 2 \n"
                                                          "20: AND inner node - ID: 20 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 16 19 Variables in circuit: 1 2 4 5 6  Literals in circuit: -1 1 2 -4 -5 -6 \n"
                                                          "21: Binary OR inner node - ID: 21 Size: 2 Decision variable: 3 High child (ID): 6 Low child (ID): 7 Is smooth: 1 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                          "22: AND inner node - ID: 22 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 20 21 Variables in circuit: 1 2 3 4 5 6  Literals in circuit: -1 1 2 -3 3 -4 -5 -6 \n"
                                                          "\n";

    inline std::string wDnnfCompilerPWDnnfCircuitSingletonResult = "Current formula: 1 -2 0 3 4 0 -5 -6 0 7 8 0 7 -9 0 -10 11 0 -10 -12 0 \n"
                                                                   "\n"
                                                                   "Circuit - pwDNNF\n"
                                                                   "Size: 25\n"
                                                                   "Number of edges: 25\n"
                                                                   "Number of nodes: 37\n"
                                                                   "Number of leaves: 26\n"
                                                                   "Number of inner nodes: 11\n"
                                                                   "Number of used variables: 12\n"
                                                                   "Root: 36\n"
                                                                   "Used variables: 1 2 3 4 5 6 7 8 9 10 11 12\n"
                                                                   "Node types:\n"
                                                                   "\tliteral leaf: 24\n"
                                                                   "\tconstant leaf: 2\n"
                                                                   "\tAND inner node: 5\n"
                                                                   "\tOR inner node: 5\n"
                                                                   "\tbinary OR inner node: 1\n"
                                                                   "\n"
                                                                   "Nodes:\n"
                                                                   "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                   "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                   "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                   "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                   "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                   "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                   "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                   "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                   "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                                   "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                                   "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                                   "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                                   "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                                   "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                                   "14: Literal leaf - ID: 14 Size: 0 Literal: 7 Variable: 7\n"
                                                                   "15: Literal leaf - ID: 15 Size: 0 Literal: -7 Variable: 7\n"
                                                                   "16: Literal leaf - ID: 16 Size: 0 Literal: 8 Variable: 8\n"
                                                                   "17: Literal leaf - ID: 17 Size: 0 Literal: -8 Variable: 8\n"
                                                                   "18: Literal leaf - ID: 18 Size: 0 Literal: 9 Variable: 9\n"
                                                                   "19: Literal leaf - ID: 19 Size: 0 Literal: -9 Variable: 9\n"
                                                                   "20: Literal leaf - ID: 20 Size: 0 Literal: 10 Variable: 10\n"
                                                                   "21: Literal leaf - ID: 21 Size: 0 Literal: -10 Variable: 10\n"
                                                                   "22: Literal leaf - ID: 22 Size: 0 Literal: 11 Variable: 11\n"
                                                                   "23: Literal leaf - ID: 23 Size: 0 Literal: -11 Variable: 11\n"
                                                                   "24: Literal leaf - ID: 24 Size: 0 Literal: 12 Variable: 12\n"
                                                                   "25: Literal leaf - ID: 25 Size: 0 Literal: -12 Variable: 12\n"
                                                                   "26: OR inner node - ID: 26 Size: 2 Is smooth: 0 Children (IDs): 2 5 Variables in circuit: 1 2  Literals in circuit: 1 -2 \n"
                                                                   "27: OR inner node - ID: 27 Size: 2 Is smooth: 0 Children (IDs): 6 8 Variables in circuit: 3 4  Literals in circuit: 3 4 \n"
                                                                   "28: OR inner node - ID: 28 Size: 2 Is smooth: 0 Children (IDs): 11 13 Variables in circuit: 5 6  Literals in circuit: -5 -6 \n"
                                                                   "29: OR inner node - ID: 29 Size: 2 Is smooth: 0 Children (IDs): 14 16 Variables in circuit: 7 8  Literals in circuit: 7 8 \n"
                                                                   "30: OR inner node - ID: 30 Size: 2 Is smooth: 0 Children (IDs): 14 19 Variables in circuit: 7 9  Literals in circuit: 7 -9 \n"
                                                                   "31: AND inner node - ID: 31 Size: 5 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 0 Children (IDs): 26 27 28 29 30 Variables in circuit: 1 2 3 4 5 6 7 8 9  Literals in circuit: 1 -2 3 4 -5 -6 7 8 -9 \n"
                                                                   "32: AND inner node - ID: 32 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 22 25 Variables in circuit: 11 12  Literals in circuit: 11 -12 \n"
                                                                   "33: AND inner node - ID: 33 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 20 32 Variables in circuit: 10 11 12  Literals in circuit: 10 11 -12 \n"
                                                                   "34: AND inner node - ID: 34 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 21 Variables in circuit: 10  Literals in circuit: -10 \n"
                                                                   "35: Binary OR inner node - ID: 35 Size: 2 Decision variable: 10 High child (ID): 33 Low child (ID): 34 Is smooth: 0 Variables in circuit: 10 11 12  Literals in circuit: -10 10 11 -12 \n"
                                                                   "36: AND inner node - ID: 36 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 31 35 Variables in circuit: 1 2 3 4 5 6 7 8 9 10 11 12  Literals in circuit: 1 -2 3 4 -5 -6 7 8 -9 -10 10 11 -12 \n"
                                                                   "\n";

    inline std::string wDnnfCompilerNWDnnfCircuitSingletonResult = "Current formula: 1 -2 0 3 4 0 -5 -6 0 7 8 0 7 -9 0 -10 11 0 -10 -12 0 \n"
                                                                   "\n"
                                                                   "Circuit - nwDNNF\n"
                                                                   "Size: 25\n"
                                                                   "Number of edges: 25\n"
                                                                   "Number of nodes: 37\n"
                                                                   "Number of leaves: 26\n"
                                                                   "Number of inner nodes: 11\n"
                                                                   "Number of used variables: 12\n"
                                                                   "Root: 36\n"
                                                                   "Used variables: 1 2 3 4 5 6 7 8 9 10 11 12\n"
                                                                   "Node types:\n"
                                                                   "\tliteral leaf: 24\n"
                                                                   "\tconstant leaf: 2\n"
                                                                   "\tAND inner node: 5\n"
                                                                   "\tOR inner node: 5\n"
                                                                   "\tbinary OR inner node: 1\n"
                                                                   "\n"
                                                                   "Nodes:\n"
                                                                   "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                   "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                   "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                   "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                   "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                   "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                   "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                   "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                   "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                                   "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                                   "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                                   "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                                   "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                                   "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                                   "14: Literal leaf - ID: 14 Size: 0 Literal: 7 Variable: 7\n"
                                                                   "15: Literal leaf - ID: 15 Size: 0 Literal: -7 Variable: 7\n"
                                                                   "16: Literal leaf - ID: 16 Size: 0 Literal: 8 Variable: 8\n"
                                                                   "17: Literal leaf - ID: 17 Size: 0 Literal: -8 Variable: 8\n"
                                                                   "18: Literal leaf - ID: 18 Size: 0 Literal: 9 Variable: 9\n"
                                                                   "19: Literal leaf - ID: 19 Size: 0 Literal: -9 Variable: 9\n"
                                                                   "20: Literal leaf - ID: 20 Size: 0 Literal: 10 Variable: 10\n"
                                                                   "21: Literal leaf - ID: 21 Size: 0 Literal: -10 Variable: 10\n"
                                                                   "22: Literal leaf - ID: 22 Size: 0 Literal: 11 Variable: 11\n"
                                                                   "23: Literal leaf - ID: 23 Size: 0 Literal: -11 Variable: 11\n"
                                                                   "24: Literal leaf - ID: 24 Size: 0 Literal: 12 Variable: 12\n"
                                                                   "25: Literal leaf - ID: 25 Size: 0 Literal: -12 Variable: 12\n"
                                                                   "26: OR inner node - ID: 26 Size: 2 Is smooth: 0 Children (IDs): 2 5 Variables in circuit: 1 2  Literals in circuit: 1 -2 \n"
                                                                   "27: OR inner node - ID: 27 Size: 2 Is smooth: 0 Children (IDs): 6 8 Variables in circuit: 3 4  Literals in circuit: 3 4 \n"
                                                                   "28: OR inner node - ID: 28 Size: 2 Is smooth: 0 Children (IDs): 11 13 Variables in circuit: 5 6  Literals in circuit: -5 -6 \n"
                                                                   "29: OR inner node - ID: 29 Size: 2 Is smooth: 0 Children (IDs): 21 22 Variables in circuit: 10 11  Literals in circuit: -10 11 \n"
                                                                   "30: OR inner node - ID: 30 Size: 2 Is smooth: 0 Children (IDs): 21 25 Variables in circuit: 10 12  Literals in circuit: -10 -12 \n"
                                                                   "31: AND inner node - ID: 31 Size: 5 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 1 Children (IDs): 26 27 28 29 30 Variables in circuit: 1 2 3 4 5 6 10 11 12  Literals in circuit: 1 -2 3 4 -5 -6 -10 11 -12 \n"
                                                                   "32: AND inner node - ID: 32 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 16 19 Variables in circuit: 8 9  Literals in circuit: 8 -9 \n"
                                                                   "33: AND inner node - ID: 33 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 14 Variables in circuit: 7  Literals in circuit: 7 \n"
                                                                   "34: AND inner node - ID: 34 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 15 32 Variables in circuit: 7 8 9  Literals in circuit: -7 8 -9 \n"
                                                                   "35: Binary OR inner node - ID: 35 Size: 2 Decision variable: 7 High child (ID): 33 Low child (ID): 34 Is smooth: 0 Variables in circuit: 7 8 9  Literals in circuit: -7 7 8 -9 \n"
                                                                   "36: AND inner node - ID: 36 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 31 35 Variables in circuit: 1 2 3 4 5 6 7 8 9 10 11 12  Literals in circuit: 1 -2 3 4 -5 -6 -7 7 8 -9 -10 11 -12 \n"
                                                                   "\n";

    inline std::string wDnnfCompilerWDnnfCircuitCutResult = "Current formula: 1 -2 3 -4 0 1 -2 -4 -5 0 1 2 -3 -4 0 1 2 -4 5 0 \n"
                                                            "\n"
                                                            "Circuit - wDNNF\n"
                                                            "Size: 22\n"
                                                            "Number of edges: 22\n"
                                                            "Number of nodes: 21\n"
                                                            "Number of leaves: 12\n"
                                                            "Number of inner nodes: 9\n"
                                                            "Number of used variables: 5\n"
                                                            "Root: 20\n"
                                                            "Used variables: 1 2 3 4 5\n"
                                                            "Node types:\n"
                                                            "\tliteral leaf: 10\n"
                                                            "\tconstant leaf: 2\n"
                                                            "\tAND inner node: 4\n"
                                                            "\tOR inner node: 4\n"
                                                            "\tbinary OR inner node: 1\n"
                                                            "\n"
                                                            "Nodes:\n"
                                                            "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                            "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                            "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                            "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                            "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                            "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                            "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                            "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                            "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                            "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                            "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                            "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                            "12: OR inner node - ID: 12 Size: 3 Is smooth: 0 Children (IDs): 2 6 9 Variables in circuit: 1 3 4  Literals in circuit: 1 3 -4 \n"
                                                            "13: OR inner node - ID: 13 Size: 3 Is smooth: 0 Children (IDs): 2 9 11 Variables in circuit: 1 4 5  Literals in circuit: 1 -4 -5 \n"
                                                            "14: AND inner node - ID: 14 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 0 Children (IDs): 12 13 Variables in circuit: 1 3 4 5  Literals in circuit: 1 3 -4 -5 \n"
                                                            "15: OR inner node - ID: 15 Size: 3 Is smooth: 0 Children (IDs): 2 7 9 Variables in circuit: 1 3 4  Literals in circuit: 1 -3 -4 \n"
                                                            "16: OR inner node - ID: 16 Size: 3 Is smooth: 0 Children (IDs): 2 9 10 Variables in circuit: 1 4 5  Literals in circuit: 1 -4 5 \n"
                                                            "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 0 Children (IDs): 15 16 Variables in circuit: 1 3 4 5  Literals in circuit: 1 -3 -4 5 \n"
                                                            "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 14 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 2 3 -4 -5 \n"
                                                            "19: AND inner node - ID: 19 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 5 17 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 -2 -3 -4 5 \n"
                                                            "20: Binary OR inner node - ID: 20 Size: 2 Decision variable: 2 High child (ID): 18 Low child (ID): 19 Is smooth: 1 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 -2 2 -3 3 -4 -5 5 \n"
                                                            "\n";

    inline std::string wDnnfCompilerPWDnnfCircuitCutResult = "Current formula: 1 -2 3 4 0 1 -2 4 -5 0 1 2 -3 4 0 1 2 4 5 0 \n"
                                                             "\n"
                                                             "Circuit - pwDNNF\n"
                                                             "Size: 22\n"
                                                             "Number of edges: 22\n"
                                                             "Number of nodes: 21\n"
                                                             "Number of leaves: 12\n"
                                                             "Number of inner nodes: 9\n"
                                                             "Number of used variables: 5\n"
                                                             "Root: 20\n"
                                                             "Used variables: 1 2 3 4 5\n"
                                                             "Node types:\n"
                                                             "\tliteral leaf: 10\n"
                                                             "\tconstant leaf: 2\n"
                                                             "\tAND inner node: 4\n"
                                                             "\tOR inner node: 4\n"
                                                             "\tbinary OR inner node: 1\n"
                                                             "\n"
                                                             "Nodes:\n"
                                                             "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                             "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                             "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                             "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                             "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                             "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                             "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                             "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                             "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                             "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                             "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                             "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                             "12: OR inner node - ID: 12 Size: 3 Is smooth: 0 Children (IDs): 2 6 8 Variables in circuit: 1 3 4  Literals in circuit: 1 3 4 \n"
                                                             "13: OR inner node - ID: 13 Size: 3 Is smooth: 0 Children (IDs): 2 8 11 Variables in circuit: 1 4 5  Literals in circuit: 1 4 -5 \n"
                                                             "14: AND inner node - ID: 14 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 0 Children (IDs): 12 13 Variables in circuit: 1 3 4 5  Literals in circuit: 1 3 4 -5 \n"
                                                             "15: OR inner node - ID: 15 Size: 3 Is smooth: 0 Children (IDs): 2 7 8 Variables in circuit: 1 3 4  Literals in circuit: 1 -3 4 \n"
                                                             "16: OR inner node - ID: 16 Size: 3 Is smooth: 0 Children (IDs): 2 8 10 Variables in circuit: 1 4 5  Literals in circuit: 1 4 5 \n"
                                                             "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 0 Children (IDs): 15 16 Variables in circuit: 1 3 4 5  Literals in circuit: 1 -3 4 5 \n"
                                                             "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 14 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 2 3 4 -5 \n"
                                                             "19: AND inner node - ID: 19 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 5 17 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 -2 -3 4 5 \n"
                                                             "20: Binary OR inner node - ID: 20 Size: 2 Decision variable: 2 High child (ID): 18 Low child (ID): 19 Is smooth: 1 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 -2 2 -3 3 4 -5 5 \n"
                                                             "\n";

    inline std::string wDnnfCompilerNWDnnfCircuitCutResult = "Current formula: -1 -2 3 -4 0 -1 -2 -4 -5 0 -1 2 -3 -4 0 -1 2 -4 5 0 \n"
                                                             "\n"
                                                             "Circuit - nwDNNF\n"
                                                             "Size: 22\n"
                                                             "Number of edges: 22\n"
                                                             "Number of nodes: 21\n"
                                                             "Number of leaves: 12\n"
                                                             "Number of inner nodes: 9\n"
                                                             "Number of used variables: 5\n"
                                                             "Root: 20\n"
                                                             "Used variables: 1 2 3 4 5\n"
                                                             "Node types:\n"
                                                             "\tliteral leaf: 10\n"
                                                             "\tconstant leaf: 2\n"
                                                             "\tAND inner node: 4\n"
                                                             "\tOR inner node: 4\n"
                                                             "\tbinary OR inner node: 1\n"
                                                             "\n"
                                                             "Nodes:\n"
                                                             "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                             "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                             "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                             "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                             "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                             "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                             "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                             "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                             "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                             "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                             "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                             "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                             "12: OR inner node - ID: 12 Size: 3 Is smooth: 0 Children (IDs): 3 6 9 Variables in circuit: 1 3 4  Literals in circuit: -1 3 -4 \n"
                                                             "13: OR inner node - ID: 13 Size: 3 Is smooth: 0 Children (IDs): 3 9 11 Variables in circuit: 1 4 5  Literals in circuit: -1 -4 -5 \n"
                                                             "14: AND inner node - ID: 14 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 1 Children (IDs): 12 13 Variables in circuit: 1 3 4 5  Literals in circuit: -1 3 -4 -5 \n"
                                                             "15: OR inner node - ID: 15 Size: 3 Is smooth: 0 Children (IDs): 3 7 9 Variables in circuit: 1 3 4  Literals in circuit: -1 -3 -4 \n"
                                                             "16: OR inner node - ID: 16 Size: 3 Is smooth: 0 Children (IDs): 3 9 10 Variables in circuit: 1 4 5  Literals in circuit: -1 -4 5 \n"
                                                             "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 0 Is Bella decomposable: 1 Is posBella decomposable: 0 Is negBella decomposable: 1 Children (IDs): 15 16 Variables in circuit: 1 3 4 5  Literals in circuit: -1 -3 -4 5 \n"
                                                             "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 14 Variables in circuit: 1 2 3 4 5  Literals in circuit: -1 2 3 -4 -5 \n"
                                                             "19: AND inner node - ID: 19 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 5 17 Variables in circuit: 1 2 3 4 5  Literals in circuit: -1 -2 -3 -4 5 \n"
                                                             "20: Binary OR inner node - ID: 20 Size: 2 Decision variable: 2 High child (ID): 18 Low child (ID): 19 Is smooth: 1 Variables in circuit: 1 2 3 4 5  Literals in circuit: -1 -2 2 -3 3 -4 -5 5 \n"
                                                             "\n";
}   // namespace BellaTest::Compiler::wDNNF
