#pragma once

#include <string>

namespace HydraTest::Formula::PartialAssignment {
    inline std::string formulaPartialAssignmentConstructorResult = "Empty partial assignment: \n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 0\n"
                                                                   "Are all variables assigned: 1\n"
                                                                   "Literals: \n"
                                                                   "Variables: \n"
                                                                   "\n"
                                                                   "Initialized partial assignment: \n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 3\n"
                                                                   "Are all variables assigned: 1\n"
                                                                   "Literals: 1 -2 3 \n"
                                                                   "Variables: 1 2 3 \n"
                                                                   "\n"
                                                                   "Inconsistent partial assignment: \n"
                                                                   "Attempt to add the complementary literal (-1) to the partial assignment!\n";

    inline std::string formulaPartialAssignmentCopyAndMoveResult = "Partial assignment: \n"
                                                                   "Number of assigned variables: 3\n"
                                                                   "Are all variables assigned: 0\n"
                                                                   "Literals: 1 -2 3 \n"
                                                                   "Variables: 1 2 3 \n"
                                                                   "\n"
                                                                   "Copy method\n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 3\n"
                                                                   "Are all variables assigned: 0\n"
                                                                   "Literals: 1 -2 3 \n"
                                                                   "Variables: 1 2 3 \n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 4\n"
                                                                   "Are all variables assigned: 1\n"
                                                                   "Literals: 1 -2 3 -4 \n"
                                                                   "Variables: 1 2 3 4 \n"
                                                                   "\n"
                                                                   "Move method\n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 3\n"
                                                                   "Are all variables assigned: 0\n"
                                                                   "Literals: 1 -2 3 \n"
                                                                   "Variables: 1 2 3 \n"
                                                                   "\n";

    inline std::string formulaPartialAssignmentAddLiteralsResult = "Partial assignment: \n"
                                                                   "Number of assigned variables: 1\n"
                                                                   "Are all variables assigned: 0\n"
                                                                   "Literals: 1 \n"
                                                                   "Variables: 1 \n"
                                                                   "\n"
                                                                   "Add literal: -2\n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 2\n"
                                                                   "Are all variables assigned: 0\n"
                                                                   "Literals: 1 -2 \n"
                                                                   "Variables: 1 2 \n"
                                                                   "\n"
                                                                   "Add literal: 3\n"
                                                                   "Partial assignment: \n"
                                                                   "Number of assigned variables: 3\n"
                                                                   "Are all variables assigned: 1\n"
                                                                   "Literals: 1 -2 3 \n"
                                                                   "Variables: 1 2 3 \n"
                                                                   "\n"
                                                                   "Add literal: -1\n"
                                                                   "Attempt to add the complementary literal (-1) to the partial assignment!\n"
                                                                   "\n"
                                                                   "Add literal: 1\n"
                                                                   "Attempt to add the literal (1) that already exists in the partial assignment!\n"
                                                                   "\n";

    inline std::string formulaPartialAssignmentRemoveLiteralsResult = "Partial assignment: \n"
                                                                      "Number of assigned variables: 3\n"
                                                                      "Are all variables assigned: 0\n"
                                                                      "Literals: 1 -2 3 \n"
                                                                      "Variables: 1 2 3 \n"
                                                                      "\n"
                                                                      "Remove literal: -2\n"
                                                                      "Partial assignment: \n"
                                                                      "Number of assigned variables: 2\n"
                                                                      "Are all variables assigned: 0\n"
                                                                      "Literals: 1 3 \n"
                                                                      "Variables: 1 3 \n"
                                                                      "\n"
                                                                      "Remove literal: -1\n"
                                                                      "Attempt to delete the complementary literal (-1) from the partial assignment!\n"
                                                                      "\n"
                                                                      "Remove literal: -4\n"
                                                                      "Attempt to delete the literal (-4) that does not exist in the partial assignment!\n"
                                                                      "\n"
                                                                      "Remove literal: 1\n"
                                                                      "Partial assignment: \n"
                                                                      "Number of assigned variables: 1\n"
                                                                      "Are all variables assigned: 0\n"
                                                                      "Literals: 3 \n"
                                                                      "Variables: 3 \n"
                                                                      "\n";

    inline std::string formulaPartialAssignmentExistLiteralsResult = "Partial assignment: \n"
                                                                     "Number of assigned variables: 3\n"
                                                                     "Are all variables assigned: 0\n"
                                                                     "Literals: 1 -2 3 \n"
                                                                     "Variables: 1 2 3 \n"
                                                                     "\n"
                                                                     "Literal exists (-2): 1\n"
                                                                     "Complementary literal exists (-2): 0\n"
                                                                     "Variable exists (2): 1\n"
                                                                     "\n"
                                                                     "Literal exists (-1): 0\n"
                                                                     "Complementary literal exists (-1): 1\n"
                                                                     "Variable exists (1): 1\n"
                                                                     "\n"
                                                                     "Literal exists (-4): 0\n"
                                                                     "Complementary literal exists (-4): 0\n"
                                                                     "Variable exists (4): 0\n"
                                                                     "\n";
}   // namespace HydraTest::Formula::PartialAssignment
