#pragma once

#include <string>

namespace HydraTest::Formula {
    inline std::string formulaLiteralConstructorResult = "Variable: 1\n"
                                                         "Is positive: 1\n"
                                                         "Is negative: 0\n"
                                                         "LiteralT: 2\n"
                                                         "Complementary LiteralT: 3\n"
                                                         "ToString: 1\n"
                                                         "1\n"
                                                         "\n"
                                                         "Variable: 2\n"
                                                         "Is positive: 0\n"
                                                         "Is negative: 1\n"
                                                         "LiteralT: 5\n"
                                                         "Complementary LiteralT: 4\n"
                                                         "ToString: -2\n"
                                                         "-2\n"
                                                         "\n"
                                                         "Variable: 3\n"
                                                         "Is positive: 1\n"
                                                         "Is negative: 0\n"
                                                         "LiteralT: 6\n"
                                                         "Complementary LiteralT: 7\n"
                                                         "ToString: 3\n"
                                                         "3\n"
                                                         "\n";

    inline std::string formulaLiteralCopyAndMoveResult = "Variable: 1\n"
                                                         "Is positive: 0\n"
                                                         "Is negative: 1\n"
                                                         "LiteralT: 3\n"
                                                         "Complementary LiteralT: 2\n"
                                                         "ToString: -1\n"
                                                         "-1\n"
                                                         "\n"
                                                         "Copy method\n"
                                                         "Variable: 1\n"
                                                         "Is positive: 0\n"
                                                         "Is negative: 1\n"
                                                         "LiteralT: 3\n"
                                                         "Complementary LiteralT: 2\n"
                                                         "ToString: -1\n"
                                                         "-1\n"
                                                         "\n"
                                                         "Variable: 1\n"
                                                         "Is positive: 1\n"
                                                         "Is negative: 0\n"
                                                         "LiteralT: 2\n"
                                                         "Complementary LiteralT: 3\n"
                                                         "ToString: 1\n"
                                                         "1\n"
                                                         "\n"
                                                         "Move method\n"
                                                         "Variable: 1\n"
                                                         "Is positive: 0\n"
                                                         "Is negative: 1\n"
                                                         "LiteralT: 3\n"
                                                         "Complementary LiteralT: 2\n"
                                                         "ToString: -1\n"
                                                         "-1\n"
                                                         "\n";

    inline std::string formulaLiteralOperatorsResult = "Negation (1): -1\n"
                                                       "1 == 1: 1\n"
                                                       "1 != 1: 0\n"
                                                       "1 < 1: 0\n"
                                                       "1 > 1: 0\n"
                                                       "\n"
                                                       "1 == -1: 0\n"
                                                       "1 != -1: 1\n"
                                                       "1 < -1: 0\n"
                                                       "1 > -1: 1\n"
                                                       "\n"
                                                       "1 == 2: 0\n"
                                                       "1 != 2: 1\n"
                                                       "1 < 2: 1\n"
                                                       "1 > 2: 0\n"
                                                       "\n"
                                                       "1 == -2: 0\n"
                                                       "1 != -2: 1\n"
                                                       "1 < -2: 1\n"
                                                       "1 > -2: 0\n"
                                                       "\n"
                                                       "Negation (-1): 1\n"
                                                       "-1 == -1: 1\n"
                                                       "-1 != -1: 0\n"
                                                       "-1 < -1: 0\n"
                                                       "-1 > -1: 0\n"
                                                       "\n"
                                                       "-1 == 2: 0\n"
                                                       "-1 != 2: 1\n"
                                                       "-1 < 2: 1\n"
                                                       "-1 > 2: 0\n"
                                                       "\n"
                                                       "-1 == -2: 0\n"
                                                       "-1 != -2: 1\n"
                                                       "-1 < -2: 1\n"
                                                       "-1 > -2: 0\n"
                                                       "\n"
                                                       "Negation (2): -2\n"
                                                       "2 == 2: 1\n"
                                                       "2 != 2: 0\n"
                                                       "2 < 2: 0\n"
                                                       "2 > 2: 0\n"
                                                       "\n"
                                                       "2 == -2: 0\n"
                                                       "2 != -2: 1\n"
                                                       "2 < -2: 0\n"
                                                       "2 > -2: 1\n"
                                                       "\n";
}   // namespace HydraTest::Formula
