#pragma once

#include <string>

namespace HydraTest::Formula::Representation::Contagious::VariableSubsumptionWithMapping {
    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingResult = "Current formula: \n"
                                                                                             "1 0 -2 0 -3 -4 0 -3 4 0 3 -4 0 3 4 0 5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 8 -9 10 0 8 -9 10 0 \n"
                                                                                             "Clauses that variable subsume some clause: 3 4 5 6 7 8 11\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingCurrentComponentResult = "Current formula: \n"
                                                                                                             "1 0 -2 0 -3 -4 0 -3 4 0 3 -4 0 3 4 0 5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 8 -9 10 0 8 -9 10 0 \n"
                                                                                                             "--------------------------------------------------------------------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 1 2\n"
                                                                                                             "Current formula: \n"
                                                                                                             "1 0 -2 0 \n"
                                                                                                             "Clauses that variable subsume some clause:\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 3 4\n"
                                                                                                             "Current formula: \n"
                                                                                                             "-3 -4 0 -3 4 0 3 -4 0 3 4 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 3 4 5\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 5 6 7\n"
                                                                                                             "Current formula: \n"
                                                                                                             "5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 6 7 8\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 8 9 10\n"
                                                                                                             "Current formula: \n"
                                                                                                             "8 -9 10 0 8 -9 10 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 10\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 1 2 3 4\n"
                                                                                                             "Current formula: \n"
                                                                                                             "1 0 -2 0 -3 -4 0 -3 4 0 3 -4 0 3 4 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 3 4 5\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 5 6 7 8 9 10\n"
                                                                                                             "Current formula: \n"
                                                                                                             "5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 8 -9 10 0 8 -9 10 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 6 7 8 10\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n"
                                                                                                             "Current component: 1 2 3 4 5 6 7 8 9 10\n"
                                                                                                             "Current formula: \n"
                                                                                                             "1 0 -2 0 -3 -4 0 -3 4 0 3 -4 0 3 4 0 5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 8 -9 10 0 8 -9 10 0 \n"
                                                                                                             "Clauses that variable subsume some clause: 2 3 4 6 7 8 10\n"
                                                                                                             "--------------------\n"
                                                                                                             "\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingVariableMappingResult = "Current formula: \n"
                                                                                                            "1 0 -2 0 -3 -4 0 -3 4 0 3 -4 0 3 4 0 5 6 0 5 -7 0 -6 -7 0 -5 6 7 0 8 -9 10 0 8 -9 10 0 \n"
                                                                                                            "--------------------------------------------------------------------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping:\n"
                                                                                                            "Clauses that variable subsume some clause: 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 1 -> 2, \n"
                                                                                                            "Clauses that variable subsume some clause: 1 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 2 -> 1, \n"
                                                                                                            "Clauses that variable subsume some clause: 1 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 3 -> 4,  4 -> 3, \n"
                                                                                                            "Clauses that variable subsume some clause: 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 1 -> 3,  2 -> 5, \n"
                                                                                                            "Clauses that variable subsume some clause: 0 1 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 3 -> 5,  4 -> 6, \n"
                                                                                                            "Clauses that variable subsume some clause: 2 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 8 -> 9, \n"
                                                                                                            "Clauses that variable subsume some clause: 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n"
                                                                                                            "Variable mapping: 9 -> 8,  10 -> 8, \n"
                                                                                                            "Clauses that variable subsume some clause: 3 4 5 6 7 8 11\n"
                                                                                                            "--------------------\n"
                                                                                                            "\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingIgnorePositivePureLiteralsResult = "Current formula: \n"
                                                                                                                       "1 0 -2 0 -5 8 0 1 3 4 0 1 -4 5 0 -2 -6 -7 0 -2 7 -8 0 \n"
                                                                                                                       "Clauses that variable subsume some clause: 0 1 3 5\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingIgnoreNegativePureLiteralsResult = "Current formula: \n"
                                                                                                                       "1 0 -2 0 -5 8 0 1 3 4 0 1 -4 5 0 -2 -6 -7 0 -2 7 -8 0 \n"
                                                                                                                       "Clauses that variable subsume some clause: 0 1 3 5\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingIgnorePureLiteralsResult = "Current formula: \n"
                                                                                                               "1 0 -2 0 -5 8 0 1 3 4 0 1 -4 5 0 -2 -6 -7 0 -2 7 -8 0 \n"
                                                                                                               "Clauses that variable subsume some clause: 0 1 3 5\n";

    inline std::string contagiousFormulaRepresentationVariableSubsumptionWithMappingNotIgnorePureLiteralsResult = "Current formula: \n"
                                                                                                                  "1 0 -2 0 -5 8 0 1 3 4 0 1 -4 5 0 -2 -6 -7 0 -2 7 -8 0 \n"
                                                                                                                  "Clauses that variable subsume some clause: 0 1\n";
}   // namespace HydraTest::Formula::Representation::Contagious::VariableSubsumptionWithMapping
