#pragma once

#include <string>

namespace HydraTest::DecisionHeuristic::LiteralCount {
    inline std::string literalCountDecisionHeuristicDlcsResult = "Decision heuristic\n"
                                                                 "Type: dynamic largest combined sum (DLCS)\n"
                                                                 "Ignore pure literal type: pure literals are not ignored\n"
                                                                 "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                 "\n"
                                                                 "\n"
                                                                 "Selected variables: 1 2 3 4 5 6\n"
                                                                 "Decision variable: 2\n"
                                                                 "\n";

    inline std::string literalCountDecisionHeuristicDlcsSelectedVariablesResult = "Decision heuristic\n"
                                                                                  "Type: dynamic largest combined sum (DLCS)\n"
                                                                                  "Ignore pure literal type: pure literals are not ignored\n"
                                                                                  "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                                  "\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1 3 4 5 6\n"
                                                                                  "Decision variable: 3\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1 3 5 6\n"
                                                                                  "Decision variable: 3\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1 5 6\n"
                                                                                  "Decision variable: 6\n"
                                                                                  "\n"
                                                                                  "Selected variables: 4 5\n"
                                                                                  "Decision variable: 4\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1\n"
                                                                                  "Decision variable: 1\n"
                                                                                  "\n";

    inline std::string literalCountDecisionHeuristicDlcsIgnorePositivePureLiteralsResult = "Decision heuristic\n"
                                                                                           "Type: dynamic largest combined sum (DLCS)\n"
                                                                                           "Ignore pure literal type: only positive pure literals are ignored\n"
                                                                                           "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                           "\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 2 3 4\n"
                                                                                           "Decision variable: 2\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 3 4\n"
                                                                                           "Decision variable: 3\n"
                                                                                           "\n"
                                                                                           "Selected variables: 2 3 4\n"
                                                                                           "Decision variable: 2\n"
                                                                                           "\n"
                                                                                           "Selected variables: 3 4\n"
                                                                                           "Decision variable: 3\n"
                                                                                           "\n";

    inline std::string literalCountDecisionHeuristicDlcsIgnoreNegativePureLiteralsResult = "Decision heuristic\n"
                                                                                           "Type: dynamic largest combined sum (DLCS)\n"
                                                                                           "Ignore pure literal type: only negative pure literals are ignored\n"
                                                                                           "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                           "\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 2 3 4\n"
                                                                                           "Decision variable: 1\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 3 4\n"
                                                                                           "Decision variable: 1\n"
                                                                                           "\n"
                                                                                           "Selected variables: 2 3 4\n"
                                                                                           "Decision variable: 3\n"
                                                                                           "\n"
                                                                                           "Selected variables: 3 4\n"
                                                                                           "Decision variable: 3\n"
                                                                                           "\n";

    inline std::string literalCountDecisionHeuristicDlcsIgnorePureLiteralsResult = "Decision heuristic\n"
                                                                                   "Type: dynamic largest combined sum (DLCS)\n"
                                                                                   "Ignore pure literal type: both positive and negative pure literals are ignored\n"
                                                                                   "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                   "\n"
                                                                                   "\n"
                                                                                   "Selected variables: 1 2 3 4\n"
                                                                                   "Decision variable: 3\n"
                                                                                   "\n"
                                                                                   "Selected variables: 1 3 4\n"
                                                                                   "Decision variable: 3\n"
                                                                                   "\n"
                                                                                   "Selected variables: 2 3 4\n"
                                                                                   "Decision variable: 3\n"
                                                                                   "\n"
                                                                                   "Selected variables: 3 4\n"
                                                                                   "Decision variable: 3\n"
                                                                                   "\n";

    inline std::string literalCountDecisionHeuristicDlisResult = "Decision heuristic\n"
                                                                 "Type: dynamic largest individual sum (DLIS)\n"
                                                                 "Ignore pure literal type: pure literals are not ignored\n"
                                                                 "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                 "\n"
                                                                 "\n"
                                                                 "Selected variables: 1 2 3 4 5 6\n"
                                                                 "Decision variable: 6\n"
                                                                 "\n";

    inline std::string literalCountDecisionHeuristicDlisSelectedVariablesResult = "Decision heuristic\n"
                                                                                  "Type: dynamic largest individual sum (DLIS)\n"
                                                                                  "Ignore pure literal type: pure literals are not ignored\n"
                                                                                  "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                                  "\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1 2 3 4 5\n"
                                                                                  "Decision variable: 1\n"
                                                                                  "\n"
                                                                                  "Selected variables: 2 3 5\n"
                                                                                  "Decision variable: 3\n"
                                                                                  "\n"
                                                                                  "Selected variables: 1 3\n"
                                                                                  "Decision variable: 1\n"
                                                                                  "\n"
                                                                                  "Selected variables: 2\n"
                                                                                  "Decision variable: 2\n"
                                                                                  "\n";

    inline std::string literalCountDecisionHeuristicDlisIgnorePositivePureLiteralsResult = "Decision heuristic\n"
                                                                                           "Type: dynamic largest individual sum (DLIS)\n"
                                                                                           "Ignore pure literal type: only positive pure literals are ignored\n"
                                                                                           "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                           "\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 2 3 4\n"
                                                                                           "Decision variable: 2\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 3 4\n"
                                                                                           "Decision variable: 4\n"
                                                                                           "\n"
                                                                                           "Selected variables: 2 3 4\n"
                                                                                           "Decision variable: 2\n"
                                                                                           "\n"
                                                                                           "Selected variables: 3 4\n"
                                                                                           "Decision variable: 4\n"
                                                                                           "\n";

    inline std::string literalCountDecisionHeuristicDlisIgnoreNegativePureLiteralsResult = "Decision heuristic\n"
                                                                                           "Type: dynamic largest individual sum (DLIS)\n"
                                                                                           "Ignore pure literal type: only negative pure literals are ignored\n"
                                                                                           "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                           "\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 2 3 4\n"
                                                                                           "Decision variable: 1\n"
                                                                                           "\n"
                                                                                           "Selected variables: 1 3 4\n"
                                                                                           "Decision variable: 1\n"
                                                                                           "\n"
                                                                                           "Selected variables: 2 3 4\n"
                                                                                           "Decision variable: 4\n"
                                                                                           "\n"
                                                                                           "Selected variables: 3 4\n"
                                                                                           "Decision variable: 4\n"
                                                                                           "\n";

    inline std::string literalCountDecisionHeuristicDlisIgnorePureLiteralsResult = "Decision heuristic\n"
                                                                                   "Type: dynamic largest individual sum (DLIS)\n"
                                                                                   "Ignore pure literal type: both positive and negative pure literals are ignored\n"
                                                                                   "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                   "\n"
                                                                                   "\n"
                                                                                   "Selected variables: 1 2 3 4\n"
                                                                                   "Decision variable: 4\n"
                                                                                   "\n"
                                                                                   "Selected variables: 1 3 4\n"
                                                                                   "Decision variable: 4\n"
                                                                                   "\n"
                                                                                   "Selected variables: 2 3 4\n"
                                                                                   "Decision variable: 4\n"
                                                                                   "\n"
                                                                                   "Selected variables: 3 4\n"
                                                                                   "Decision variable: 4\n"
                                                                                   "\n";

    inline std::string literalCountDecisionHeuristicDlcsDlisResult = "Decision heuristic\n"
                                                                     "Type: DLCS + DLIS as a tie-breaker (DLCS-DLIS)\n"
                                                                     "Ignore pure literal type: pure literals are not ignored\n"
                                                                     "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                     "\n"
                                                                     "\n"
                                                                     "Selected variables: 1 2 3 4 5 6\n"
                                                                     "Decision variable: 3\n"
                                                                     "\n";

    inline std::string literalCountDecisionHeuristicDlcsDlisSelectedVariablesResult = "Decision heuristic\n"
                                                                                      "Type: DLCS + DLIS as a tie-breaker (DLCS-DLIS)\n"
                                                                                      "Ignore pure literal type: pure literals are not ignored\n"
                                                                                      "Current formula: -2 -4 0 2 -4 0 -3 -5 0 1 -3 -6 0 -2 -3 -6 0 2 -3 5 0 1 -2 4 -6 0 1 2 3 -6 0 1 3 5 -6 0 \n"
                                                                                      "\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 2 4 5 6\n"
                                                                                      "Decision variable: 2\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1 5 6\n"
                                                                                      "Decision variable: 6\n"
                                                                                      "\n"
                                                                                      "Selected variables: 4 5\n"
                                                                                      "Decision variable: 4\n"
                                                                                      "\n"
                                                                                      "Selected variables: 1\n"
                                                                                      "Decision variable: 1\n"
                                                                                      "\n";

    inline std::string literalCountDecisionHeuristicDlcsDlisIgnorePositivePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: DLCS + DLIS as a tie-breaker (DLCS-DLIS)\n"
                                                                                               "Ignore pure literal type: only positive pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 4\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 2\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 4\n"
                                                                                               "\n";

    inline std::string literalCountDecisionHeuristicDlcsDlisIgnoreNegativePureLiteralsResult = "Decision heuristic\n"
                                                                                               "Type: DLCS + DLIS as a tie-breaker (DLCS-DLIS)\n"
                                                                                               "Ignore pure literal type: only negative pure literals are ignored\n"
                                                                                               "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                               "\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 2 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 1 3 4\n"
                                                                                               "Decision variable: 1\n"
                                                                                               "\n"
                                                                                               "Selected variables: 2 3 4\n"
                                                                                               "Decision variable: 4\n"
                                                                                               "\n"
                                                                                               "Selected variables: 3 4\n"
                                                                                               "Decision variable: 4\n"
                                                                                               "\n";

    inline std::string literalCountDecisionHeuristicDlcsDlisIgnorePureLiteralsResult = "Decision heuristic\n"
                                                                                       "Type: DLCS + DLIS as a tie-breaker (DLCS-DLIS)\n"
                                                                                       "Ignore pure literal type: both positive and negative pure literals are ignored\n"
                                                                                       "Current formula: 1 0 -2 0 1 3 0 1 -4 0 -2 -3 0 -2 4 0 3 -4 0 1 -2 -3 0 1 -2 -4 0 \n"
                                                                                       "\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 2 3 4\n"
                                                                                       "Decision variable: 4\n"
                                                                                       "\n"
                                                                                       "Selected variables: 1 3 4\n"
                                                                                       "Decision variable: 4\n"
                                                                                       "\n"
                                                                                       "Selected variables: 2 3 4\n"
                                                                                       "Decision variable: 4\n"
                                                                                       "\n"
                                                                                       "Selected variables: 3 4\n"
                                                                                       "Decision variable: 4\n"
                                                                                       "\n";
}   // namespace HydraTest::DecisionHeuristic::LiteralCount
