#pragma once

#include <string>

namespace BellaTest::Compiler::dDNNF {
    inline std::string dDnnfCompilerEmptyFormulaResult = "The formula is empty!\n";

    inline std::string dDnnfCompilerUnsatisfiableFormulaResult = "Current formula: -1 -2 0 1 -2 0 1 2 0 -1 2 -3 0 -1 2 3 0 \n"
                                                                 "\n"
                                                                 "Circuit - d-DNNF\n"
                                                                 "Size: 12\n"
                                                                 "Number of edges: 12\n"
                                                                 "Number of nodes: 13\n"
                                                                 "Number of leaves: 8\n"
                                                                 "Number of inner nodes: 5\n"
                                                                 "Number of used variables: 3\n"
                                                                 "Root: 12\n"
                                                                 "Used variables: 1 2 3\n"
                                                                 "Node types:\n"
                                                                 "\tliteral leaf: 6\n"
                                                                 "\tconstant leaf: 2\n"
                                                                 "\tAND inner node: 2\n"
                                                                 "\tbinary OR inner node: 3\n"
                                                                 "\n"
                                                                 "Nodes:\n"
                                                                 "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                 "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                 "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                 "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                 "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                 "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                 "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                 "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                 "8: AND inner node - ID: 8 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 0 0 Variables in circuit:  Literals in circuit: \n"
                                                                 "9: Binary OR inner node - ID: 9 Size: 2 Decision variable: 1 High child (ID): 2 Low child (ID): 3 Is smooth: 1 Variables in circuit: 1  Literals in circuit: -1 1 \n"
                                                                 "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 2 High child (ID): 4 Low child (ID): 5 Is smooth: 1 Variables in circuit: 2  Literals in circuit: -2 2 \n"
                                                                 "11: Binary OR inner node - ID: 11 Size: 2 Decision variable: 3 High child (ID): 6 Low child (ID): 7 Is smooth: 1 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                                 "12: AND inner node - ID: 12 Size: 4 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 8 9 10 11 Variables in circuit: 1 2 3  Literals in circuit: -1 1 -2 2 -3 3 \n"
                                                                 "\n";

    inline std::string dDnnfCompilerOneUnitClauseResult = "Current formula: -2 0 \n"
                                                          "\n"
                                                          "Circuit - d-DNNF\n"
                                                          "Size: 9\n"
                                                          "Number of edges: 9\n"
                                                          "Number of nodes: 12\n"
                                                          "Number of leaves: 8\n"
                                                          "Number of inner nodes: 4\n"
                                                          "Number of used variables: 3\n"
                                                          "Root: 11\n"
                                                          "Used variables: 1 2 3\n"
                                                          "Node types:\n"
                                                          "\tliteral leaf: 6\n"
                                                          "\tconstant leaf: 2\n"
                                                          "\tAND inner node: 2\n"
                                                          "\tbinary OR inner node: 2\n"
                                                          "\n"
                                                          "Nodes:\n"
                                                          "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                          "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                          "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                          "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                          "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                          "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                          "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                          "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                          "8: AND inner node - ID: 8 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 5 Variables in circuit: 2  Literals in circuit: -2 \n"
                                                          "9: Binary OR inner node - ID: 9 Size: 2 Decision variable: 1 High child (ID): 2 Low child (ID): 3 Is smooth: 1 Variables in circuit: 1  Literals in circuit: -1 1 \n"
                                                          "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 3 High child (ID): 6 Low child (ID): 7 Is smooth: 1 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                          "11: AND inner node - ID: 11 Size: 3 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 8 9 10 Variables in circuit: 1 2 3  Literals in circuit: -1 1 -2 -3 3 \n"
                                                          "\n";

    inline std::string dDnnfCompilerOneClauseResult = "Current formula: 1 -2 0 \n"
                                                      "\n"
                                                      "Circuit - d-DNNF\n"
                                                      "Size: 6\n"
                                                      "Number of edges: 6\n"
                                                      "Number of nodes: 9\n"
                                                      "Number of leaves: 6\n"
                                                      "Number of inner nodes: 3\n"
                                                      "Number of used variables: 2\n"
                                                      "Root: 8\n"
                                                      "Used variables: 1 2\n"
                                                      "Node types:\n"
                                                      "\tliteral leaf: 4\n"
                                                      "\tconstant leaf: 2\n"
                                                      "\tAND inner node: 2\n"
                                                      "\tbinary OR inner node: 1\n"
                                                      "\n"
                                                      "Nodes:\n"
                                                      "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                      "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                      "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                      "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                      "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                      "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                      "6: AND inner node - ID: 6 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 2 Variables in circuit: 1  Literals in circuit: 1 \n"
                                                      "7: AND inner node - ID: 7 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 5 Variables in circuit: 1 2  Literals in circuit: -1 -2 \n"
                                                      "8: Binary OR inner node - ID: 8 Size: 2 Decision variable: 1 High child (ID): 6 Low child (ID): 7 Is smooth: 0 Variables in circuit: 1 2  Literals in circuit: -1 1 -2 \n"
                                                      "\n";

    inline std::string dDnnfCompilerOneClauseSmoothResult = "Current formula: 1 -2 0 \n"
                                                            "\n"
                                                            "Circuit - sd-DNNF\n"
                                                            "Size: 10\n"
                                                            "Number of edges: 10\n"
                                                            "Number of nodes: 11\n"
                                                            "Number of leaves: 6\n"
                                                            "Number of inner nodes: 5\n"
                                                            "Number of used variables: 2\n"
                                                            "Root: 10\n"
                                                            "Used variables: 1 2\n"
                                                            "Node types:\n"
                                                            "\tliteral leaf: 4\n"
                                                            "\tconstant leaf: 2\n"
                                                            "\tAND inner node: 3\n"
                                                            "\tbinary OR inner node: 2\n"
                                                            "\n"
                                                            "Nodes:\n"
                                                            "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                            "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                            "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                            "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                            "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                            "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                            "6: Binary OR inner node - ID: 6 Size: 2 Decision variable: 2 High child (ID): 4 Low child (ID): 5 Is smooth: 1 Variables in circuit: 2  Literals in circuit: -2 2 \n"
                                                            "7: AND inner node - ID: 7 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 6 Variables in circuit: 2  Literals in circuit: -2 2 \n"
                                                            "8: AND inner node - ID: 8 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 2 7 Variables in circuit: 1 2  Literals in circuit: 1 -2 2 \n"
                                                            "9: AND inner node - ID: 9 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 5 Variables in circuit: 1 2  Literals in circuit: -1 -2 \n"
                                                            "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 1 High child (ID): 8 Low child (ID): 9 Is smooth: 1 Variables in circuit: 1 2  Literals in circuit: -1 1 -2 2 \n"
                                                            "\n";

    inline std::string dDnnfCompilerFreeVariablesResult = "Current formula: -2 3 0 \n"
                                                          "\n"
                                                          "Circuit - d-DNNF\n"
                                                          "Size: 13\n"
                                                          "Number of edges: 13\n"
                                                          "Number of nodes: 16\n"
                                                          "Number of leaves: 10\n"
                                                          "Number of inner nodes: 6\n"
                                                          "Number of used variables: 4\n"
                                                          "Root: 15\n"
                                                          "Used variables: 1 2 3 4\n"
                                                          "Node types:\n"
                                                          "\tliteral leaf: 8\n"
                                                          "\tconstant leaf: 2\n"
                                                          "\tAND inner node: 3\n"
                                                          "\tbinary OR inner node: 3\n"
                                                          "\n"
                                                          "Nodes:\n"
                                                          "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                          "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                          "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                          "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                          "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                          "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                          "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                          "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                          "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                          "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                          "10: AND inner node - ID: 10 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 6 Variables in circuit: 2 3  Literals in circuit: 2 3 \n"
                                                          "11: AND inner node - ID: 11 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 5 Variables in circuit: 2  Literals in circuit: -2 \n"
                                                          "12: Binary OR inner node - ID: 12 Size: 2 Decision variable: 2 High child (ID): 10 Low child (ID): 11 Is smooth: 0 Variables in circuit: 2 3  Literals in circuit: -2 2 3 \n"
                                                          "13: Binary OR inner node - ID: 13 Size: 2 Decision variable: 1 High child (ID): 2 Low child (ID): 3 Is smooth: 1 Variables in circuit: 1  Literals in circuit: -1 1 \n"
                                                          "14: Binary OR inner node - ID: 14 Size: 2 Decision variable: 4 High child (ID): 8 Low child (ID): 9 Is smooth: 1 Variables in circuit: 4  Literals in circuit: -4 4 \n"
                                                          "15: AND inner node - ID: 15 Size: 3 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 12 13 14 Variables in circuit: 1 2 3 4  Literals in circuit: -1 1 -2 2 3 -4 4 \n"
                                                          "\n";

    inline std::string dDnnfCompilerFreeVariablesSmoothResult = "Current formula: -2 3 0 \n"
                                                                "\n"
                                                                "Circuit - sd-DNNF\n"
                                                                "Size: 17\n"
                                                                "Number of edges: 17\n"
                                                                "Number of nodes: 18\n"
                                                                "Number of leaves: 10\n"
                                                                "Number of inner nodes: 8\n"
                                                                "Number of used variables: 4\n"
                                                                "Root: 17\n"
                                                                "Used variables: 1 2 3 4\n"
                                                                "Node types:\n"
                                                                "\tliteral leaf: 8\n"
                                                                "\tconstant leaf: 2\n"
                                                                "\tAND inner node: 4\n"
                                                                "\tbinary OR inner node: 4\n"
                                                                "\n"
                                                                "Nodes:\n"
                                                                "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                                "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                                "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 3 High child (ID): 6 Low child (ID): 7 Is smooth: 1 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                                "11: AND inner node - ID: 11 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 10 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                                "12: AND inner node - ID: 12 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 6 Variables in circuit: 2 3  Literals in circuit: 2 3 \n"
                                                                "13: AND inner node - ID: 13 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 5 11 Variables in circuit: 2 3  Literals in circuit: -2 -3 3 \n"
                                                                "14: Binary OR inner node - ID: 14 Size: 2 Decision variable: 2 High child (ID): 12 Low child (ID): 13 Is smooth: 1 Variables in circuit: 2 3  Literals in circuit: -2 2 -3 3 \n"
                                                                "15: Binary OR inner node - ID: 15 Size: 2 Decision variable: 1 High child (ID): 2 Low child (ID): 3 Is smooth: 1 Variables in circuit: 1  Literals in circuit: -1 1 \n"
                                                                "16: Binary OR inner node - ID: 16 Size: 2 Decision variable: 4 High child (ID): 8 Low child (ID): 9 Is smooth: 1 Variables in circuit: 4  Literals in circuit: -4 4 \n"
                                                                "17: AND inner node - ID: 17 Size: 3 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 14 15 16 Variables in circuit: 1 2 3 4  Literals in circuit: -1 1 -2 2 -3 3 -4 4 \n"
                                                                "\n";

    inline std::string dDnnfCompilerFreeVariablesInDecisionNodeResult = "Current formula: -1 2 0 -2 3 0 \n"
                                                                        "\n"
                                                                        "Circuit - d-DNNF\n"
                                                                        "Size: 6\n"
                                                                        "Number of edges: 6\n"
                                                                        "Number of nodes: 11\n"
                                                                        "Number of leaves: 8\n"
                                                                        "Number of inner nodes: 3\n"
                                                                        "Number of used variables: 3\n"
                                                                        "Root: 10\n"
                                                                        "Used variables: 1 2 3\n"
                                                                        "Node types:\n"
                                                                        "\tliteral leaf: 6\n"
                                                                        "\tconstant leaf: 2\n"
                                                                        "\tAND inner node: 2\n"
                                                                        "\tbinary OR inner node: 1\n"
                                                                        "\n"
                                                                        "Nodes:\n"
                                                                        "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                        "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                        "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                        "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                        "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                        "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                        "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                        "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                        "8: AND inner node - ID: 8 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 6 Variables in circuit: 2 3  Literals in circuit: 2 3 \n"
                                                                        "9: AND inner node - ID: 9 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 5 Variables in circuit: 1 2  Literals in circuit: -1 -2 \n"
                                                                        "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 2 High child (ID): 8 Low child (ID): 9 Is smooth: 0 Variables in circuit: 1 2 3  Literals in circuit: -1 -2 2 3 \n"
                                                                        "\n";

    inline std::string dDnnfCompilerFreeVariablesInDecisionNodeSmoothResult = "Current formula: -1 2 0 -2 3 0 \n"
                                                                              "\n"
                                                                              "Circuit - sd-DNNF\n"
                                                                              "Size: 14\n"
                                                                              "Number of edges: 14\n"
                                                                              "Number of nodes: 15\n"
                                                                              "Number of leaves: 8\n"
                                                                              "Number of inner nodes: 7\n"
                                                                              "Number of used variables: 3\n"
                                                                              "Root: 14\n"
                                                                              "Used variables: 1 2 3\n"
                                                                              "Node types:\n"
                                                                              "\tliteral leaf: 6\n"
                                                                              "\tconstant leaf: 2\n"
                                                                              "\tAND inner node: 4\n"
                                                                              "\tbinary OR inner node: 3\n"
                                                                              "\n"
                                                                              "Nodes:\n"
                                                                              "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                              "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                              "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                              "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                              "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                              "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                              "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                              "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                              "8: Binary OR inner node - ID: 8 Size: 2 Decision variable: 1 High child (ID): 2 Low child (ID): 3 Is smooth: 1 Variables in circuit: 1  Literals in circuit: -1 1 \n"
                                                                              "9: AND inner node - ID: 9 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 6 8 Variables in circuit: 1 3  Literals in circuit: -1 1 3 \n"
                                                                              "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 3 High child (ID): 6 Low child (ID): 7 Is smooth: 1 Variables in circuit: 3  Literals in circuit: -3 3 \n"
                                                                              "11: AND inner node - ID: 11 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 10 Variables in circuit: 1 3  Literals in circuit: -1 -3 3 \n"
                                                                              "12: AND inner node - ID: 12 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 4 9 Variables in circuit: 1 2 3  Literals in circuit: -1 1 2 3 \n"
                                                                              "13: AND inner node - ID: 13 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 5 11 Variables in circuit: 1 2 3  Literals in circuit: -1 -2 -3 3 \n"
                                                                              "14: Binary OR inner node - ID: 14 Size: 2 Decision variable: 2 High child (ID): 12 Low child (ID): 13 Is smooth: 1 Variables in circuit: 1 2 3  Literals in circuit: -1 1 -2 2 -3 3 \n"
                                                                              "\n";

    inline std::string dDnnfCompilerTwoDisjointClausesResult = "Current formula: 1 2 0 -3 -4 0 \n"
                                                               "\n"
                                                               "Circuit - d-DNNF\n"
                                                               "Size: 14\n"
                                                               "Number of edges: 14\n"
                                                               "Number of nodes: 17\n"
                                                               "Number of leaves: 10\n"
                                                               "Number of inner nodes: 7\n"
                                                               "Number of used variables: 4\n"
                                                               "Root: 16\n"
                                                               "Used variables: 1 2 3 4\n"
                                                               "Node types:\n"
                                                               "\tliteral leaf: 8\n"
                                                               "\tconstant leaf: 2\n"
                                                               "\tAND inner node: 5\n"
                                                               "\tbinary OR inner node: 2\n"
                                                               "\n"
                                                               "Nodes:\n"
                                                               "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                               "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                               "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                               "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                               "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                               "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                               "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                               "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                               "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                               "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                               "10: AND inner node - ID: 10 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 2 Variables in circuit: 1  Literals in circuit: 1 \n"
                                                               "11: AND inner node - ID: 11 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 4 Variables in circuit: 1 2  Literals in circuit: -1 2 \n"
                                                               "12: Binary OR inner node - ID: 12 Size: 2 Decision variable: 1 High child (ID): 10 Low child (ID): 11 Is smooth: 0 Variables in circuit: 1 2  Literals in circuit: -1 1 2 \n"
                                                               "13: AND inner node - ID: 13 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 6 9 Variables in circuit: 3 4  Literals in circuit: 3 -4 \n"
                                                               "14: AND inner node - ID: 14 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 7 Variables in circuit: 3  Literals in circuit: -3 \n"
                                                               "15: Binary OR inner node - ID: 15 Size: 2 Decision variable: 3 High child (ID): 13 Low child (ID): 14 Is smooth: 0 Variables in circuit: 3 4  Literals in circuit: -3 3 -4 \n"
                                                               "16: AND inner node - ID: 16 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 12 15 Variables in circuit: 1 2 3 4  Literals in circuit: -1 1 2 -3 3 -4 \n"
                                                               "\n";

    inline std::string dDnnfCompilerTwoDisjointClausesSmoothResult = "Current formula: 1 2 0 -3 -4 0 \n"
                                                                     "\n"
                                                                     "Circuit - sd-DNNF\n"
                                                                     "Size: 22\n"
                                                                     "Number of edges: 22\n"
                                                                     "Number of nodes: 21\n"
                                                                     "Number of leaves: 10\n"
                                                                     "Number of inner nodes: 11\n"
                                                                     "Number of used variables: 4\n"
                                                                     "Root: 20\n"
                                                                     "Used variables: 1 2 3 4\n"
                                                                     "Node types:\n"
                                                                     "\tliteral leaf: 8\n"
                                                                     "\tconstant leaf: 2\n"
                                                                     "\tAND inner node: 7\n"
                                                                     "\tbinary OR inner node: 4\n"
                                                                     "\n"
                                                                     "Nodes:\n"
                                                                     "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                     "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                     "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                     "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                     "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                     "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                     "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                     "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                     "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                                     "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                                     "10: Binary OR inner node - ID: 10 Size: 2 Decision variable: 2 High child (ID): 4 Low child (ID): 5 Is smooth: 1 Variables in circuit: 2  Literals in circuit: -2 2 \n"
                                                                     "11: AND inner node - ID: 11 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 10 Variables in circuit: 2  Literals in circuit: -2 2 \n"
                                                                     "12: AND inner node - ID: 12 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 2 11 Variables in circuit: 1 2  Literals in circuit: 1 -2 2 \n"
                                                                     "13: AND inner node - ID: 13 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 3 4 Variables in circuit: 1 2  Literals in circuit: -1 2 \n"
                                                                     "14: Binary OR inner node - ID: 14 Size: 2 Decision variable: 1 High child (ID): 12 Low child (ID): 13 Is smooth: 1 Variables in circuit: 1 2  Literals in circuit: -1 1 -2 2 \n"
                                                                     "15: Binary OR inner node - ID: 15 Size: 2 Decision variable: 4 High child (ID): 8 Low child (ID): 9 Is smooth: 1 Variables in circuit: 4  Literals in circuit: -4 4 \n"
                                                                     "16: AND inner node - ID: 16 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 1 15 Variables in circuit: 4  Literals in circuit: -4 4 \n"
                                                                     "17: AND inner node - ID: 17 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 6 9 Variables in circuit: 3 4  Literals in circuit: 3 -4 \n"
                                                                     "18: AND inner node - ID: 18 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 7 16 Variables in circuit: 3 4  Literals in circuit: -3 -4 4 \n"
                                                                     "19: Binary OR inner node - ID: 19 Size: 2 Decision variable: 3 High child (ID): 17 Low child (ID): 18 Is smooth: 1 Variables in circuit: 3 4  Literals in circuit: -3 3 -4 4 \n"
                                                                     "20: AND inner node - ID: 20 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 14 19 Variables in circuit: 1 2 3 4  Literals in circuit: -1 1 -2 2 -3 3 -4 4 \n"
                                                                     "\n";

    inline std::string dDnnfCompilerInitiallyImpliedLiteralsResult = "Current formula: 1 0 -4 0 -1 2 0 1 3 0 -4 6 0 4 5 0 8 9 0 -9 10 0 -1 3 4 0 1 -3 -4 0 \n"
                                                                     "\n"
                                                                     "Circuit - d-DNNF\n"
                                                                     "Size: 20\n"
                                                                     "Number of edges: 20\n"
                                                                     "Number of nodes: 30\n"
                                                                     "Number of leaves: 22\n"
                                                                     "Number of inner nodes: 8\n"
                                                                     "Number of used variables: 10\n"
                                                                     "Root: 29\n"
                                                                     "Used variables: 1 2 3 4 5 6 7 8 9 10\n"
                                                                     "Node types:\n"
                                                                     "\tliteral leaf: 20\n"
                                                                     "\tconstant leaf: 2\n"
                                                                     "\tAND inner node: 5\n"
                                                                     "\tbinary OR inner node: 3\n"
                                                                     "\n"
                                                                     "Nodes:\n"
                                                                     "0: Constant leaf - ID: 0 Size: 0 Constant: 0\n"
                                                                     "1: Constant leaf - ID: 1 Size: 0 Constant: 1\n"
                                                                     "2: Literal leaf - ID: 2 Size: 0 Literal: 1 Variable: 1\n"
                                                                     "3: Literal leaf - ID: 3 Size: 0 Literal: -1 Variable: 1\n"
                                                                     "4: Literal leaf - ID: 4 Size: 0 Literal: 2 Variable: 2\n"
                                                                     "5: Literal leaf - ID: 5 Size: 0 Literal: -2 Variable: 2\n"
                                                                     "6: Literal leaf - ID: 6 Size: 0 Literal: 3 Variable: 3\n"
                                                                     "7: Literal leaf - ID: 7 Size: 0 Literal: -3 Variable: 3\n"
                                                                     "8: Literal leaf - ID: 8 Size: 0 Literal: 4 Variable: 4\n"
                                                                     "9: Literal leaf - ID: 9 Size: 0 Literal: -4 Variable: 4\n"
                                                                     "10: Literal leaf - ID: 10 Size: 0 Literal: 5 Variable: 5\n"
                                                                     "11: Literal leaf - ID: 11 Size: 0 Literal: -5 Variable: 5\n"
                                                                     "12: Literal leaf - ID: 12 Size: 0 Literal: 6 Variable: 6\n"
                                                                     "13: Literal leaf - ID: 13 Size: 0 Literal: -6 Variable: 6\n"
                                                                     "14: Literal leaf - ID: 14 Size: 0 Literal: 7 Variable: 7\n"
                                                                     "15: Literal leaf - ID: 15 Size: 0 Literal: -7 Variable: 7\n"
                                                                     "16: Literal leaf - ID: 16 Size: 0 Literal: 8 Variable: 8\n"
                                                                     "17: Literal leaf - ID: 17 Size: 0 Literal: -8 Variable: 8\n"
                                                                     "18: Literal leaf - ID: 18 Size: 0 Literal: 9 Variable: 9\n"
                                                                     "19: Literal leaf - ID: 19 Size: 0 Literal: -9 Variable: 9\n"
                                                                     "20: Literal leaf - ID: 20 Size: 0 Literal: 10 Variable: 10\n"
                                                                     "21: Literal leaf - ID: 21 Size: 0 Literal: -10 Variable: 10\n"
                                                                     "22: AND inner node - ID: 22 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 18 20 Variables in circuit: 9 10  Literals in circuit: 9 10 \n"
                                                                     "23: AND inner node - ID: 23 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 16 19 Variables in circuit: 8 9  Literals in circuit: 8 -9 \n"
                                                                     "24: Binary OR inner node - ID: 24 Size: 2 Decision variable: 9 High child (ID): 22 Low child (ID): 23 Is smooth: 0 Variables in circuit: 8 9 10  Literals in circuit: 8 -9 9 10 \n"
                                                                     "25: AND inner node - ID: 25 Size: 5 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 2 4 6 9 10 Variables in circuit: 1 2 3 4 5  Literals in circuit: 1 2 3 -4 5 \n"
                                                                     "26: AND inner node - ID: 26 Size: 2 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 24 25 Variables in circuit: 1 2 3 4 5 8 9 10  Literals in circuit: 1 2 3 -4 5 8 -9 9 10 \n"
                                                                     "27: Binary OR inner node - ID: 27 Size: 2 Decision variable: 6 High child (ID): 12 Low child (ID): 13 Is smooth: 1 Variables in circuit: 6  Literals in circuit: -6 6 \n"
                                                                     "28: Binary OR inner node - ID: 28 Size: 2 Decision variable: 7 High child (ID): 14 Low child (ID): 15 Is smooth: 1 Variables in circuit: 7  Literals in circuit: -7 7 \n"
                                                                     "29: AND inner node - ID: 29 Size: 3 Is (classically) decomposable: 1 Is Bella decomposable: 1 Is posBella decomposable: 1 Is negBella decomposable: 1 Children (IDs): 26 27 28 Variables in circuit: 1 2 3 4 5 6 7 8 9 10  Literals in circuit: 1 2 3 -4 5 -6 6 -7 7 8 -9 9 10 \n"
                                                                     "\n";
}   // namespace BellaTest::Compiler::dDNNF
