#pragma once

#include <string>

namespace HydraTest::Container::VectorSet {
    inline std::string vectorSetConstructorResult = "Vector set: 0 0 0 0 0 0 0 0 0 0\n"
                                                    "Added elements:\n"
                                                    "Number of added elements: 0\n"
                                                    "----------\n"
                                                    "getAddedElementVector:\n"
                                                    "\n";

    inline std::string vectorSetConstructorEmptyResult = "Vector set:\n"
                                                         "Added elements:\n"
                                                         "Number of added elements: 0\n"
                                                         "----------\n"
                                                         "getAddedElementVector:\n"
                                                         "\n"
                                                         "Capacity: 0\n";

    inline std::string vectorSetMoveConstructorAssignmentEmptyResult = "---------------\n"
                                                                       "--- before ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set: 0 0 0 0 0 0 0 0 0 0 0\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 11\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "---- after ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set:\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 0\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "---- moved ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set: 0 0 0 0 0 0 0 0 0 0 0\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 11\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n";

    inline std::string vectorSetMoveConstructorAssignmentFullResult = "---------------\n"
                                                                      "--- before ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set: 1 1 1 1 1 1 1 1 1 1 1 1\n"
                                                                      "Added elements: 0 1 2 3 4 5 6 7 8 9 10 11\n"
                                                                      "Number of added elements: 12\n"
                                                                      "----------\n"
                                                                      "Capacity: 12\n"
                                                                      "getAddedElementVector: 0 1 2 3 4 5 6 7 8 9 10 11\n"
                                                                      "\n"
                                                                      "---------------\n"
                                                                      "---- after ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set:\n"
                                                                      "Added elements:\n"
                                                                      "Number of added elements: 0\n"
                                                                      "----------\n"
                                                                      "Capacity: 0\n"
                                                                      "getAddedElementVector:\n"
                                                                      "\n"
                                                                      "---------------\n"
                                                                      "---- moved ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set: 1 1 1 1 1 1 1 1 1 1 1 1\n"
                                                                      "Added elements: 0 1 2 3 4 5 6 7 8 9 10 11\n"
                                                                      "Number of added elements: 12\n"
                                                                      "----------\n"
                                                                      "Capacity: 12\n"
                                                                      "getAddedElementVector: 0 1 2 3 4 5 6 7 8 9 10 11\n"
                                                                      "\n";

    inline std::string vectorSetMoveConstructorAssignmentEvenResult = "---------------\n"
                                                                      "--- before ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set: 1 0 1 0 1 0 1 0 1 0 1 0 1\n"
                                                                      "Added elements: 0 2 4 6 8 10 12\n"
                                                                      "Number of added elements: 7\n"
                                                                      "----------\n"
                                                                      "Capacity: 13\n"
                                                                      "getAddedElementVector: 0 2 4 6 8 10 12\n"
                                                                      "\n"
                                                                      "---------------\n"
                                                                      "---- after ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set:\n"
                                                                      "Added elements:\n"
                                                                      "Number of added elements: 0\n"
                                                                      "----------\n"
                                                                      "Capacity: 0\n"
                                                                      "getAddedElementVector:\n"
                                                                      "\n"
                                                                      "---------------\n"
                                                                      "---- moved ----\n"
                                                                      "---------------\n"
                                                                      "\n"
                                                                      "Vector set: 1 0 1 0 1 0 1 0 1 0 1 0 1\n"
                                                                      "Added elements: 0 2 4 6 8 10 12\n"
                                                                      "Number of added elements: 7\n"
                                                                      "----------\n"
                                                                      "Capacity: 13\n"
                                                                      "getAddedElementVector: 0 2 4 6 8 10 12\n"
                                                                      "\n";

    inline std::string vectorSetMoveConstructorAssignmentOddResult = "---------------\n"
                                                                     "--- before ----\n"
                                                                     "---------------\n"
                                                                     "\n"
                                                                     "Vector set: 0 1 0 1 0 1 0 1 0 1 0 1 0 1\n"
                                                                     "Added elements: 1 3 5 7 9 11 13\n"
                                                                     "Number of added elements: 7\n"
                                                                     "----------\n"
                                                                     "Capacity: 14\n"
                                                                     "getAddedElementVector: 1 3 5 7 9 11 13\n"
                                                                     "\n"
                                                                     "---------------\n"
                                                                     "---- after ----\n"
                                                                     "---------------\n"
                                                                     "\n"
                                                                     "Vector set:\n"
                                                                     "Added elements:\n"
                                                                     "Number of added elements: 0\n"
                                                                     "----------\n"
                                                                     "Capacity: 0\n"
                                                                     "getAddedElementVector:\n"
                                                                     "\n"
                                                                     "---------------\n"
                                                                     "---- moved ----\n"
                                                                     "---------------\n"
                                                                     "\n"
                                                                     "Vector set: 0 1 0 1 0 1 0 1 0 1 0 1 0 1\n"
                                                                     "Added elements: 1 3 5 7 9 11 13\n"
                                                                     "Number of added elements: 7\n"
                                                                     "----------\n"
                                                                     "Capacity: 14\n"
                                                                     "getAddedElementVector: 1 3 5 7 9 11 13\n"
                                                                     "\n";

    inline std::string vectorSetMoveConstructorAssignmentClearResult = "---------------\n"
                                                                       "-- add full ---\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n"
                                                                       "Added elements: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14\n"
                                                                       "Number of added elements: 15\n"
                                                                       "----------\n"
                                                                       "getAddedElementVector: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "---- clear ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "--- before ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 15\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "---- after ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set:\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 0\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n"
                                                                       "---------------\n"
                                                                       "---- moved ----\n"
                                                                       "---------------\n"
                                                                       "\n"
                                                                       "Vector set: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0\n"
                                                                       "Added elements:\n"
                                                                       "Number of added elements: 0\n"
                                                                       "----------\n"
                                                                       "Capacity: 15\n"
                                                                       "getAddedElementVector:\n"
                                                                       "\n";

    inline std::string vectorSetEmplaceResult = "Vector set: 0 0 0 0 0 0 0 0 0\n"
                                                "Added elements:\n"
                                                "Number of added elements: 0\n"
                                                "----------\n"
                                                "getAddedElementVector:\n"
                                                "\n"
                                                "Add element: 0\n"
                                                "\n"
                                                "Vector set: 1 0 0 0 0 0 0 0 0\n"
                                                "Added elements: 0\n"
                                                "Number of added elements: 1\n"
                                                "----------\n"
                                                "getAddedElementVector: 0\n"
                                                "\n"
                                                "Add element: 1\n"
                                                "\n"
                                                "Vector set: 1 1 0 0 0 0 0 0 0\n"
                                                "Added elements: 0 1\n"
                                                "Number of added elements: 2\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1\n"
                                                "\n"
                                                "Add element: 8\n"
                                                "\n"
                                                "Vector set: 1 1 0 0 0 0 0 0 1\n"
                                                "Added elements: 0 1 8\n"
                                                "Number of added elements: 3\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 8\n"
                                                "\n"
                                                "Add element: 7\n"
                                                "\n"
                                                "Vector set: 1 1 0 0 0 0 0 1 1\n"
                                                "Added elements: 0 1 7 8\n"
                                                "Number of added elements: 4\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 7 8\n"
                                                "\n"
                                                "Add element: 4\n"
                                                "\n"
                                                "Vector set: 1 1 0 0 1 0 0 1 1\n"
                                                "Added elements: 0 1 4 7 8\n"
                                                "Number of added elements: 5\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 4 7 8\n"
                                                "\n"
                                                "Add element: 3\n"
                                                "\n"
                                                "Vector set: 1 1 0 1 1 0 0 1 1\n"
                                                "Added elements: 0 1 3 4 7 8\n"
                                                "Number of added elements: 6\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 3 4 7 8\n"
                                                "\n"
                                                "Add element: 5\n"
                                                "\n"
                                                "Vector set: 1 1 0 1 1 1 0 1 1\n"
                                                "Added elements: 0 1 3 4 5 7 8\n"
                                                "Number of added elements: 7\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 3 4 5 7 8\n"
                                                "\n";

    inline std::string vectorSetEmplaceMultipleOccurrencesResult = "Vector set: 0 0 0 0 0 0 0 0\n"
                                                                   "Added elements:\n"
                                                                   "Number of added elements: 0\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector:\n"
                                                                   "\n"
                                                                   "Add element: 5\n"
                                                                   "\n"
                                                                   "Vector set: 0 0 0 0 0 1 0 0\n"
                                                                   "Added elements: 5\n"
                                                                   "Number of added elements: 1\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector: 5\n"
                                                                   "\n"
                                                                   "Add element: 4\n"
                                                                   "\n"
                                                                   "Vector set: 0 0 0 0 1 1 0 0\n"
                                                                   "Added elements: 4 5\n"
                                                                   "Number of added elements: 2\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector: 4 5\n"
                                                                   "\n"
                                                                   "Add element: 3\n"
                                                                   "\n"
                                                                   "Vector set: 0 0 0 1 1 1 0 0\n"
                                                                   "Added elements: 3 4 5\n"
                                                                   "Number of added elements: 3\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector: 3 4 5\n"
                                                                   "\n"
                                                                   "Add element: 2\n"
                                                                   "\n"
                                                                   "Vector set: 0 0 1 1 1 1 0 0\n"
                                                                   "Added elements: 2 3 4 5\n"
                                                                   "Number of added elements: 4\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector: 2 3 4 5\n"
                                                                   "\n"
                                                                   "Add element: 4\n"
                                                                   "\n"
                                                                   "Vector set: 0 0 1 1 1 1 0 0\n"
                                                                   "Added elements: 2 3 4 5\n"
                                                                   "Number of added elements: 4\n"
                                                                   "----------\n"
                                                                   "getAddedElementVector: 2 3 4 5\n"
                                                                   "\n";

    inline std::string vectorSetEmplaceWithCheckExistenceMultipleOccurrencesResult = "Vector set: 0 0 0 0 0 0 0 0\n"
                                                                                     "Added elements:\n"
                                                                                     "Number of added elements: 0\n"
                                                                                     "----------\n"
                                                                                     "getAddedElementVector:\n"
                                                                                     "\n"
                                                                                     "Add element: 5\n"
                                                                                     "\n"
                                                                                     "Vector set: 0 0 0 0 0 1 0 0\n"
                                                                                     "Added elements: 5\n"
                                                                                     "Number of added elements: 1\n"
                                                                                     "----------\n"
                                                                                     "getAddedElementVector: 5\n"
                                                                                     "\n"
                                                                                     "Add element: 4\n"
                                                                                     "\n"
                                                                                     "Vector set: 0 0 0 0 1 1 0 0\n"
                                                                                     "Added elements: 4 5\n"
                                                                                     "Number of added elements: 2\n"
                                                                                     "----------\n"
                                                                                     "getAddedElementVector: 4 5\n"
                                                                                     "\n"
                                                                                     "Add element: 3\n"
                                                                                     "\n"
                                                                                     "Vector set: 0 0 0 1 1 1 0 0\n"
                                                                                     "Added elements: 3 4 5\n"
                                                                                     "Number of added elements: 3\n"
                                                                                     "----------\n"
                                                                                     "getAddedElementVector: 3 4 5\n"
                                                                                     "\n"
                                                                                     "Add element: 2\n"
                                                                                     "\n"
                                                                                     "Vector set: 0 0 1 1 1 1 0 0\n"
                                                                                     "Added elements: 2 3 4 5\n"
                                                                                     "Number of added elements: 4\n"
                                                                                     "----------\n"
                                                                                     "getAddedElementVector: 2 3 4 5\n"
                                                                                     "\n"
                                                                                     "Add element: 4\n"
                                                                                     "\n"
                                                                                     "Attempt to add the element (4) multiple times to the set!\n";

    inline std::string vectorSetAddFullResult = "---------------\n"
                                                "-- add full ---\n"
                                                "---------------\n"
                                                "\n"
                                                "Vector set: 1 1 1 1 1 1 1\n"
                                                "Added elements: 0 1 2 3 4 5 6\n"
                                                "Number of added elements: 7\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 1 2 3 4 5 6\n"
                                                "\n";

    inline std::string vectorSetAddEvenResult = "---------------\n"
                                                "-- add even ---\n"
                                                "---------------\n"
                                                "\n"
                                                "Vector set: 1 0 1 0 1 0\n"
                                                "Added elements: 0 2 4\n"
                                                "Number of added elements: 3\n"
                                                "----------\n"
                                                "getAddedElementVector: 0 2 4\n"
                                                "\n";

    inline std::string vectorSetAddOddResult = "---------------\n"
                                               "--- add odd ---\n"
                                               "---------------\n"
                                               "\n"
                                               "Vector set: 0 1 0 1 0\n"
                                               "Added elements: 1 3\n"
                                               "Number of added elements: 2\n"
                                               "----------\n"
                                               "getAddedElementVector: 1 3\n"
                                               "\n";

    inline std::string vectorSetClearFullResult = "---------------\n"
                                                  "-- add full ---\n"
                                                  "---------------\n"
                                                  "\n"
                                                  "Vector set: 1 1 1 1\n"
                                                  "Added elements: 0 1 2 3\n"
                                                  "Number of added elements: 4\n"
                                                  "----------\n"
                                                  "getAddedElementVector: 0 1 2 3\n"
                                                  "\n"
                                                  "---------------\n"
                                                  "---- clear ----\n"
                                                  "---------------\n"
                                                  "\n"
                                                  "Vector set: 0 0 0 0\n"
                                                  "Added elements:\n"
                                                  "Number of added elements: 0\n"
                                                  "----------\n"
                                                  "getAddedElementVector:\n"
                                                  "\n";

    inline std::string vectorSetClearEvenResult = "---------------\n"
                                                  "-- add even ---\n"
                                                  "---------------\n"
                                                  "\n"
                                                  "Vector set: 1 0 1 0 1\n"
                                                  "Added elements: 0 2 4\n"
                                                  "Number of added elements: 3\n"
                                                  "----------\n"
                                                  "getAddedElementVector: 0 2 4\n"
                                                  "\n"
                                                  "---------------\n"
                                                  "---- clear ----\n"
                                                  "---------------\n"
                                                  "\n"
                                                  "Vector set: 0 0 0 0 0\n"
                                                  "Added elements:\n"
                                                  "Number of added elements: 0\n"
                                                  "----------\n"
                                                  "getAddedElementVector:\n"
                                                  "\n";

    inline std::string vectorSetClearOddResult = "---------------\n"
                                                 "--- add odd ---\n"
                                                 "---------------\n"
                                                 "\n"
                                                 "Vector set: 0 1 0 1 0 1\n"
                                                 "Added elements: 1 3 5\n"
                                                 "Number of added elements: 3\n"
                                                 "----------\n"
                                                 "getAddedElementVector: 1 3 5\n"
                                                 "\n"
                                                 "---------------\n"
                                                 "---- clear ----\n"
                                                 "---------------\n"
                                                 "\n"
                                                 "Vector set: 0 0 0 0 0 0\n"
                                                 "Added elements:\n"
                                                 "Number of added elements: 0\n"
                                                 "----------\n"
                                                 "getAddedElementVector:\n"
                                                 "\n";

    inline std::string vectorSetClearEmptyResult = "Vector set: 0 0 0 0 0 0 0\n"
                                                   "Added elements:\n"
                                                   "Number of added elements: 0\n"
                                                   "----------\n"
                                                   "getAddedElementVector:\n"
                                                   "\n"
                                                   "---------------\n"
                                                   "---- clear ----\n"
                                                   "---------------\n"
                                                   "\n"
                                                   "Vector set: 0 0 0 0 0 0 0\n"
                                                   "Added elements:\n"
                                                   "Number of added elements: 0\n"
                                                   "----------\n"
                                                   "getAddedElementVector:\n"
                                                   "\n";

    inline std::string vectorSetContainsFullResult = "---------------\n"
                                                     "-- add full ---\n"
                                                     "---------------\n"
                                                     "\n"
                                                     "Vector set: 1 1 1 1 1 1 1 1\n"
                                                     "Added elements: 0 1 2 3 4 5 6 7\n"
                                                     "Number of added elements: 8\n"
                                                     "----------\n"
                                                     "getAddedElementVector: 0 1 2 3 4 5 6 7\n"
                                                     "\n"
                                                     "Element 0: 1\n"
                                                     "Element 1: 1\n"
                                                     "Element 2: 1\n"
                                                     "Element 3: 1\n"
                                                     "Element 4: 1\n"
                                                     "Element 5: 1\n"
                                                     "Element 6: 1\n"
                                                     "Element 7: 1\n";

    inline std::string vectorSetContainsEvenResult = "---------------\n"
                                                     "-- add even ---\n"
                                                     "---------------\n"
                                                     "\n"
                                                     "Vector set: 1 0 1 0 1 0 1 0\n"
                                                     "Added elements: 0 2 4 6\n"
                                                     "Number of added elements: 4\n"
                                                     "----------\n"
                                                     "getAddedElementVector: 0 2 4 6\n"
                                                     "\n"
                                                     "Element 0: 1\n"
                                                     "Element 1: 0\n"
                                                     "Element 2: 1\n"
                                                     "Element 3: 0\n"
                                                     "Element 4: 1\n"
                                                     "Element 5: 0\n"
                                                     "Element 6: 1\n"
                                                     "Element 7: 0\n";

    inline std::string vectorSetContainsOddResult = "---------------\n"
                                                    "--- add odd ---\n"
                                                    "---------------\n"
                                                    "\n"
                                                    "Vector set: 0 1 0 1 0 1 0 1\n"
                                                    "Added elements: 1 3 5 7\n"
                                                    "Number of added elements: 4\n"
                                                    "----------\n"
                                                    "getAddedElementVector: 1 3 5 7\n"
                                                    "\n"
                                                    "Element 0: 0\n"
                                                    "Element 1: 1\n"
                                                    "Element 2: 0\n"
                                                    "Element 3: 1\n"
                                                    "Element 4: 0\n"
                                                    "Element 5: 1\n"
                                                    "Element 6: 0\n"
                                                    "Element 7: 1\n";

    inline std::string vectorSetContainsEmptyResult = "Vector set: 0 0 0 0 0 0 0 0\n"
                                                      "Added elements:\n"
                                                      "Number of added elements: 0\n"
                                                      "----------\n"
                                                      "getAddedElementVector:\n"
                                                      "\n"
                                                      "Element 0: 0\n"
                                                      "Element 1: 0\n"
                                                      "Element 2: 0\n"
                                                      "Element 3: 0\n"
                                                      "Element 4: 0\n"
                                                      "Element 5: 0\n"
                                                      "Element 6: 0\n"
                                                      "Element 7: 0\n";
}   // namespace HydraTest::Container::VectorSet
